### ISSUE TITLE
NavBar Behavior

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#10]
I think it's good to have a reference to [this](https://notepad-plus-plus.org/community/topic/11116/compare-plugin/7) issue.

**Comment by pnedev** [comment]
Yes, indeed. Thanks.

**Comment by pnedev** [comment]
Hello Yaron,

This is fixed in master branch. NavBar can be further optimized but that is another matter.
Closing this now.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. Thank you.

I really don't know how the NavBar should work and display the overall diffs.
As for [this](https://notepad-plus-plus.org/community/topic/11116/compare-plugin/7) issue: unchecking “Ignore Spacing” and comparing the files in Test.zip, I get a different image than both posted by Doutei. :)

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Yes, there are still some issues. I'll check that.
Thanks.

BR

**Comment by Yaron10** [comment]
Thank you Pavel. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

One a bit "strange" question - What is the resolution of your monitor?

The current NavBar looks exactly as the first image from Doutei if you have a vertical resolution greater than the number of lines in the compared documents (the bigger number from the two).
This is because each vertical pixel in the NavBar bitmap currently represents one line from the compare and if you have less vertical screen resolution than the compared lines some get overwritten.
This is a problem of course and as I said there are still some issues and things to be fixed. I just wanted to clarify :)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for everything.
Just when we get to the interesting part (the Compares and layout handling; - not the NavBar) I hardly have a free minute.
Tomorrow I probably won't be by a PC. I'm looking forward to Friday. :)

My resolution is 1360x768.

The "Select First" is a truly brilliant idea.
How about "Compare current to last active"?

I'll elaborate on that and other issues.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Don't worry, we'll discuss things further when you have time, thanks.

> How about "Compare current to last active"?

I see what you mean. That's interesting but I think it might get a bit confusing for the user and it will add another compare command to the plugin menu (which seems a bit too much).

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Some screenshots of the NavBar on my machine.

Thank you.

BR

[NavBar.zip](https://github.com/pnedev/compare-plugin/files/210384/NavBar.zip)

**Comment by pnedev** [comment]
Thank you, I'll investigate it sometime in the future.

BR

**Comment by Yaron10** [comment]
Great. Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I've made a lot of modifications and optimizations to the NavBar and basically it should be functional and working OK now. There might still be some issues but nothing critical I hope. I'll clean them regularly as those pop-up, thanks.
I'm closing this issue now.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

As you know I hardly use the NavBar.
Anyway - using Doutei's [comment and images](https://notepad-plus-plus.org/community/topic/11116/compare-plugin/7) as a reference point, your work seems great as always. :)

Thank you very much.
BR

**Comment by pnedev** [comment]
Thanks Yaron.

BR
