### ISSUE TITLE
Provide x64 build

### ISSUE THREAD

**Issue by phsc** [pnedev/compare-plugin#101]
In the README I saw, that the x64 builds currently have BETA status. Could you still please provide an x64 build?

Otherwise it is impossible for users without Visual Studio to test the latest version of the compare plugin (the latest Sourceforge build is from June 2010).

**Comment by pnedev** [comment]
I'm trying to keep the original repository at https://github.com/jsleroy/compare-plugin completely up-to-date with the modifications I commit here in the master branch thus the latest build in all its variants can be found here:
https://ci.appveyor.com/project/jsleroy/compare-plugin

The toolset v140_xp refers to VS2015 builds, v120_xp is for VS2013 builds.
You can get release or debug version in x64 or x86 variant (x64: 64-bit, Win32: 32-bit).
Select the build you like and click on it, then select _Artifacts_ on the right, just above the console output window. You will find the corresponding DLL there.

**Comment by phsc** [comment]
Great! Thank you for the explanation!
