### ISSUE TITLE
Some issues after latest engine refactoring 

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#102]
Hello Pavel,

Could you please compare [these files](https://github.com/pnedev/compare-plugin/files/643366/TEST.zip)?

![InsertText](https://s27.postimg.org/8v0gwhihv/Wrong_Diffs.png)

3 problems in the new file at top:
1) In line 4 you get both "Plus" and "Diff" marks.
2) In line 4 some of the text is wrongly highlighted (in brown).
3) line 5 is not highlighted.

You warned me about possible regressions after the latest refactoring.
I think it's expected and natural after such a major work. One more push. :)

Thank you very much. I appreciate it.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll have a look, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you and best of luck.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

A minor regression:
Please compare the files posted above in Wrap mode.

![InsertText](https://s18.postimg.org/fhqo28dbt/Wrap_Wrong.png)

The window is not repainted after the insertion of the Compare-Margin and, as a result, the text is cut off.
It's displayed properly after manually refreshing the window (this was not necessary up until one of the recent commits).

With the last version available on [Dropbox](https://www.dropbox.com/sh/f42cxkqppuapa1j/AADvlcmqoK_myRmoOpeL1yGMa?dl=0):
 
![InsertText](https://s24.postimg.org/84udqz0o5/Wrap_OK.png)

Thank you very much for your time and great work.
BR

**Comment by pnedev** [comment]
Hello Yaron,

The second regression (about the margins) is fixed.
Thanks for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the quick fix. Great.

Regarding the first issue:
You have been doing a *mammoth* work. I suppose the engine algorithm is quite complex and normally a full team of developers would work on it. 
Allow me to ask you to relax and take it easy. :)

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for the concern :)
I suspected the first issue might appear at some point and it is related to the results colorization.
I'll need more free time to fix it though.
It should be appearing (in a different form perhaps) even in the old implementation.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Thanks for the concern :)

Do take it seriously. :)

> I'll need more free time to fix it though.

Sure.
I'll write it again: the work you've undertaken and accomplished is literally amazing. 
Have some rest.

Thank you very much. Highly appreciated.
BR

**Comment by pnedev** [comment]
Hello Yaron,

The latest master branch commit (https://github.com/pnedev/compare-plugin/commit/820b474232a8ffe50ab828dc6649ec52e5a5dc0e) fixes the colorization issues.
As there are no more critical issues and the CP is already quite stable and mature I'm about to officially release version 2.0.0 this weekend. Please write back if you come across any regressions.

Thank you for all the suggestions, discussions, testing and issue reporting. You did a great job detecting CP problems throughout all the development process. I appreciate that.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for fixing this issue. Great work as always.

[Congratulations and Thank You](https://github.com/pnedev/compare-plugin/issues/103).

Best regards.
