### ISSUE TITLE
Compare resets zoom level

### ISSUE THREAD

**Issue by ganego** [pnedev/compare-plugin#104]
I just updated from the old compare to your v2.0 version, thank you for updating it.

I use a higher than normal zoom level in npp (via CTRL + mousewheelscroll), the old version had the problem that this would not work well (left view was zoomed, right one not). It seems you fixed this by resetting the zoom level to default(?).

Could you instead either set the zoom level I had for my main npp window to both the left and right compare window or at least when closing the compare reset it to the zoom level it was before?

**Comment by Yaron10** [comment]
Hello Pavel and @ganego,

The zoom level in both views (or panels) is determined by the active view after Compare.
Until Pavel fixes this issue, please open Compare -> Settings  and  change "Old file position" to "Left/Top".

Best regards.

**Comment by Yaron10** [comment]
Change "Old file position" to "Right/Bottom".
Sorry.

**Comment by ganego** [comment]
I just realized that if I use zoom on the panels so that they are the same size as my normal view, they will remember this setting. So (when I don't change the zoom level) both compare and normal view will have the same zoom. Works ok as a workaround if it's not possible to get the zoom from the main view panel and apply them to both compare panels (I don't know what plugins can do in npp).

**Comment by Yaron10** [comment]
Yes, NPP saves the zoom level of each view separately. 
Your reported issue is a problem if the SUB-VIEW zoom level has not been changed.
I hope Pavel will kindly fix it (set zoom level in both views according to the active view **before** Compare).

**Comment by pnedev** [comment]
Hello @ganego and @Yaron10 ,

I'll have a look at Monday, thanks.

BR

**Comment by pnedev** [comment]
Hello again,

The zoom issue is fixed in commit https://github.com/pnedev/compare-plugin/commit/32d674b4e4e11eaba7184f788bb056895a4c7d8e.
You can find the x64 build at https://ci.appveyor.com/api/buildjobs/w82wvhvuvh8ty5an/artifacts/ComparePlugin.dll
and the x86 build at https://ci.appveyor.com/api/buildjobs/dw4t9rrqopxwj77i/artifacts/ComparePlugin.dll.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I was just about to thank you for looking into it.
Now I can thank you for fixing it. Great.

BR

**Comment by pnedev** [comment]
Hello Yaron,

You are welcome, thank you.

BR
