### ISSUE TITLE
[Request] Insert blank lines as counterparts to added/removed/moved lines

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#109]
Hello Pavel,

Continued from https://github.com/pnedev/compare-plugin/issues/108#issuecomment-278982841.

Summery:
In case of having a large sequence of added/removed/moved lines - inserting blank lines as their counterparts improves clarity.

![image](https://cloud.githubusercontent.com/assets/10229320/22831626/b99263f6-efb3-11e6-9fcd-d92394d8a987.png)

vs.

![image](https://cloud.githubusercontent.com/assets/10229320/22831653/d23bd2b6-efb3-11e6-9484-aad7628acd67.png)

In other cases placing "+" lines against "-" lines may be clearer.

![image](https://cloud.githubusercontent.com/assets/10229320/22831981/fe824be2-efb4-11e6-9917-27eda42d0f60.png)

vs.

![image](https://cloud.githubusercontent.com/assets/10229320/22831955/e9768be6-efb4-11e6-83b2-39b11cadf04f.png)

Thank you for agreeing to restore the old results representation with blanks against the + and - lines. I do appreciate it.

Do you find the current implementation better and want to keep it?
This would mean a user-choice between these two methods.

If you don't want to keep the current implementation... 
A few months ago we all agreed that the no-blank-lines-at-all method wasn't useful.
I'm not so sure about that now (as explained above).
So the preference can be "Insert Blank Lines" (old "Align Matches").

Or no preference at all and only "Insert Blank Lines" implementation?

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for creating the feature request.

> Do you find the current implementation better and want to keep it?
This would mean a user-choice between these two methods.

I most certainly do. User setting about the results representation is needed.

> Or no preference at all and only "Insert Blank Lines" implementation?

Exactly. _Align matches_ is something from the past - this should always be the case.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

That's great. 
Thanks again. I do appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

One thing - do you have any idea for this user setting name. I cannot think of a suitable enough name for that option at the moment.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I've had a busy day and I'm literally exhausted.
I'll write tomorrow.

Thank you for your great work. I haven't tried anything yet but I'm impressed. :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

No problem at all, hope everything is fine.
Get some rest.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Your feature request is implemented with in https://github.com/pnedev/compare-plugin/commit/5c1bfb0ef489a7ebfdb7a3a9b9bf626f6e56e50e.
Could you please verify it when you have more time?
I couldn't test it extensively.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I'm fine.
I hope you're as well. Now you have to be dealing with more requests and questions. :)

> do you have any idea for this user setting name?

It *is* a tough one.

`Insert blank lines for non-matches` (short but not very accurate - changed lines).
`Insert blanks for added/removed/moved lines` (clearer and accurate but too long?).
`Insert blanks for added/removed lines` (shorter but not complete).

What do you think? What did you have in mind?
I suppose you plan to add this preference to the menu, correct?

Thanks again for your brilliant work. I do appreciate it.

BR

**Comment by Yaron10** [comment]
Hello again Pavel,

I saw your last post after typing my reply.
I'll test it later.

Thank you so much!

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I've tested it with a few pairs of files and it seems to be working perfectly. 
Thank you very much.

"Align Replacements" is very nice. 👍 
I think the preferred results display might (also) depend on the compared files' contents.
Wouldn't it indeed be better to include it in the menu?

BR

**Comment by pnedev** [comment]
Hello Yaron,

Is it really needed in the menu? I look at this setting more like a user preference than a per-compare switchable option. Having it in the menu actually adds another N++ command - I prefer not to put it there unless it really hurts usability.
I trust your judgement on this.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I haven't still used it in a real compare session.
Still, don't you think that it can be convenient to quickly change the display according to the (per) compare results?
If you have some 50 replacements in a row, you might find the extra blank lines helpful; and if you then switch to another pair with 10 replacements here and there, the other method might be clearer.
I even considered adding a toolbar button for this switch (for my personal use).

Your wish is my command (or setting). :)

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I really don't know if that's useful or not. From my perspective it is not justified but my CP use-cases are rather simple and do not involve dynamically changing results representation.
If that will be useful for you personally to have that as an option (and eventually to be able to add icon for your personal use) that would probably be useful to others too so I will change the setting to be in the menu.
I leave the decision to you.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

IMO it can certainly be a per Compare preference.
It's not that important though, and I'd rather save my quota of legit arguments with you to other things. :) :)

Thank you for your kindness. I appreciate it.
BR

**Comment by pnedev** [comment]
Hello Yaron,

:) OK, I'll leave it as it is for the moment.
If we find in the future uses that having this option per-compare is better then I'll change it.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. Thank you.
And thanks again for adding this option.

BR

**Comment by pnedev** [comment]
Hello @Yaron10 ,

That option is not working with the latest master branch changes (see issue https://github.com/pnedev/compare-plugin/issues/122). Sorry for that, I'll see what I can do but due to the new alignment implementation it is getting difficult support that.

BR

**Comment by pnedev** [comment]
Hello @Yaron10 ,

Because of the change in the alignment approach and the frequent need for realignments (due to word-wrapping and unequally split vertical panes) this feature is difficult to implement.

If you don't consider it that important for your workflow I'd like to drop this setting/feature.
If you'd very much like to have it I'll consider implementing it some time in the future.

Tell me what you think when you have time, thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

The new alignment implementation and the much clearer results are certainly worth removing this method.

Thank you very much.
I appreciate your kindness.

BR

**Comment by pnedev** [comment]
Thank you.

BR
