### ISSUE TITLE
A Lite Compare version

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#11]
Hello Pavel,

I never use the NavBar. Do you?
I also don't use "Compare to Git" and "Compare to SVN".

IMO, "Use old symbols" (in Options) can be removed.

What do you think about a Lite Compare version without those components?
(Some day in the future when the more urgent tasks have been accomplished). :)

Best regards.

**Comment by pnedev** [comment]
Hi Yaron,

Hm, interesting proposal.
I haven't used Compare plugin before but when I'm comparing bigger files with other compare software I'm using its NavBar. It seems to be useful for quick preview of the differences and their places in the documents.

About Git and SVN - those look to me as a good to have features - let's keep them for now.

> IMO, "Use old symbols" (in Options) can be removed.

I'll have to check, thanks.

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

NavBar, Git and SVN:
I was thinking of Compare Lite in addition to the full version (not as a replacement).
Git and SVN may not slow down the comparing process but the NavBar certainly does.

IMO, "Use old symbols" can be removed in both versions. :)

Thank you.
BR.

**Comment by pnedev** [comment]
Hi Yaron,

1) I think Git and SVN doesn't hurt - I haven't checked they are working properly though.
2) It would be good then to make NavBar optional.

Anyway, thanks for the suggestion, I'll certainly consider it. Perhaps a lighter version is not bad idea after all (no external DLLs).

The _"Use old symbols"_ is going away.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for considering that.
Special thanks for removing "Use old symbols". :)

Best regards.

**Comment by pnedev** [comment]
"Old symbols" option removed - change merged to master.
Thanks for the suggestion.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

That's great. Thank you very much.

BR.

**Comment by Yaron10** [comment]
Hello Pavel,

For a later stage. :)

Compare Lite:
No NavBar.
No Git/Svn.
No loader.
Latest commit https://github.com/pnedev/compare-plugin/commit/bf8275f84d89fdd0ac1d5cc9a83233812863a3da is included.

Folders removed:
NavDlg
libgit2
loader

Files removed:
Docking.h
DockingDlgInterface.h
dockingResource.h
dockingResource.h
ScmHelper.h

The built DLL and the changed files are included in the attached file.

[ComparePlugin.zip](https://github.com/pnedev/compare-plugin/files/181120/ComparePlugin.zip)

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Great. That's what a light version of Compare Plugin should look like :)

BR

**Comment by Yaron10** [comment]
Thank you Pavel. I appreciate it.
BR.

**Comment by pnedev** [comment]
Hello Yaron,

I've reworked NavBar to some extent - it will not slow down at all the compare process if disabled.
So I don't see a point now in throwing away functionality from the plugin when it is run-time configurable.
Because of that I don't see a need in Light version of the plugin - I'm closing this issue.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I've reworked NavBar to some extent - it will not slow down at all the compare process if disabled.

That's absolutely great. Thank you so much.

Best regards.
