### ISSUE TITLE
Enhancement request: Ignore Case

### ISSUE THREAD

**Issue by dwelden** [pnedev/compare-plugin#110]
This is the one setting I miss from other editor compares I have used. If Compare could have an Ignore Case setting it would be awesome.

**Comment by pnedev** [comment]
Hello @dwelden ,

Sounds like a good-to-have option, thanks.

BR

**Comment by pnedev** [comment]
Hello,

The new feature is implemented in https://github.com/pnedev/compare-plugin/commit/cb306d2ef13b1d62946cae8dd0ca0a0478915ca2.

Here are the binaries:

- x64:  https://ci.appveyor.com/api/buildjobs/hsq95q9uqslfpij5/artifacts/ComparePlugin.dll
- x86:  https://ci.appveyor.com/api/buildjobs/k9w01nanbar944xj/artifacts/ComparePlugin.dll

BR

**Comment by Yaron10** [comment]
Hello Pavel,

That's a nice and useful addition. 👍 
Thank you for that too.

@dwelden,
Do you know any other developer who would accept and implement a request so quickly? :)
Well, I'm really impressed.

BR

**Comment by dwelden** [comment]
I was very impressed at Pavel's responsiveness, and have been praising his work to my coworkers. Well done, @pnedev.

**Comment by Yaron10** [comment]
@dwelden,
Great.
And thank you for the idea.

BR

**Comment by pnedev** [comment]
Thank you @Yaron10 and @dwelden .

BR

**Comment by nozzo1** [comment]
When will this be incorporated in to the Plugin Manager 'official' downloads? It still has the version without case sensitivity. tks. _Chris.

**Comment by pnedev** [comment]
I'm in the middle of a major plugin rework and upgrade and I cannot tell for sure when I'll be ready due to the lack of free time. I suppose the new release will come in January.
BR

**Comment by JPUC** [comment]
Hello, is this feature anyhow available in Plugin Manager 'official' (as @nozzo1 called it 😉) version?
I wanted to create a new request for this feature, but found that it was asked for before.

**Comment by pnedev** [comment]
Hi,
This feature is available in the new compare plugin called ComparePlus. The old Compare plugin does not have that functionality and is no longer supported by me.
The new plugin can be installed via PluginsAdmin feature in the more recent versions of Notepad++ (I cannot recall what was the first Notepad++ version introducing its integrated plugin management - PluginsAdmin but if you use v8+ should be fine). I would recommend installing the latest Notepad++ (8.5.4 to date) and install all plugins you'd like (including ComparePlus) through PluginsAdmin (you will find it in the Plugins menu list).
BR
