### ISSUE TITLE
Visible diffs disappear on switching between files

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#112]
Hello Pavel,

STR:
Compare ![these files](https://cloud.githubusercontent.com/assets/10229320/23087241/3d3ae4b8-f57b-11e6-80f3-26403c540239.png).
Open a third file.
Activate the compared file in the same view.

Result:
The visible diffs disappear.

NOTE: if it doesn't occur the first time - close the third file, activate the other view and repeat the steps.

I just encountered this issue and was pretty sure it was a very recent regression.
I've tried it with a build from 25/11/16 and had the same result.
I'm surprised we didn't notice that earlier. :)
Could you please have a look?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I was not able to reproduce the issue. What do you mean by "The visible diffs disappear."?
Could you move your other plugins to the _N++_install_dir/plugins/disabled_ folder (to have only the CP plugin remaining) and try again?

I tried that several times with different layouts and positions - I didn't notice anything unusual.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

It's not consistent but certainly reproducible after several times.
I've tested it with a fresh portable NPP 7.3.2. Default settings and plugins.

Please compare the files and don't scroll.
The diffs in the visible lines (16-18, and actually some of the invisible lines) disappear after opening a third file and switching to the compared file.
When you press "First", the caret is positioned at line 22.

![image](https://cloud.githubusercontent.com/assets/10229320/23147125/2fd2902a-f7e5-11e6-9b91-97cc7ebf83ff.png)

Thank you for looking into it. I appreciate that.
BR

**Comment by pnedev** [comment]
Hello Yaron,

OK, I'll keep trying to trigger that, thanks for elaborating.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again. I appreciate it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Another *consistent* issue.

STR:
Open two files in *Single-View mode*.
Compare.
Activate the file in the *main-view*.
Open a third file.
Activate the compared file in the *sub-view* by clicking on a line.

Result:
Some text is selected.

Related to this issue or https://github.com/pnedev/compare-plugin/commit/3332eac30add45a567439a7e729f0adbc9911ea8?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, I know about that issue, I've seen it and it is consistent.
I haven't found a time yet to think of a way to fix it.
Thanks for logging it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Just to let you know that I was also able to reproduce the first issue you reported, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Knowing you, I consider both issues fixed. :)
(That is: when you find the time).

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello @Yaron10 ,

I still need to test if that issue is also present in the latest binary (issue https://github.com/pnedev/compare-plugin/issues/122), I'm pretty sure it is fixed.
If you have the time could you please re-test it also?
Much appreciated, thanks.

BR

**Comment by pnedev** [comment]
Hello again Yaron,

I tested the latest binaries and the issues do not appear. The second is fixed for sure but if the first reappears please open the ticket again. Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

The second issue is fixed. 👍 

The first issue still exists.
Could you please compare the pref files and use configNew.xml as the third file?

[###TEST###.zip](https://github.com/pnedev/compare-plugin/files/1400087/TEST.zip)

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, I see the problem, thanks for the details.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for looking into it. Appreciated as always. 

BR

**Comment by pnedev** [comment]
Hello Yaron,

Can I ask you to test that again with the binary from https://github.com/pnedev/compare-plugin/issues/145 (https://ci.appveyor.com/api/buildjobs/r4a5wsiq3pqu5uia/artifacts/ComparePlugin.dll)?
Sorry to bother you again but I couldn't reproduce the issue (again).
Thank you very much, I appreciate it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

This seems to be a stubborn tough one. :)
Not consistent but I was able to reproduce it within a couple of minutes.

Thanks again.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> This seems to be a stubborn tough one. :)

Are you kidding? ;)

I seriously don't know what to do about that - it is very difficult to reproduce and besides is linked to some Scintilla refresh / re-paint issue (perhaps synchronization one).
I might postpone it for now until the other problems are solved.

Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I might postpone it for now until the other problems are solved.

👍 

The best apps have some "Known Issues".

Thanks again.
BR

**Comment by pnedev** [comment]
Hello Yaron,

It's been a long time, I hope you are doing well :)

This issue is fixed after the latest changes (regarding other functionalities). I've tested it on my side, the problem appears but quickly after that marks are refreshed and everything looks as it should.
You can find x86 test binary here:
https://ci.appveyor.com/api/buildjobs/g220vqwwcgvrvdvg/artifacts/ComparePlugin.dll -

it has some new features (I implemented _'Hide Matches (Show only diffs)'_ option as it seems many users would appreciate such function) and some fixes as well.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you.

> If "Auto re-Compare..." is on and you activate one of the compared files...

You are right I'll reopen the issue.

> I'll open a separate thread for that.

Great :)

BR

**Comment by Yaron10** [comment]
:+1: :)

**Comment by pnedev** [comment]
Hello Yaron,

Here we are once again in our favorite thread :)

I think I found the root cause of the problem. Shortly put - when file is opened while the active document is compared some weird Scintilla notifications are coming that lead to erroneous behavior.
The issue should be fixed in this binary:
https://ci.appveyor.com/api/buildjobs/u11dkipggsjxhlfp/artifacts/ComparePlugin.dll .

Could you please verify that and confirm?
Thanks a ton.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: :+1: :+1: 

Very well done. I appreciate your persistence. :)

Interestingly - trying to reproduce this issue now (with CP before the last one), the diffs disappear in the **old file**. Looking at my older posts here, the diffs used to disappeared in the **new file**.

Anyway, with the last DLL I can not reproduce it at all.

Thanks again for your hard work.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> Interestingly - trying to reproduce this issue now ...

Just FYI the diffs should have disappeared in the SUB VIEW whatever that file might be.
Thank you for re-testing it yet once again and for founding the issue at the first place :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

It's probably not important now but - looking at my screenshots above - I'm quite sure the diffs used to disappeared in the MAIN VIEW.

Thanks again. I appreciate it.
BR

**Comment by pnedev** [comment]
Hello Yaron,

The fix is not view oriented so that's not a problem.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

All's well then. :)
Thanks again for cracking this tough nut.

BR
