### ISSUE TITLE
Horizontal sync-scrolling problem

### ISSUE THREAD

**Issue by pnedev** [pnedev/compare-plugin#114]
STR:

- Turn wrap lines N++ option off.
- Open two files that have long enough lines to not fit into the window (horizontal scroll bar is shown).
- Move one of the files to the other view.
- Horizontally scroll one of the files to its line end for example. Keep the file in the other view horizontally scrolled to the beginning of the line. IOW, have different scroll positions between the views.
- Compare.
- Try scrolling to the beginning in one of the files and try changing lines in one and in the other file.

**Comment by pnedev** [comment]
Fixed with https://github.com/pnedev/compare-plugin/commit/3332eac30add45a567439a7e729f0adbc9911ea8.

**Comment by Yaron10** [comment]
Hello Pavel,

That's a good catch.
Thanks for reporting. :)

And thank you for fixing this issue. 👍 
***
A related issue I noticed a long time ago (I can't remember if we've already discussed it).

STR:
Wrap word - ON.
Compare [these](https://cloud.githubusercontent.com/assets/10229320/23235580/b47a672e-f95e-11e6-8b5e-a48e8eee8abe.png) files (the same files uploaded in https://github.com/pnedev/compare-plugin/issues/113#issuecomment-281834661).
Manually check "Sync Vertical Scrolling".

Result:
With the old CP - the vertical scroll bars would start shaking when you got to wrapped lines.
With your great improvements this behavior seems not to exist anymore (I haven't tested it enough).
But still there's a weird behavior when you scroll to the end of the files.

A possible solution would be disabling the "Sync Scrolling" commands.
But then you'd have to re-enable them on switching to non-compared files.
What do you think? Is it worth it?


BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks.

> A possible solution would be disabling the "Sync Scrolling" commands.
But then you'd have to re-enable them on switching to non-compared files.
What do you think? Is it worth it?

I think it is not necessary. I'm sure there are more N++ commands out there the user might use while in compare mode that will lead to strange behavior but are very far from the typical compare use. Trying to fix all such scenarios is an overkill. Besides, It is highly unlikely that someone will manually check N++ _Sync Vertical Scrolling_ while in compare when the vertical scrolling is already synced.

BR

**Comment by pnedev** [comment]
Hello again Yaron,

I reconsidered the above and implemented sync scroll N++ menu commands disabling while in compare together with some other fixes regarding those menu commands state saving / restoring.
Here is the commit: https://github.com/pnedev/compare-plugin/commit/2e86f0df9f29d68f568a33ed383f93df5eae98a3.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I hardly use those commands.
Adding them to the toolbar for testing, your addition looks good. 👍 
Thank you very much.

A minor issue:
If you open a third file and then activate the compared file *in the other view*, the commands are still enabled.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for testing.

> A minor issue: ...

Are you seeing this through the toolbar?
In the actual N++ menu the commands look disabled. We are having some issues with the toolbar as discussed with Claudia in N++ forum.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Are you seeing this through the toolbar?
> ...

You're right. 👍 

We used to have a similar issue with the "Clear Active Compare" button before you added it to the toolbar via CP.

I'm wondering if this is the *exact* issue as the one discussed on the forum.
We both use the Customize Toolbar plugin. Claudia doesn't.

Without CT, the "Sync" toolbar buttons are *always* enabled.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> Without CT, the "Sync" toolbar buttons are always enabled.

You are right, I have fixed that in https://github.com/pnedev/compare-plugin/commit/c0d4e5d5cbe59ae8398f26193359f430ad812b56.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

It's working like a charm now with or w/o Customize Toolbar.
Thank you very much.

BR
