### ISSUE TITLE
Make "Files Match. Close Files?" dialog optional

### ISSUE THREAD

**Issue by pnedev** [pnedev/compare-plugin#115]
Hello all,

A user sent me recently an e-mail with request to make the "Files match. Close (Y/N)" dialog optional.
He preferred to have instead a simple "Files match. OK" info message box.
Unfortunately I deleted the e-mail by mistake and I don't remember the user name or his contacts but I think it is a reasonable request and I'll implement a setting for that (I personally also prefer a simple info message).

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I often need to compare tens of files. I open a pair at at a time and if they match I want to close them.
I guess this option might be useful for others too.
Thanks for keeping it as an option.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I'm aware of the importance this feature has for you and I will not remove it. I'll simply add a config preference for this, don't worry. Having said that, I'll probably set the default value of the setting to be using the simple "OK" message because it is the more common scenario IMO.
Thanks.

BR

**Comment by pnedev** [comment]
Hello all,

The new setting is implemented in https://github.com/pnedev/compare-plugin/commit/81720c674f725a7c7506d321f8785876e69cbb9e.

Hello Yaron,

I have also changed the Settings dialog layout (as it is continuously growing in height) - commit https://github.com/pnedev/compare-plugin/commit/83a8f3c454fdfd931dbd5b9c37f6846727442c63.

Now that we have the "Prompt to close files on match" user preference I have made the default answer to the question to be 'Yes'.
Do you think it is better to directly close the matched files instead of prompting (in case the user enables the setting)? IOW, is it better to change the user preference to "Close files on match" instead of "Prompt to close files on match"?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I'm aware of the importance this feature has for you and I will not remove it.

Thank you.

> Now that we have the "Prompt to close files on match" user preference I have made the default answer to the question to be 'Yes'.

I was thinking of suggesting that myself. 👍 
Thanks.

> Do you think it is better to directly close the matched files instead of prompting (in case the user enables the setting)? IOW, is it better to change the user preference to "Close files on match" instead of "Prompt to close files on match"?

Oh, no. :)
***
The new Settings layout looks great. 👍 
And I was also thinking of suggesting something similar to the change you've made in the About dialog. Very nice.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I'm glad you like the new changes, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again.

BR
