### ISSUE TITLE
Replace Website in About Dialog

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#12]
In AboutDialog.cpp replace
`_urlNppPlugins.create(::GetDlgItem(_hSelf, IDC_NPP_PLUGINS_URL), _T("http://sourceforge.net/projects/npp-plugins/"));`
with
`_urlNppPlugins.create(::GetDlgItem(_hSelf, IDC_NPP_PLUGINS_URL), _T("https://github.com/pnedev/compare-plugin"));`

What do you think?

**Comment by pnedev** [comment]
I already did that but pointed to the [official GitHub repository](https://github.com/jsleroy/compare-plugin).
I also increased the version to 1.5.6.8.

Thanks for the suggestion!

**Comment by Yaron10** [comment]
Great. Thank you.

BR.
