### ISSUE TITLE
Compact navigation bar graphics artifacts

### ISSUE THREAD

**Issue by jay** [pnedev/compare-plugin#120]
To reproduce download the files [here](https://github.com/jsleroy/compare-plugin/files/812116/Assertion.failed.-.vector.subscript.out.of.range.zip) (it's from a different issue but I'm just reusing file1 and file2 to demonstrate this) and enable compact navigation bar.

In pnedev@51f0a00 I can scroll down to the bottom of the navbar but it doesn't seem to be proportioned the same. file1.c and file2.c have a less total line count (4941 vs 5165) and also if you see the navbar on the left in the area I circled there's basically slack space that is filled with graphics leftovers (I'm really not sure of the right word for this) so the content is never the same. Here's a screenshot:
![capture](https://cloud.githubusercontent.com/assets/965580/23591532/a3a3f28a-01bf-11e7-84e3-0f60f0c27eaf.PNG)

Originally reported at https://github.com/jsleroy/compare-plugin/issues/66#issuecomment-284263881

Pavel says:

> The graphics artifact is a bug. The NavBar portion where the artifact is should be just a gray area (as if the file end has been reached). Try again to reproduce the issue and when you are seeing the graphics artifact just minimize and restore the N++ window again - you'll see what the expected behavior should be in that case. It again doesn't look very nice (the visible diffs are misaligned) but it is the expected behavior with the current implementation (it is not a bug).
> The misalignment is coming from the "Compact Navigation Bar" setting turned on. It tries to compress the diffs preview by skipping preview for similar lines. If the files differ much then the lines skip count is different which leads to different preview lines count between files. Turning off "Compact Navigation Bar" turns off the compression making the line count equal -> aligned NavBar preview.
Please file also a new issue about that in my fork. Thanks.

When I minimize the Notepad++ window if the scrollbar is at the bottom Notepad++ will assert with error vector subscript out of range which is what was reported in jsleroy/compare-plugin#66 so I'll have to reopen that issue.

**Comment by jay** [comment]
Here is another strange artifact (gray vertical bar) that might be corruption. Unfortunately this I couldn't reproduce.
![capture](https://cloud.githubusercontent.com/assets/965580/23640544/7b380f90-02bc-11e7-8188-0ac5f390c694.PNG)

**Comment by pnedev** [comment]
Hello @jay ,

Thanks for filing this issue. I'll have a look at it soon.

BR

**Comment by pnedev** [comment]
Hello @jay ,

The visual artifact you noticed is fixed in **[this x86 binary](https://ci.appveyor.com/api/buildjobs/5k02tpsuqdgr0grf/artifacts/ComparePlugin.dll)**.
I'm aware that currently there are still problems with the NavBar scroll but it is a different issue I'll take care of in the coming days.
With this binary I also don't experience the out-of-bound exception you mentioned ages ago :)

I'm closing this issue now but please write again if you come across another visual artifact or exception.
Thank you.

BR
