### ISSUE TITLE
Changed lines are marked as Added/Removed

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#124]
Hello Pavel,

Could you please compare ![these files](https://cloud.githubusercontent.com/assets/10229320/23837218/83928d98-078d-11e7-831b-47be16cd638c.png) (when the new alignment implementation is ready)?

The lines starting with `user_pref("extensions.bootstrappedAddons"` are marked as Added/Removed in v2.
In v1.5.7 there's also a bug (we've discussed and you've fixed)

![default](https://cloud.githubusercontent.com/assets/10229320/23837175/c7cd2f0a-078c-11e7-979a-3bb353044e37.png)

but the lines are correctly marked as Changed. :)

In concept, I think that Changed lines should be aligned as well.

NOTE:
This is *not* the issue reported in https://github.com/pnedev/compare-plugin/issues/113#issuecomment-285872598 ("Changed lines are marked as Added/Removed (pageInfo files)").

Thank you very much.
And best of luck with the new refactoring.

BR

**Comment by pnedev** [comment]
Thank you for filing the issue @Yaron10 .

BR

**Comment by pnedev** [comment]
Hello Yaron,

I've already fixed that issue in the current 2.1 RC version but thanks for filing it anyway -
as I wrote yesterday, we'll retest all filed cases when the new version is out.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I've already fixed that issue in the current 2.1 RC version

Do you mean you fixed it in one of the very recent commits?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I think the commit that fixes it is https://github.com/pnedev/compare-plugin/commit/cad1ed2767921ee0c1a6e07a81c915416fea4ccd.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the fix. I appreciate it.

I haven't tried the recent commits yet due to the issue reported in https://github.com/pnedev/compare-plugin/issues/113#issuecomment-285872598.

Should I close this issue?

BR

**Comment by pnedev** [comment]
Hello Yaron,

Let's leave the issue open for now.
We'll re-test it when I'm ready with the major refactoring.
Thank you.

BR

**Comment by B-Art** [comment]
The problem occurs when sentences are almost equal. There are at most more spaces or points.

**Comment by pnedev** [comment]
Hello @B-Art ,

Yes, I've noticed that myself recently and it is already fixed in the latest development branch. The fix will be included in the new release of the plugin. Thank you for reporting the problem.
You could eventually provide a sample test files for me to test just to be sure the issue you observe is the same I have encountered and fixed. If that's possible and not a problem for you of course.

BR

**Comment by pnedev** [comment]
Hello all,

This issues are fixed in the latest master branch, please have a look at this issue: https://github.com/pnedev/compare-plugin/issues/122.
If you experience similar problems please write again, thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. 👍 
Thank you very much.

BR
