### ISSUE TITLE
[BUG] Long cancel if comparing long with short file

### ISSUE THREAD

**Issue by CoR--** [pnedev/compare-plugin#126]
First file is 200kb long. Second is 1k long. Both are utf8, windows eol.

Start compare than click on cancel. 
It takes about 60sec or more to cancel on my comp.

**Comment by pnedev** [comment]
Hello @CoR-- ,

This is not a bug but a limitation in the current implementation.
The compare process is comprised of several distinctive steps and your _Cancel_ input is taken between those steps. In your case you've had to wait a single step to complete and apparently that step took 60s or so.
I'll think about a way to make the cancel immediate but I cannot promise anything.

BR

**Comment by CoR--** [comment]
No problem. Thanks for improving this (for me very important ) plugin :)
For now, it's enough that you are aware that there is timing problem.

**Comment by pnedev** [comment]
Hello,

It is now possible to cancel compare in early stage of the process as well (when files are being read) so there will be no more "long cancel" problems.
You can have a look at this issue for more details: https://github.com/pnedev/compare-plugin/issues/122
The fix will be available in the next release of the plugin, thanks.

BR
