### ISSUE TITLE
x64 plugin registration

### ISSUE THREAD

**Issue by chcg** [pnedev/compare-plugin#127]
@pnedev Hi Pavel,

could you have a look here https://github.com/bruderstein/npp-plugins-x64/pull/5#discussion_r111772990

I added the x64 compare plugin as a test and have some comments from Dave, which also regard the config in the existing system at https://npppm.bruderste.in/users/login. Do you wan't to update the config?

Regards,
 Christian

**Comment by pnedev** [comment]
@chcg 
Hi Christian,

Thanks for that, I'll update the config in the x86 list according to Dave's comment.

BR
