### ISSUE TITLE
Compare colorization is not cleared properly

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#13]
1) Open 3 files in N++
2) Trigger 'compare'
3) Go to the view with the two files. Let's call the file that is compared and colorized 'fileA'. Switch to the other file
4) Clear compare results
5) Switch again to 'fileA'. It is still colorized as if being compared.

BR,
Pavel
***
Originally opened in:
https://github.com/jsleroy/compare-plugin/issues/16

**Comment by pnedev** [comment]
Fixed in master branch.

BR

**Comment by Yaron10** [comment]
Great. :+1:
Many thanks.

BR
