### ISSUE TITLE
Loses syntax highlights after clearing file compare results.

### ISSUE THREAD

**Issue by mohammadul** [pnedev/compare-plugin#130]
### Description of the Issue
Syntax Highlights are lost after clearing the file compare results.

### Steps to Reproduce the Issue
1. Open 2 syntax highlight-able files (e.g. C++ files). [Both of them are now C++ syntax highlighted.]
2. Move one of them to the other view.
3. Click Plugins>Compare>Compare (Alt+D).
4. Click Plugins>Compare>Clear Results (Ctrl+Alt+D). [Now both of them lose the highlights.]

### Expected Behavior
Retain the original syntax highlights after Step 4 above. 

### Actual Behavior
Syntax highlights are lost and default colour is set to the text contents.

### Debug Information
None.

**Comment by pnedev** [comment]
Hello @mohammadul ,

I'm unable to reproduce the issue. What version of the plugin are you using?
What is your OS version? Your Notepad++ version?
Thanks.

BR

**Comment by mohammadul** [comment]
Plugin: Compare Plugin 1.5.6
Host application: Notepad++ v7.3.3 (32bit)
OS: Win 7 Ultimate 64bit, Win 10 Home 64bit

Okay, I see. This does not happen in Compare Plugin v2.0.0. I never updated it.

Thanks.
