### ISSUE TITLE
Windows jump randomly

### ISSUE THREAD

**Issue by louis925** [pnedev/compare-plugin#131]
After updating to v2.0.0, the plugin becomes unusable.

The following issues happens randomly.
Issue 1: The compare windows doesn't match at all.
Issue 2: The windows are stuck in random place. When scrolling, it will automatically scroll back to the place it stuck.
Issue 3: When there are more than 2 documents opened in notepad++, the compared windows will jump back and forth between two random points in the documents infinitely.

![loop1](https://user-images.githubusercontent.com/18520676/26862301-f534deb0-4afe-11e7-9e9b-97495244fca2.png)
![loop2](https://user-images.githubusercontent.com/18520676/26862302-f535f03e-4afe-11e7-8c83-d93d3c8dc18f.png)
![loop3](https://user-images.githubusercontent.com/18520676/26862303-f54bd296-4afe-11e7-8945-ec0846841d26.png)

**Comment by pnedev** [comment]
Hello @louis925 ,

I've never seen that issue. What is your OS and Notepad++ version?
Thanks.

BR

**Comment by louis925** [comment]
I am using Windows 7 SP1 Enterprise 64-bit. The Notepad++ version is v6.1.5. Is this the reason?

**Comment by pnedev** [comment]
Yes, most probably the old N++ version is causing the issue.
Update to 7.3.3 or to the latest version (7.4.1 at the moment) and try again.

**Comment by louis925** [comment]
Great! The issue disappears on version 7.4.1. Thanks!
