### ISSUE TITLE
[suggestion] add ignore lines

### ISSUE THREAD

**Issue by gendalv** [pnedev/compare-plugin#132]
like let's say I'm comparing 2 chrome bookmarks files and I only want to see the difference between urls and ignore the lines: "date_added".*, id:.*

**Comment by pnedev** [comment]
I'll consider that, thanks.

**Comment by pnedev** [comment]
This feature request is very similar to this one:
https://github.com/pnedev/compare-plugin/issues/167

I'll close it as redundant and address both requests in the given link.

BR
