### ISSUE TITLE
saving settings

### ISSUE THREAD

**Issue by carlandrea** [pnedev/compare-plugin#137]
Every time I run Notepad++, the plugin's settings are always the default ones.
How can I store my personal settings?

**Comment by pnedev** [comment]
Open the plugin's Settings window, make the desired changes and click the "OK" button.
That should save your settings but I assume you have already done that.
If it doesn't help then try to find where your Notepad++ stores its plugins' config files. It is usually in your user's system folder _-> Application Data -> Notepad++ -> plugins -> config_ but if your Notepad++ is portable version (doesn't require install) or is explicitly configured during install it might look for the plugins config on your flash drive or in Notepad++'s install folder. In that case your user might not have write permissions for the config folder. I'm not sure about that but your settings might even be on your Cloud storage and you might not have Internet access at the moment.
Do you have other plugins installed and if so do they have a problem storing their configs?

**Comment by carlandrea** [comment]
The directory for plugins configuration files is the one you said. But it does not exist in my file system.
In fact, when I try to change the settings of the converter plugin, a pop-up message tell me that that the configuration file that supposes to be in that directory does not exist.

**Comment by pnedev** [comment]
Well, that's a problem with the Notepad++ installation / configuration, not the Compare plugin.
Perhaps Notepad++ is installed for another user but I'm just guessing.
Try looking into your system's _Users_ folder and see if there are more than one. If yes look for _Application Data -> Notepad++_ subfolder in each user's folder. You can create the missing path for your user manually to see if that helps (and probably copy the 'original' user's config data from his / hers config folder if you want to).
I would also suggest to create a thread in Notepad++ [help forum](https://notepad-plus-plus.org/community/category/4/help-wanted) about that issue.

**Comment by carlandrea** [comment]
Ok, thank you.
I checked, but the only Notepad++ folder I could found was under my user folder.
Anyway, I created the path manually and it worked. Notepad created the .ini file and now my settings are persistent

**Comment by pnedev** [comment]
OK, great, I'm closing the ticket then
