### ISSUE TITLE
Temp file is not discarded when comparing to last save

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#14]
STR:
Open two files.
Change anything in one file (do not save).
Compare to last Save.
Clear Results.

Result:
The temp file is not discarded.
***
Originally opened in:
https://github.com/jsleroy/compare-plugin/issues/18

**Comment by pnedev** [comment]
Confirmed.
Just to add that this is valid for SVN and Git compare also.
Thanks.

**Comment by Yaron10** [comment]
Thank you.

**Comment by pnedev** [comment]
Fixed in master.

Just to mention that "SVN Diff" and "GIT Diff" still have some issues, I'm aware of that. I'm working on those, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great job!
Thank you very much.

BR
