### ISSUE TITLE
Diffs are skipped/not visible in some cases

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#141]
Hello Pavel,

STR 1:
Set NPP width to 960 px and its height to 732 px.
Compare [these files](https://github.com/pnedev/compare-plugin/files/1412340/Test.zip).
Press Next.

Result:
The second diff is not visible.
***
STR 2 (probably related):
Set NPP width to 960 px and its height to 732 px.
Compare the same files.
Press Next.
Press Next again (you get the second diff).
Maximize NPP.

Result:
The second diff is not visible.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, that's what I'm talking in https://github.com/pnedev/compare-plugin/issues/142.
Thanks for filing this issue.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again for your work. Highly appreciated.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I'm quite been busy these days and I don't have much time to work on CP but just FYI STR 1 is fixed.
Here is the x86 binary:
https://ci.appveyor.com/api/buildjobs/5wj86c8fin988amv/artifacts/ComparePlugin.dll

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I hope you're doing well.

Thank you for finding the time for fixing the recent issues. Appreciated as always.
We'll patiently be waiting for the final new version. :) 

> just FYI STR 1 is fixed.

Great work. 👍 

Have a nice weekend.

**Comment by Yaron10** [comment]
Hello Pavel,

Another related issue.

STR:
Set NPP to `width="979" height="732"`.
Compare [these files](https://github.com/pnedev/compare-plugin/files/2016669/stylers.zip).
Open the Incremental-Bar and type `rc`.

Result:
The search-match line is not visible.

I'm sure I came across a case where double-clicking the matches in the Find-Results window resulted in the search-match lines not being visible.
I don't remember now the files and the search term. 

**

STR2 (may not be related to this thread but I came across the issue comparing the files from STR1):
Set NPP to `width="979" height="732"`.
Compare.
Activate `stylers.model2.xml`.
Press Last.

Result:
Caret in the wrong line.

**

Another variant of the Maximize/Restore issue.

STR3:
Set NPP to `width="979" height="732"`.
Compare the same files.
Maximize.
Press Last.
Restore.

Result:
The files are scrolled to beyond the last line.

Thank you for looking into it. I do appreciate it.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

I'm not sure the following case is related to this thread.

STR:
Compare pair4 from https://github.com/pnedev/compare-plugin/issues/165#issuecomment-389453635.
Activate 2.txt.
Press Last.

Result:
The caret is in line 15.

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Regarding my previous post.

The caret is *correctly* placed in line 15.
The lack of a blank line confused me. This is due to your decision not to add blanks at the end, correct?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> This is due to your decision not to add blanks at the end, correct?

Yes, correct. This is not a problem.
But all the other issues you reported are relevant and expected at the moment and have the same root cause.
I'll certainly think about a way to circumvent the problem, I don't know yet if it is possible at all (at a reasonable cost I mean).

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

> This is due to your decision not to add blanks at the end, correct?
...
Yes, correct. This is not a problem.

I don't remember the reason for your decision not to add blanks at the end (and probably didn't fully understand it at the time).

Would it be possible to add a *single* blank line in such cases?
The current behavior is slightly confusing IMO.
***
> But all the other issues you reported are relevant and expected at the moment and have the same root cause.
I'll certainly think about a way to circumvent the problem, I don't know yet if it is possible at all (at a reasonable cost I mean).

Many thanks and best of luck.

I know you've invested a lot of time and work in the annotations implementation.
It's indeed a major improvement and I truly appreciate it.
Please don't consider the following lines ungrateful. My intention is good and I'm just sharing my thoughts.

Let's try to analyze the pros and cons of "annotations" vs. the old method.

**Annotations**  

*Pros:*
1) Undo/Redo - available.
2) Performance.

*Cons:*
1) The issues reported here (if you indeed find it hard to fix them; especially the search issues).
2) Inserting a line in many cases (still an issue even with the possible solution we've discussed).
3) The "Smart Highlight" issue is much more common than I thought.

**Old Method**  

*Pros:*
1) The cons mentioned above are irrelevant.

*Cons:*
1) Undo/Redo - unavailable.
2) Performance.

I think the performance is not a major factor.
So it's mainly "Undo/Redo" vs. the other issues.

What would you prefer as a user? What do you think most users would prefer?

Would you consider releasing CP v2.5 including the many improvements you've added since v2 but without annotations? Or would it be a serious "headache"?
(This is not a request but a suggestion or even just a question).

I apologize if these suggestions are inappropriate.
And many thanks again for your excellent work.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll consider adding final blank, thank you.

---------------------------------------------------------

Regarding annotations - yes, they complicated a lot of things but there are so many changes since v2.0, it will be very hard to separate them from the ones related to the new blank approach. It can be done of course (by re-implementing the old blanks) but honestly I like the annotations. Some of the issues we have are due to bugs (or shortcomings) elsewhere and I'm trying work-around them. Some day those might be fixed and not standing in our way anymore. As is the case with the first blank.
I personally would like to see v3 finished. It just takes much more time than I thought because of things that pop-up and because I'm busy with other things.

Thank you for the suggestion anyway that is undoubtedly the easier and more straightforward approach.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I'll consider adding final blank, thank you.

Great. Thank you.

> Regarding annotations -

I can certainly understand you. Thanks.

> I personally would like to see v3 finished. It just takes much more time than I thought because of things that pop-up and because I'm busy with other things.

I had no intention whatsoever to hurry you up. :)
Whenever you find time to work on CP it's appreciated.

BR

**Comment by pnedev** [comment]
Hello Yaron,

How are you, I hope you are doing well :)

I did some changes regarding this issue and tested the fixes here but could you please do some checks on your side as well when you have the time and tell me if you still experience this misbehavior?

Thank you in advance for helping with this, much appreciated as always.

Here are the binaries:
- [**x86**](https://ci.appveyor.com/api/buildjobs/8c4l30f8goufi2eb/artifacts/ComparePlus.dll)
- [**x64**](https://ci.appveyor.com/api/buildjobs/5dgxb59ww6gqsk71/artifacts/ComparePlus.dll)

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

I'm fine, thank you.
I hope you are as well.

I've tested the issues in this thread (not possibly related issues in others).
I've also tested [these RC files](https://github.com/pnedev/compare-plugin/files/4255894/RC.zip) (several issues in a not-maximized window).
As always, excellent work. :+1: 

You probably fixed the following cases before https://github.com/pnedev/compare-plugin/commit/136c97a6773d8642e2f035e533acb41249097570 as I can not reproduce them with a ComparePlus from about a year ago. 

> STR:
Set NPP to width="979" height="732".
Compare these files.
Open the Incremental-Bar and type rc.
>
> Result:
The search-match line is not visible.

>STR2 (may not be related to this thread but I came across the issue comparing the files from STR1):
Set NPP to width="979" height="732".
Compare.
Activate stylers.model2.xml.
Press Last.
>
>Result:
Caret in the wrong line.

All the other issues are fixed with https://github.com/pnedev/compare-plugin/commit/136c97a6773d8642e2f035e533acb41249097570.
Another major improvement. :)

The only issue I still find slightly confusing is your [pair4](https://github.com/pnedev/compare-plugin/files/4255908/pair4.zip) (without the empty lines at the end).
Compare and press Last.
![תמונה](https://user-images.githubusercontent.com/10229320/75347267-15ff6d80-58a9-11ea-94be-72f7823e76f3.png)

Thank you for your hard work. It's truly appreciated.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks a lot for the quick re-testing and the feedback :+1: 

I will look into your last remark about pair4 files lacking the end blanks and consider this issue resolved.

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

> and consider this issue resolved.

I do. :)
:+1: 
Thank you so much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

How are you in these troubled times?
I hope I find you and your loved ones in good health.

I have added the end of file alignments, here are the binaries:
- [**x86**](https://ci.appveyor.com/api/buildjobs/hny222cyfxq3i979/artifacts/ComparePlus.dll)
- [**x64**](https://ci.appveyor.com/api/buildjobs/s118r3ec3nn9doy5/artifacts/ComparePlus.dll)

Take care, stay safe and wishing you all the best in the current situation.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Troubled times indeed. The "dead count" is top news and we all wonder what the next day will bring.

Judging by your lines (and work :) ), I gladly assume you are fine and in good health.
I've read the situation in Bulgaria is relatively good. 
I wish you, your family and your country the very best.

Thank you for your kind wishes. Apart from the inconveniences caused by the partial curfew, I'm OK.
***

And thank you for fixing the last issue here. Great work. Much appreciated. :+1: 

BR

**Comment by pnedev** [comment]
Hello my friend,

And thank you for the kind words.
I wish all the best to you and your loved ones.
Let's hope things will get better soon.
Be safe.

BR

**Comment by Yaron10** [comment]
:+1: :+1:
