### ISSUE TITLE
Vertical scroll is not synchronized after minimizing NPP 

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#145]
Hello Pavel,

STR:
Open NPP.
Minimize and restore.
Open two files and Compare.

Result:
Vertical scroll is not synchronized.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Strange, I cannot reproduce it at the moment.
I'll try on native Windows and write again, thanks.

BR

**Comment by Yaron10** [comment]
Hello again Pavel,

I've just noticed that the problem does not occur when you minimize a maximized window.
Could you please have NPP in a not-maximized window and then minimize?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Got it, thank you 👍 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again. Appreciated.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Could you please try this binary (x86):
https://ci.appveyor.com/api/buildjobs/r4a5wsiq3pqu5uia/artifacts/ComparePlugin.dll ?
The problem seems to be fixed on my side.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Fixed. 👍 
Thank you very much.

Thank you also for the other improvements.
They require some thinking and I'm exhausted now. Tomorrow. :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

Of course, whenever it's convenient for you, thank you.

BR
