### ISSUE TITLE
Wrap mode: words are cut off

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#146]
Hello Pavel,

I think we've had this issue before.
Could you please have a look?

With Compare margin:
![default](https://user-images.githubusercontent.com/10229320/32300042-7b5b56a6-bf60-11e7-8dd5-20f74a78894f.png)

Without Compare margin:
![default](https://user-images.githubusercontent.com/10229320/32300102-b03ffc14-bf60-11e7-9e94-aed5e3409ed5.png)

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

How can I reproduce that?
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Sorry. 
Here are the STR:
Set NPP to `width="960" height="732"`.
Compare the [pref files](https://github.com/pnedev/compare-plugin/files/1424355/TEST.zip) ('prefs.js' in the left view).

![default](https://user-images.githubusercontent.com/10229320/32337708-6cc8bd04-bffb-11e7-80c5-e9f6dceecaaa.png)

Thank you. 
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for reporting,
I'll check that when I find free time.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Could you please re-test that with the latest binary
https://ci.appveyor.com/api/buildjobs/5wj86c8fin988amv/artifacts/ComparePlugin.dll (same as in https://github.com/pnedev/compare-plugin/issues/141) and write back if the issue persists?

Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for looking into it.
The problem still exists on my machine. I understand you can not reproduce it, is that correct?

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for testing it again.
I haven't tried it yet on my side.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Whenever you find the time.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Minimizing and restoring NPP, the lines are displayed properly.
Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, yes, I know, thank you.
The issue is due to some Scintilla window refresh that is not happening.
I have no idea yet what might be blocking that.

P.S. I reproduce the issue BTW, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again and best of luck with that (and everything :) ).

**Comment by pnedev** [comment]
Hello Yaron,

Could you please test the issue again with this x86 binary:
https://ci.appveyor.com/api/buildjobs/f41xid4on53vh9xq/artifacts/ComparePlugin.dll ?

It appears OK on my side.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

👍 

I remembered this weekend that NPP toggled Wrap-mode as a workaround to mirrored words on switching between LTR and RTL.
I wanted to suggest it as a solution to this problem too.

Well... :)

Thank you. I appreciate it.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I didn't know that but it seems there is some issue with the Scintilla view redraw.
Thanks.

BR

**Comment by Yaron10** [comment]
Thanks again Pavel.
