### ISSUE TITLE
Restore One-View mode after Clear Result

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#15]
STR:

1) Start NPP with no files (Session etc.).
2) Open two files (One-View mode; current view is 0).
3) Press "Move to Other View" (we switch to Tow-Views mode; current file is in view 1 (BOTTOM), and the second file is in view 0 (TOP)).
4) Activate the file at top, and press "Move to Other View" (we switch to One-View mode; current view is 1).
5) Open a third file.
6) Compare.
7) Clear Results.

Result:
We're still in Two-Views mode.
***
Originally opened in:
https://github.com/jsleroy/compare-plugin/issues/15

**Comment by pnedev** [comment]
Confirmed, thanks.

BR

**Comment by Yaron10** [comment]
Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

When you get to this part...

Related: https://github.com/pnedev/compare-plugin/commit/bcfcea5246d68ad4ff8491461a6ad573e895f490.

The following code solves this problem.
```
		if (panelsOpened && (closingWin == -1))
		{
			// Yaron 
			// 1) Get and later activate the currently focused file.
			// 2) Make sure we always return to One-View mode.
					
			LRESULT focusedBufferID = SendMessage(nppData._nppHandle, NPPM_GETCURRENTBUFFERID, 0, 0);
			
			::SendMessage(viewOriginallyActiveFile == MAIN_VIEW ? nppData._scintillaSecondHandle : nppData._scintillaMainHandle, SCI_GRABFOCUS, 0, (LPARAM)0);
			skipAutoReset = true;
			SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_GOTO_ANOTHER_VIEW, 0);
			
			bufferActivateOrGetView(focusedBufferID, viewOriginallyActiveFile);
			
			skipAutoReset = false;
		}
```
You still might want to change the general structure of `if (panelsOpened && (closingWin == -1))`. :)
I suggest we keep it open for now.

Thank you.
BR

**Comment by pnedev** [comment]
Fixed in master branch.

BR

**Comment by Yaron10** [comment]
Great. :+1:
Many thanks.

BR
