### ISSUE TITLE
Zoom is changed after closing Compare.

### ISSUE THREAD

**Issue by sky5walk** [pnedev/compare-plugin#150]
[May be similar to this issue.](https://github.com/jsleroy/compare-plugin/issues/82)
My zoom changes to a smaller scale after closing Compare.
Compare Plugin v2.0.0 on Notepad++ v7.5.1.

**Comment by pnedev** [comment]
Thanks for reporting, that will be fixed in the next version.

BR

**Comment by pnedev** [comment]
Hi @sky5walk ,

Can you please try with the latest development binary:
- x86 (32 bit): https://ci.appveyor.com/api/buildjobs/ww62r199k56e92k7/artifacts/ComparePlugin.dll
or
- x64 (64 bit): https://ci.appveyor.com/api/buildjobs/w6no5ibopj70m8xe/artifacts/ComparePlugin.dll
and tell me if you still experience the zoom issue?

Please have in mind that the development build differs significantly from v2.0 and might have other issues (it is still in development).
Thanks and Happy holidays!

BR

**Comment by pnedev** [comment]
Great, I'll close the issue then.

P.S. Renaming the old Compare Plugin dll doesn't work because the dll is loaded anyway. You'll need to remove the old dll completely (simply move it outside the plugins folder) as you have guessed already.

BR
