### ISSUE TITLE
no response bug

### ISSUE THREAD

**Issue by softmgr** [pnedev/compare-plugin#151]
There is no response when comparing two completely different files.

This is the case: 2 completely different XML files, of which 1 filesize are 55KB and the other 1 are 8KB, and they have no response when comparing their contents.

**Comment by pnedev** [comment]
Is it possible to send me the files to see what might be wrong?
The plugin version is 2.0, correct?

BR

**Comment by softmgr** [comment]
[xmlfiles.zip](https://github.com/pnedev/compare-plugin/files/1576086/xmlfiles.zip)
@pnedev

**Comment by pnedev** [comment]
@softmgr ,
Thanks for the report and for the example files.
The compare process takes a lot of time without notifying the user and it appears as if something has crashed. If you wait long enough you'll get the compare results.
This is a common problem related to comparing files with big difference in sizes and very different contents.
I have made a lot of improvements (including related to speed) for the new plugin version that is about to be released soon (in a month or two). The new version will compare your files considerably faster but will take noticeable time anyway.
BR
