### ISSUE TITLE
BUG: default shortcut key conflicts

### ISSUE THREAD

**Issue by softmgr** [pnedev/compare-plugin#153]
Default shortcut keys for "Clear All Compares" conflict with shortcut keys of "Run - Launch in Firefox".
The shortcut keys for the two menu items are all Ctrl+Alt+Shift+X

PS:  "Run - Launch in Firefox" is Notepad++ default command.

**Comment by pnedev** [comment]
@softmgr ,
That has already been reported and is fixed for the next version.
Thanks for filing the issue.
BR
