### ISSUE TITLE
Compare + "Clear Results" changes file

### ISSUE THREAD

**Issue by const-git** [pnedev/compare-plugin#155]
Open files a.txt, b.txt and compare them. Then click "Clear Results". Afterwards file b has changed (compared to the original file content). 
Version of Compare plugin is 1.5.6.3.

[a.txt](https://github.com/pnedev/compare-plugin/files/1772198/a.txt)
[b.txt](https://github.com/pnedev/compare-plugin/files/1772199/b.txt)

**Comment by Yaron10** [comment]
Please try Compare Plugin [v2.0](https://github.com/pnedev/compare-plugin/releases) by Pavel Nedev.

**Comment by pnedev** [comment]
I'm developing and supporting Compare plugin starting from v2.0, I'm not involved in prior versions.
Thanks for reporting anyway.

Thank you for the support @Yaron10.

BR

**Comment by const-git** [comment]
Then why is the outdated version linked on the plugin overview page? 
http://docs.notepad-plus-plus.org/index.php?title=Plugin_Central#C

**Comment by const-git** [comment]
I wanted to report the issue on the bug report page of notepad++ but I was not sure whether it's the right location since it's a plugin and not the main program. So I searched for "compare" and found another issue where somebody said that it's indeed not the right place and he posted a link to this site. 
Now I understand that I'm wrong here too. 
Do you know whether the other plugin is still maintained?
Maybe both plugin versions could be listed as alternatives?

**Comment by pnedev** [comment]
This is just the right place to report issues for versions after 2.0 (including).
As far as I know the prior versions are no longer maintained. That's why I continued the development.

> Maybe both plugin versions could be listed as alternatives?

Maybe it is a good idea after all.
