### ISSUE TITLE
Plugin isn't compatible with Notepad++ 7.5.5 (32bit)

### ISSUE THREAD

**Issue by MrRedHead** [pnedev/compare-plugin#156]
Installed ComparePlugin.dll 
version 2.0.0
date created: 19-12-2016 (european date format)
MD5 checksum: BC2BC5EF1BD504FA1AF10096FE414AE0
SHA1 checksum: 7F160CCA1AF7FC63A358A07FE2BA40B34FE87557

When starting Notepad++ version 7.5.5  error plugin isn't compatible

**Comment by pnedev** [comment]
Are you sure your N++ is 32 bit?
I couldn't reproduce the issue.

**Comment by pnedev** [comment]
@MrRedHead ,
Any update?

**Comment by pnedev** [comment]
Obsolete/irrelevant.
