### ISSUE TITLE
NavBar in RTL layout

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#158]
Hello Pavel,

I happened to open the NavBar with your short `abc` files compared, and noticed the columns should be "flipped" in RTL layout (general RTL - as with the `Set First` icon; NOT Text Direction).

![default](https://user-images.githubusercontent.com/10229320/38739582-fae67722-3f3d-11e8-9c91-fc7c3051b8f2.png)

I hope it doesn't require a lot of extra work.
Whenever you find time in the future. :)

And a cosmetic improvement for the *far* future.
With such short files, the default gray dialog color seems to require some frame.
Something like the black frame in the FunctionList window.

![default](https://user-images.githubusercontent.com/10229320/38740027-3118ec2a-3f3f-11e8-9160-f7cbeb3a689f.png)

Thank you very much.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Great! Thank you very much for the quick fix.
I've clicked and scrolled and it seems to be working like a charm.
(You know I usually don't use the NavBar; it would be good if you could test it yourself after switching to RTL).

> How can I set RTL on my setup?

By switching to a RTL language.
Preferences -> General -> Language -> Hebrew. 

> Is the left view the SUB one?

Indeed. An opposite world. :)
***
> The Navbar has a border at the moment but the color is gray...

I assume you're referring to the border of the panes. That's indeed very nice.
I was suggesting to add another border surrounding the panes (so that you'd have some frame in the blank area).

![default](https://user-images.githubusercontent.com/10229320/38817998-4b41230a-41a2-11e8-8590-61547eaed247.png)

You'd need to move the panes some 2px right and left so that they are not so close to the black frame.
If it's too complex, just forget it. :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

Good, thank you. :+1: 

> Indeed. An opposite world. :)

Hm, that could lead to confusion if we look at the CP Settings.
If we are using RTL language and look at the settings, _Old file position_ would be the opposite of what's stated (if side-by-side views layout is used). I have to think about that.

> I was suggesting to add another border surrounding the panes

I see, I actually prefer it the way it is if you don't mind.
Thanks again.

BR

**Comment by pnedev** [comment]
Hi again Yaron,

One question:
Does the blank line pointing navigation arrow symbol look OK on your side in the RTL case?
On my Linux setup it is wrong at the moment.

Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Hm, that could lead to confusion if we look at the CP Settings.
If we are using RTL language and look at the settings, Old file position would be the opposite of what's stated (if side-by-side views layout is used). 

:+1: 

I thought about that when you first introduced those feature and setting. I may have even mentioned it.
But RTL users are quite used to that right/left swap.

You could add a `*` next to that setting and a comment like "In RTL languages Right and Left will be swapped".
That comment can be placed either bellow the relevant setting or at the end of the settings.

But IMO the appropriate structure for the Settings window is Title and Verb. We've also discussed somewhere the wording.
If you're open to those suggestions, it might be better to leave the RTL comment to a later stage.  

> I was suggesting to add another border surrounding the panes...
...
I see, I actually prefer it the way it is if you don't mind.

Sure, to each his own. :)

> Does the blank line pointing navigation arrow symbol look OK on your side in the RTL case?

Yes, it does. your implementation is perfect.

![default](https://user-images.githubusercontent.com/10229320/38903671-ac9184f8-42ae-11e8-80aa-97cb1758f129.png)

The LTR/RTL arrows are not related to NPP general layout but rather to the text direction.
If you use NPP in English, change the text direction to RTL (View menu) and Compare - do you get the wrong arrows?
***
I've had a busy day.
I'll reply to the Move discussion either tomorrow or on Friday.

Thanks again for your work and patience. Highly appreciated.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll think about the settings more.

> ... do you get the wrong arrows?

Yes, on Linux under Wine. If however on native Windows it is OK then everything should be fine.

Thank you very much.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Perhaps the user doesn't have the notion of main / sub at all.

Unfortunately I agree. 

> Yes, on Linux under Wine. If however on native Windows it is OK then everything should be fine.

It may also be Windows vs. Windows-RTL.
Could you please test it on native Windows when you get a chance?
Does `Fold` change to RTL when you switch text-direction to RTL?

![default](https://user-images.githubusercontent.com/10229320/39058251-f0975de6-44c3-11e8-83b7-8f156793f0bc.png)

I assume you've changed text-direction in *both Views*.

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> Unfortunately I agree.

I'll think of something else, thanks

> Could you please test it on native Windows when you get a chance?

Yes, sure.

> Does Fold change to RTL when you switch text-direction to RTL?

Yes the braces direction changes.

> I assume you've changed text-direction in both Views.

Yes.

Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Regarding Left/Right in Settings:
I think that a comment in the user-guide page would be enough.
Apropos - IMO it would be nice to add a `Help` button to Settings and About. You'd probably not like it.

> Yes, the braces direction changes.

I was referring to the Fold direction which might be a better indication.

I happened to notice there was a superfluous space in `More colors ...` (between "colors" and "...").

Thank you very much.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I tested the RTL blank pointing arrows on my native Windows setup and they are fine. What I've noticed seems to be a Wine issue.

I fixed the left/right inconsistency in **[this](https://ci.appveyor.com/api/buildjobs/w048i8an0iudf5uj/artifacts/ComparePlugin.dll)** x86 binary. The changed `More colors...` is also there.

Thank you,
BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I tested the RTL blank pointing arrows on my native Windows setup and they are fine. What I've noticed seems to be a Wine issue.

Great. Thanks for testing it.

> I fixed the left/right inconsistency

One of the short commits I understand and can genuinely write: I was impressed. :+1: 
And my goodness, you ARE a perfectionist. :)

Thanks again for your work and time.
BR
