### ISSUE TITLE
[Enhancement] A new extra Status Bar for Compare

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#16]
A new extra Status Bar for Compare could be useful.

It should have the following segments:
1) Total diffs.
2) No. of added lines.
3) No. of removed lines.
4) No. of not equal lines.
5) No. of moved lines.

6) Various messages: "No files to compare.", "Can not locate Git." etc.

7) A small Progress Bar.
Pressing "Clear Results" should terminate the process and close the status bar.

---

Originally opened in:
https://github.com/jsleroy/compare-plugin/issues/9

**Comment by pnedev** [comment]
Hello Yaron,

I didn't quite get point 7 - You mean to remove the _Cancel_ button from the progress and to be able to cancel from _Clear Results_? Please explain a bit.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

If you implement a Status Bar, wouldn't it be better to have the Progress Bar as one of its segment?
(Like the progress bar in some browsers indicating page load).
If so, you wouldn't have a Cancel button but rather use the "Stop/Clear Results" button to terminate the process.

Best regards.

**Comment by pnedev** [comment]
Hi Yaron,

Hm, I imagined this a bit different. You would have a normal compare (as it is now) and after the compare finishes a window with compare summary would appear.
How does it sound to you?

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

> and after the compare finishes a window with compare summary would appear.

And you'd have to press OK, correct?
Since you've already got a proper Progress Bar, let's refer only to the other segments.
Wouldn't a bar at the bottom of the window be much better? - Your workflow wouldn't be interrupted, and you could go on checking the diffs and see the extra info as well.

If not a proper toolbar, how about something similar to the Incremental Find Bar?
(I've slightly [modified](http://s27.postimg.org/rd0mywusj/image.png) it and it can look much nicer).

I have no clue as to the amount of work it might require; so it's easier written than done. :)

Thank you.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

I'll think about it later.
I'd like to focus on the stability issues first.

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

Great.
Thank you so much.

BR.

**Comment by pnedev** [comment]
Hello Yaron,

As I wrote in the general discussion thread (https://github.com/pnedev/compare-plugin/issues/108#issuecomment-280672264) this is a rough implementation of the status bar: https://github.com/pnedev/compare-plugin/commit/bf47e92f8eeb98dc1df1fe6231a1b0060d4a0216.

Of course it is not exactly the status that was initially proposed here but we can regularly add useful info if the need arises and if the place is acceptable for such info.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I must write this again: you never cease to surprise me.
Using NPP Status Bar is absolutely great and much better than an extra bar. 👍 
Thank you.

Some comments:
I usually don't use NPP in a maximized window and not all the fields are displayed.
I can think of four possible solutions:
1. A tooltip displaying the entire info on hovering that segment.
2. Increase the bar height and display the info in two rows.
3. Re-dividing the bar and assigning more space to the CP segment. 
4. Double/right-clicking the CP segment would open a popup displaying all the fields.
(Currently, double/right-clicking the CP segment still opens the Language menu).

I think the various fields should be as short as possible.
By changing `Ignore Spaces` to `Detect Spaces` and `Ignore Case` to `Case Sensitive`, the current fields can be as follows:
`Compare (Full)/(Sel)`
`Spaces (Y)/(N)`
`Moves (Y)/(N)`
`Case (Y)/(N)`

(Regardless, I think that "Moves" should appear before "Case" in the menu).

It can be even shorter if you use a different color to indicate whether a setting is checked or not.
"Spaces" in black is ON and in gray is OFF.
This wouldn't work if you accept the tooltip suggestion.

IMO the diff info (listed in the first post here (1-6)) would be more useful than the various settings state (not including Compare (Full)/(Sel)).
What do you think?

Unless you come up with another brilliant idea, one of the four suggestions listed above (tooltip etc.) would have to be implemented anyway.
So the question might be the order (i.e. diff or settings first). 

And if you agree to add the diff info, it would be nice to use different colors for the various fields: Added: (No. in green), Removed: (red) etc.

Thanks again for your work. I was really impressed.

BR

**Comment by Yaron10** [comment]
Hello again,

> Currently the status info update conflicts with the Session Manager plugin (that is when switching between the files Session Manager overwrites the info) but this is an illustration of my idea about the StatusBar.

I've never used that plugin.
Can't you override it too?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I hope you're relaxing and enjoying the weekend.
I'm writing now in case some "Status-Bar thoughts" are popping up and disturbing your serenity.

How about using icons in the Status Bar?
I have no idea as to the implementation, but it would be much clearer and take less valuable space.
* The "Moved" image should only be displayed if "Detect Moves" is checked (a separate field is spared) .
* We can create icons for "Spaces" and "Case" as well.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'm glad you are so enthusiastic and full of ideas about the Status Bar :)

I'm not currently aware of all the possibilities the Windows Status Bar control offers so I don't know which of your ideas is feasible and which is not so I'll need some time to get to know this area better.
Thank you for all the ideas anyway.

> I usually don't use NPP in a maximized window and not all the fields are displayed.

I'll see what can be done.

> I think the various fields should be as short as possible.

Totally agree.

> IMO the diff info (listed in the first post here (1-6)) would be more useful than the various settings state (not including Compare (Full)/(Sel)).
What do you think?

I'm currently planning to first finish the current compare parameters. The diff section will be something for the future. I'm not sure which info from the diff section is actually useful and I certainly wouldn't like to over-populate the status bar with info. Let's discuss that later?
Ah, as for my opinion - I prefer to have the compare params section before the diffs status section actually. This looks more logical to me personally - like a sequence that is - "I did that compare and the results are the following..." - that kind of thoughts stream.

> I've never used that plugin.
Can't you override it too?

I will although the solution is not very elegant. But I don't think I have a choice.

> How about using icons in the Status Bar?

Interesting idea. I'm not sure it is doable though.

> By changing Ignore Spaces to Detect Spaces and Ignore Case to Case Sensitive, the current fields can be as follows:

IMO _Detect Spaces_ is a bit misleading - we are actually not detecting spaces bug including them or excluding them from the compare. Besides all other available software uses the terms _Ignore_ and it is well known. Otherwise I agree - the shorter the info - the better.

> I think that "Moves" should appear before "Case" in the menu

I on the other hand think that it should be after all the "Ignores" options as it is logically different compare switch - it is also affected by the "Ignore" options so it is kind of a latter compare sub-step.

Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I'm glad you are so enthusiastic and full of ideas about the Status Bar :)

I hope you're as enthusiastic as I am. :)

> I'm not currently aware of all the possibilities the Windows Status Bar control offers so I don't know which of your ideas is feasible and which is not so I'll need some time to get to know this area better.

Sure, whenever you find the time. This is certainly not urgent.

As you've suggested, let's discuss the bar fields later.
Thank you.



> How about using icons in the Status Bar?
> ...
> Interesting idea. I'm not sure it is doable though.

![image](https://cloud.githubusercontent.com/assets/10229320/23146530/4caf6808-f7e0-11e6-9869-c73b329e9989.png)

Unfortunately, the app is not open-source. 

> IMO Detect Spaces is a bit misleading - we are actually not detecting spaces but including them or excluding them from the compare. 

That's a nice observation.
Semantically you're right but I meant changing the Spaces setting to positive.
As you understand.

> I on the other hand think that it should be after all the "Ignores" options as it is logically different compare switch - it is also affected by the "Ignore" options so it is kind of a latter compare sub-step.

Again, as you understand. So be it. :)

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> I hope you're as enthusiastic as I am. :)

:+1: 

> Unfortunately, the app is not open-source.

I'm pretty sure it is custom-implemented status bar - it is not the Windows Status Bar control.

> Semantically you're right but I meant changing the Spaces setting to positive.

Got the idea but it would be again a bit strange. The commonly used term for this type of options is _Ignore_ X.

Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> 

> I'm pretty sure it is custom-implemented status bar - it is not the Windows Status Bar control.

Your knowledge and understanding is certainly better than mine.
BTW, MS-Paint also has images in its Status Bar.

> Got the idea but it would be again a bit strange. The commonly used term for this type of options is Ignore X.

I was only referring to your first argument. :)


Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Some thoughts with your permission.
Whenever you get to this issue (I've waited in the past with some ideas and then forgotten them :) ).

The number of diff-lines can be very useful in "real-life" Compares. Here is an example.

I have `Notepad_plus Original.cpp` and `Notepad_plus Modified.cpp`.
When a new NPP version is released, I have three relevant files: the two mentioned above and the new `Notepad_plus.cpp`.
Now I can edit and change either `Notepad_plus Modified.cpp` or the new `Notepad_plus.cpp`.
I often find myself making the decision based on the diff-lines: if `Notepad_plus Original.cpp vs. Notepad_plus Modified.cpp` has 10 diff-lines and `Notepad_plus Original.cpp vs. the new Notepad_plus.cpp` has 50 diff-lines, it should be easier to edit the new `Notepad_plus.cpp`. And vice-versa.

I've suggested in this thread to let the user choose what should be displayed in the status bar: Settings, Diffs (Added, Removed, Changed, Moved and Total) or none.

I now think that even if Settings is selected, it would be useful to display diff-lines.
`Compare: 20 Diff Lines | Setting A  | Setting B`.

If you agree, `Diff Lines` should not be `Total Diffs` but rather the number of not-equal lines.
Meaning: if line 1 is marked `+` in file A and `-` in file B, it should be 1 diff-line.
If line 2 in is marked as Changed in both files, it should also be 1 diff-line.

BTW, I think the format would be nicer and "more correct" without a space between `Compare` and `:`.
`Compare:` instead of `Compare :` (it's indeed a "separator" but the convention is not to add a space before `:`).
***
What do you think about a modifier changing `Highlight on Character Level` and `Align all matching lines` *for this comparison only*?

`Ctrl + Compare` would Highlight on Character Level without changing the setting.
`Shift + Compare` would Align all matching lines without changing the setting.

Thank you very much. I appreciate your patience.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I won't have much time till Monday but just a few quick comments.

I'll think about the status info, no problem.

> BTW, I think the format would be nicer and "more correct" ...

I made it that way to mimic Notepad's style in the status bar (look on the right about the info on file's size, lines count, current position - line, column).
What do you think?

> What do you think about a modifier ...

I assume you would find that handy but is it really worth it? I mean wouldn't it seem unnecessary confusion for the user?
You are not suggesting another commands in the menu, right?

Thank you for the feedback, much appreciated. :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I'll think about the status info, no problem.

:+1: 
I'm glad you agree. Special thanks.

> I made it that way to mimic Notepad's style in the status bar...

I was about to add to my previous post: "I know that NPP adds spaces in the status bar but it doesn't look good IMO".
Well, uniformity with NPP style is a good point.
OTOH, if the window is not maximized (or in smaller monitors) the user may not see the entire info string and every character counts. 
For my personal use I've reorganized the the segments (and removed NPP spaces) in order to see CP info.
Executive derision. :)

> I assume you would find that handy but is it really worth it? I mean wouldn't it seem unnecessary confusion for the user?
You are not suggesting another commands in the menu, right?

No UI changes at all. Just a "Tip" in the user-guide.
Those two settings are unique: due to extra memory consumption and the distraction char-level may cause the settings' default value is correct and your implementation is great.
Still, from a user point of view the presentation might "not be perfect" in some cases.
I therefore suggested a quick way to get a "perfect" result.
If you find it confusing, it's certainly not worth it.

I appreciate your work.
BR

**Comment by Yaron10** [comment]
Hello again Pavel,

`Ctrl + Compare`.
I only had in mind the toolbar buttons and completely forgot the various keyboard shortcuts.

On using `Ctrl+Alt+C`, `if ((GetKeyState(VK_CONTROL) & 0x8000))` would be `true`, correct?
So it's not as simple as I thought. Retracting.

Thank you and enjoy your long weekend.

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for the feedback.
I'll see what I can do about the status bar and the additional info.

> So it's not as simple as I thought

Indeed. It will require some more plugin commands in the menu. That's why I asked if it is "worth it".
I think it is not justified.

Have a nice weekend too.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I'll see what I can do about the status bar and the additional info.

Thanks again. Highly appreciated.

> Indeed. It will require some more plugin commands in the menu. That's why I asked if it is "worth it".
I think it is not justified.

Certainly.
I understood your comment after realizing my mistake.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Please try this build:
https://ci.appveyor.com/api/buildjobs/9mpx9f26k2n2ntgh/artifacts/ComparePlugin.dll .

Try clicking in the Compare status bar portion when compare is ready.
Tell me what you think and if you have other ideas or suggestions.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

You should have seen my reaction after testing this. "Wow!" in a loop. :)
Clever and beautiful. 

Some comments with your permission:

1. The setting I've suggested is not necessary. :+1: 
I still think though the user should have an option to see NPP info.
How about toggling Diffs, Settings and NPP info?
(If you agree, should it still be per Compare? I'm not sure.).

2. I think the Compare type should be displayed in Diffs as well.
If you agree, the format can be: `Compare: 1 Added, 2 Removed`.

3. Diffs order: IMO `Match` should be last and `Changed` before `Moved`.
(In the Setting Dlg `Changed` has more settings and it's OK to place them at the end).

4. Thank you for removing the space before `:`. It looks much better now.
Would you mind trying one space with the new Settings format?
`Compare: Ignore Spaces | Detect Moves` seems more symmetric and clearer IMO. 
(*Obviously this is just my personal view and preference*).

5. Last but not least: Diff Lines can be the most helpful item.
Allow me to quote some lines from my previous post.

> The number of diff-lines can be very useful in "real-life" Compares. Here is an example.
> I have Notepad_plus Original.cpp and Notepad_plus Modified.cpp.
When a new NPP version is released, I have three relevant files: the two mentioned above and the new Notepad_plus.cpp.
Now I can edit and change either Notepad_plus Modified.cpp or the new Notepad_plus.cpp.
I often find myself making the decision based on the diff-lines: if Notepad_plus Original.cpp vs. Notepad_plus Modified.cpp has 10 diff-lines and Notepad_plus Original.cpp vs. the new Notepad_plus.cpp has 50 diff-lines, it should be easier to edit the new Notepad_plus.cpp. And vice-versa.
>
> If you agree, Diff Lines should not be Total Diffs but rather the number of not-equal lines.
Meaning: if line 1 is marked + in file A and - in file B, it should be 1 diff-line.
If line 2 in is marked as Changed in both files, it should also be 1 diff-line.

I hope my point is clear. Would it be complex to implement?
Possible format: 
`Compare: 1 Diff Lines ** 1 Added, 1 Removed`.
`Compare: 1 Diff Lines -- 1 Added, 1 Removed`.
`Compare: 1 Diff Lines. 1 Added, 1 Removed`.
`Compare: 1 Diff Lines | 1 Added, 1 Removed`.

Thank you so much. Highly appreciated.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Could you please retry with this binary:
https://ci.appveyor.com/api/buildjobs/5xp5bq3rjdxl3uuy/artifacts/ComparePlugin.dll ?

Please let me know what you think and if you have other suggestions about the status bar look.
Unfortunately it is not that easy to add possibility to switch to Notepad++'s status doc type but the user can see it anyway by right-clicking on it.

Do you mind changing `Diff Lines` as you call it to `Replaced`? Those are actually replaced lines, 'diff lines' seems a bit unclear to me. Please have in mind that diffs are not properly counted at the moment because they include also lines that are actually moved. I'll fix it tomorrow.

Thank You and
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. I appreciate your hard work and patience.

> Unfortunately it is not that easy to add possibility to switch to Notepad++'s status doc type but the user can see it anyway by right-clicking on it.

:+1: 

I'm afraid that not only the term but the entire `Diff Lines` suggestion was not clear enough. It's my fault and I apologize.

Let's please look at the following screenshot as an example.

![תמונה](https://user-images.githubusercontent.com/10229320/54792586-64db6680-4c47-11e9-925c-9201ead50523.png)

We have **3** different lines in this Compare.

*I'd like to quickly know the number of different lines I'd have to "deal with" in these two compared files.*
So if I have an Added/Removed line in one file and a blank line in the other, I'd still have to "work" on that line.
Let's think about it this way: If it was possible to select lines *across the two views* (hold the left mouse button from left to right across the entire window), I'd select the Removed line 4 and its counterpart blank, the Changed lines 4-5 and the Added line 9 and its counterpart blank.

What do you think?
Would `Replaced` be appropriate for this concept? - I think it can be.

Regarding the format:
The `Replaced` value is the most important one and I think it's not prominent enough (especially in `Compare Selections`).
How about `Compare: * 1 Replaced * 1 Added, 1 Removed`?
(It should be easier to decide on actually seeing it in the status bar).

Thank you for the other changes. :+1: 
I liked the `|` separators in Settings but `,` are nice and clear too.

BR

**Comment by Yaron10** [comment]
Hello again Pavel,

I'd like to try and make the concept clearer.

![תמונה](https://user-images.githubusercontent.com/10229320/54822414-853e0c00-4cad-11e9-9adb-e517e104165e.png)

Can we define the marked sections (red rectangles across the files) as `Segments`?
If positive, we have `3 Diff Segments` in this example.

If you compare a file containing two lines to an empty file - it's `2 Diff Segments`.

Do you think `Diff Segments` is clear? Is `Replaced` better?
If you prefer `Diff Segments`, should it be `Diff Segment(s)` or `1 Diff Segment` and `2 Diff Segments`?
(I think the singular/plural distinction is relevant to `Match` as well. Or perhaps `Matched`?).

If the `Replaced` implementation is complex and/or it might slow the comparison process, `Total Diffs` (i.e Added + Removed + Changed + Moved) would suffice and be a good indication in most cases.

Thank you. Much appreciated.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for elaborating, your concept is clear now :+1: 

I made new commit just before your new comment.
Please try again, here is the binary:
https://ci.appveyor.com/api/buildjobs/f1e9mfrxb3g6741v/artifacts/ComparePlugin.dll .

I tried different separators and think that the implemented variant looks best. Tell me what you think.

Your terminology seems better now that I understand the idea correctly - `Diff Lines` is certainly better than `Replaced`. I also prefer `Lines` instead of `Segments` because the latter sounds like a group of lines.
`Match` is not plural because here I use it as a verb, IOW _"25 lines Match."_
I'll make the necessary changes regarding `Diff Line` vs. `Diff Lines` when I get your feedback so I can fix all remaining issues at once.

BTW, I found a way to show Notepad++'s document type when clicking in status bar as well but do you think it is useful? It seems a bit too much IMO.
Could you please also look at the options status bar when no options are checked? Is it clear enough?

Thank you for the feedback, much appreciated.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

I'm glad we're on the same page. The implementation is perfect. :+1: 
Thank you so much.

I'm particularly glad you find `Diff Lines` clear. :) Thanks.

Should it be `1 Diff Line` and `2 Diff Lines`?
Unlike `Segments`, you're referring to the two line in the two files: we have one place where the *two lines* are different.
What do you think?

> Match is not plural because here I use it as a verb, IOW "25 lines Match."

You're absolutely right.

`2 Diff lines: 2 Added, 2 Removed, 4 Match`.
I find it slightly confusing: with `:` I'd expect the following values to be a summery of `Diff Lines` and this is not the case (Added/Removed do not add up and `Match` does not belong here).

If you agree, you'd probably want to revert the Settings format as well. 

> BTW, I found a way to show Notepad++'s document type when clicking in status bar as well.

:+1: 
As expected. :)

> but do you think it is useful? It seems a bit too much IMO.

For my personal use the current implementation is better.
I just thought CP should have a "Permission" for "hijacking" the segment.
If you don't see it that way, practically - the current behavior is certainly more convenient. 

Thanks again for your excellent work.
BR

**Comment by Yaron10** [comment]
Hello again Pavel,

Could you please compare [these](https://github.com/pnedev/compare-plugin/files/2998133/TEST.zip) files?
(`Detect Moves` and `Ignore Spaces`).

The Diff Lines in the status bar is 82.
Counting it manually, I get 83 (my apologies if I'm wrong).
***
Checking `Ignore Empty Lines`, the Removed count in the status bar is correctly 51 (-3) but the three empty lines in `configOld.xml` (33, 62, 64) are still marked.

Thank you very much. I appreciate it.

Have a nice weekend.

**Comment by pnedev** [comment]
Hello Yaron,

> Should it be 1 Diff Line and 2 Diff Lines?

Yes, exactly :+1: 

> 2 Diff lines: 2 Added, 2 Removed, 4 Match

The `:` is on purpose and you got it right - I interpret it exactly like you. Diff lines are all the changed lines between the files. If there is a section in which several lines are added and other at the same place are removed in the other file it is practically one diff section. This is what I refer to as `replaced`. That's why summing added and replaced lines does not equal to diff - the result might be bigger depending on the type of diff - replacement or insertion / deletion.

I agree about `Match`. Do you have any idea how it will look less confusing?
What do you think about:
`2 Diff lines: 2 Added, 2 Removed; 4 Match` ?

> If you don't see it that way, practically - the current behavior is certainly more convenient.

Great, I'll leave it that way :+1: 

> Could you please compare these files? ....
> ... Checking Ignore Empty Lines ...

All this is expected. I know you might argue that this is confusing but here is why it is as it is:

In the summary the numbers are excluding the ignored lines. Those lines are not compared and not of interest to the user. If the user doesn't care about blank lines diffs then why including them to the status?

On the other hand, if ignored line is located between diff lines the it is marked as they are. This is to be more visually appealing to the user. He/she might not care about the ignored empty lines but if those are inside one block then it doesn't hurt to match the entire block as added or removed or moved instead of leaving "holes" in it (alternating added/removed lines with unmarked empty lines). The latter would also cause problems with navigation.

Have a nice weekend,
BR

**Comment by Yaron10** [comment]
Hello Pavel,

>  Should it be 1 Diff Line and 2 Diff Lines?
...
Yes, exactly 

I actually wrote one line down that it should always be "Lines" in plural.
We have one "horizontal-segment" where the *two lines* are different.
(What can the full sentence possibly be with "1 Diff Line"?).

The same is true with "1 Match" (if it's a verb).
We have one "horizontal-segment" where the *two lines* match.

> The `:` is on purpose...

You're right. :+1: 
The Added/Removed per file result in X Diff Lines per Compare.

`2 Diff lines: 2 Added, 2 Removed. 4 Match` is better IMO.

I think that "No options in active Compare" might be confusing.
I'd revert to "Compare type" only.
***
> The Diff Lines in the status bar is 82.
Counting it manually, I get 83 (my apologies if I'm wrong).

I don't know if you missed it or wanted to further investigate it.
***
> On the other hand, if ignored line is located between diff lines the it is marked as they are...

With your permission, I'll continue this discussion in https://github.com/pnedev/compare-plugin/issues/85.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for all the suggestions. :+1: 
I've made the necessary changes and here is the new binary:
https://ci.appveyor.com/api/buildjobs/t0o1rc251hxnttd6/artifacts/ComparePlugin.dll .

> I actually wrote one line down that it should always be "Lines" in plural.

You are right.

> I don't know if you missed it or wanted to further investigate it.

I somewhat overlooked it, thanks for pointing that out once more. That is a very good catch, well done.
It should be fixed now. You can also try comparing 
**[these](https://github.com/pnedev/compare-plugin/files/3004373/TEST.zip)** files (they are modified versions of your original ones but with reduced number of diff lines to make manual counting easier).

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. Thank you for the quick fix. :+1: 
Counting the diffs with your files is indeed easier. :)

And many thanks again for implementing it. I find it very useful.

The format also looks nice and clear.
***
I've noticed the preference (Diffs/Settings) is no longer per Compare and it's saved after Clear. :+1: 
How about saving it to the INI file as well (no UI changes; just use last selected info)?
I don't know if it's worth it. What do you think?

Another issue closed. Highly appreciated.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> How about saving it to the INI file ...

Another good idea :+1: 

See it in action here:
https://ci.appveyor.com/api/buildjobs/x9tbg05ut2c28vs2/artifacts/ComparePlugin.dll .

Thank you,
BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Another great execution. :)

Thank you very much.
BR
