### ISSUE TITLE
Is there some stable beta?

### ISSUE THREAD

**Issue by informatorius** [pnedev/compare-plugin#160]
When I look in the build history there are many fixes but also work in progress
https://ci.appveyor.com/project/pnedev/compare-plugin/history

Can you tag some of these build as stable beta so I can get some fixes but not alpha work in progress?

**Comment by pnedev** [comment]
Hello @informatorius ,

I cannot tag a stable beta at this moment, sorry.
I'm doing a kind of redesign at the moment but I expect to be ready soon.
The latest alpha is pretty usable btw.

BR
