### ISSUE TITLE
Navbar does not show file position

### ISSUE THREAD

**Issue by informatorius** [pnedev/compare-plugin#163]
In Navbar the currently visible file position is not indicated.
Expected behavoir: A line or other marker is shown in the Navbar according to current visible file position.

**Comment by pnedev** [comment]
@informatorius 
Yes, The NavBar has issues at the moment. This is one of the last areas that needs rework before the new release.

**Comment by pnedev** [comment]
The NavBar file position indicator is now fixed (https://github.com/pnedev/compare-plugin/commit/5a50bbd9820b6a96687fd204bae0aadcab4a9508).

BR
