### ISSUE TITLE
"Smart Highlight" marks after Clear Compare

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#168]
Hello Pavel,

We've discussed this general issue before.
It's much more frequent now and here is a consistent case.

STR:
Compare [these files](https://github.com/pnedev/compare-plugin/files/2051709/TEST.Highlight.zip).
Double click `User` (line 2 in `prefs.js`).
Clear Compare.

Result:

![default](https://user-images.githubusercontent.com/10229320/40690195-881aae62-63ae-11e8-9c01-9428176fcfda.png)

(NPP Preferences -> Highlighting -> Smart Highlighting: disabled/unchecked).

Whenever you find time to look into it and reply.
Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I was not able to reproduce the problem on Wine (under Linux).
I'll try on native Windows tonight perhaps.
Thank you.

BR

**Comment by pnedev** [comment]
Hi again,

I wrote too soon :)
OK, so you are having smart highlighting turned on and you disable it after comparing. Then you clear compare and the screenshot is actually from _prefs Backup.js_. Is that correct?

Interesting side effect but it's actually a Notepad++ issue.
Try this:
1. Enable _Smart Highlighting_ and also the option _Hightlight another view_.
2. Open your files.
3. Move one to other view.
4. Select _user_pref_.
5. Disable _Smart Highlighting_. Note that it will clear the highlighted _user_pref_s only in the active view.
6. Move back the file to the other view (whichever file you move will have the same effect).
7. The uncleared highlights will remain.

Is that the case on your side?
If it is, it is not CP problem.

Thanks once again.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I knew NPP Smart Highlighting was buggy and I was able to reproduce your case.

I wasn't clear enough in my post. 
NPP Preferences -> Highlighting -> Smart Highlighting is always disabled/unchecked and I don't change anything during Compare.

So here are the precise STR:
NPP Preferences -> Highlighting -> Smart Highlighting: disabled/unchecked (all boxes).
Compare the files.
Double click `User` (line 2 in prefs.js).
Clear Compare.

Result:
The marks in the screenshot *in `prefs.js`*.

This does not happen when just moving a file from view to view.

It's certainly an NPP issue at the core but perhaps you might find some fix.
Obviously it's not high-priority.

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I was able to recreate it.
It is obligatory to have _Hightlight another view_ disabled to trigger the issue.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I was able to recreate it.

That's good. :)

> It is obligatory to have Hightlight another view disabled to trigger the issue.

:+1: 

Thank you for looking into it.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4774.
I hope it gets fixed.

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for submitting the PR.
:+1: 

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for finding and fixing the problem.

BR
