### ISSUE TITLE
"NUL" is added when comparing a cloned empty file

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#17]
STR:
1) Clone and Move to Other View a new empty file.
2) Compare.

Result:
"NUL" is added to the files.
***
Originally opened in:
https://github.com/jsleroy/compare-plugin/issues/8

See also:
https://notepad-plus-plus.org/community/topic/11307/plug-in-compare-bug/7

**Comment by pnedev** [comment]
Fixed in master branch:
https://github.com/pnedev/compare-plugin/commit/bf8275f84d89fdd0ac1d5cc9a83233812863a3da
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

A great job.

The crash in [this](https://notepad-plus-plus.org/community/topic/11307/plug-in-compare-bug/7) case doesn't occur, but NUL is added.

Thank you very much.
BR.

**Comment by Yaron10** [comment]
Hello again,

A crash does occur in the following case:

Start NPP.
Write something in New 1.
Open New 2.
Compare.

Thank you.

**Comment by pnedev** [comment]
Hello Yaron,

It should be OK now.
Could you test please?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Solved. Thank you very much.

Could you please try the following steps?

Start NPP.
Open 2 new empty files.
Compare.

Result:
The second file is closed.

BR.

**Comment by Yaron10** [comment]
Hello again,

Your fix is perfect.

> Result:
> The second file is closed.

This happens in previous versions as well.
Should I open a new issue for that?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, I've observed the same behavior but ignored it for now as it is not critical and high priority.
You can open new issue for that just to have this written and remember to fix it in the future.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I'll open a new issue.

BR
