### ISSUE TITLE
Comparing a cloned file

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#173]
Hello Pavel,

STR:
Open one file.
Clone to Other View.
Compare.

Result:
One file.

If you can Compare two empty files, shouldn't the files be compared in this case as well?
I suppose there are some more important issues/tasks; later. :)

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> But isn't comparing two empty files (or to one empty file) pointless too?

It is.

> I remember discussing empty files and I think you wrote that enabling Compare was easier to implement.

I believe you :)
I don't remember anything about that though.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I don't remember anything about that though.

So it should be handled as you understand it now. :)

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

>  Is this what you observe too?

Yes, it is.
But in v2 you do get the Match Dlg.
The question is if it shouldn't be better to notify the user the file(s) are empty and "operation ignored".

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

There was a slight regression in the current CP development stage regarding the empty files comparison - they appeared as different (the compare view is shown but there are no differences).
This is fixed and I have implemented an empty file check - try this x86 binary:
https://ci.appveyor.com/api/buildjobs/j6lb7rkn7927k9e6/artifacts/ComparePlugin.dll .

Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Is checking only the current file intentional?
(If the *other file* is empty, Compare is executed).

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, it is intentional. It's mainly because it is impossible to check the second file before moving it and activating the second view which is tedious and time consuming. I simply decided that it's not worth it.
This approach also gracefully covers the case where you delete all file contents and then execute _Diff since last save_.

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

> It's mainly because it is impossible to check the second file before moving it and activating the second view...

If I understand you correctly, it's impossible to get an inactive doc's length.
How about activating the othr file before switching to double-view mode?

If this is also too much, how about reverting to the old behavior (i.e. compare empty file(s) and display the Match Dlg if both are empty)?

I certainly understand your point but wouldn't the user consider the current implementation slightly strange/inconsistent?

Thank you. I appreciate your patience.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I have reverted to the old behavior. Comparing empty files is completely legit operation so there is no need for special handling.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Thank you very much.

BR
