### ISSUE TITLE
[Bug] Failed to write the configuration file

### ISSUE THREAD

**Issue by marb99** [pnedev/compare-plugin#176]
Failed to write the configuration file

tested with last git-66a6477 32 bit compile

![capturar](https://user-images.githubusercontent.com/7856897/45919206-b027de80-be89-11e8-8d54-69b5b56fc84c.PNG)

**Comment by marb99** [comment]
> 
> 
> @marb99 ,
> Hm, strange,
> Does the _Config_ folder exist?
> Is the folder/drive read-only?
> Could you please check that folder, is there _ComparePlugin.ini_? If yes, please delete the file and try again.
> BR

@pnedev 

this occurs only if Config folder don't exist.

**Comment by pnedev** [comment]
The issue is fixed.
The fix will be available in the next release.

Thank you.
