### ISSUE TITLE
Compare results are cleared when a THIRD file is closed

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#18]
STR:
1) Open THREE files.
2) Compare File1 vs. File2.
3) Close File3.

Result:
Compare results are cleared.
***
Originally opened in:
https://github.com/jsleroy/compare-plugin/issues/7

**Comment by pnedev** [comment]
Cannot reproduce that on latest master branch.
Could you confirm?
Thanks.

**Comment by Yaron10** [comment]
I've just repeated the STR with the latest master branch.
Same result.

Thanks.

**Comment by pnedev** [comment]
Hi Yaron,

Can you test the following 
[test_data.zip](https://github.com/pnedev/compare-plugin/files/180871/test_data.zip)

1) Open all three files.
2) Compare _en-GB.aff_ and _en-GB1.aff_
3) Close _small.txt_

I cannot see the problem on Win7 and on Linux under Wine.
Thanks.

**Comment by Yaron10** [comment]
Hello Pavel,

Please try the following steps:
1) Open three files.
2) Compare File1 vs. File2.
3) Press File3's Close button *without switching to it first*.

Thank you.

**Comment by pnedev** [comment]
Hello Yaron,

I can reproduce it now, thanks.
I'll look into it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Just an idea. I haven't tested it.
Is it possible that the `NPPN_FILEBEFORECLOSE` message is sent before the activated message?

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Solved. Thank you so much.

BR

**Comment by pnedev** [comment]
Thanks.
