### ISSUE TITLE
Settable theme colors.

### ISSUE THREAD

**Issue by AndersBillLinden** [pnedev/compare-plugin#181]
There seems to be no way to change the colors in the split view when comparing files.
If another theme than the default one is used, the output will become unreadable.

The theme colors really needs to be settable.

**Comment by pnedev** [comment]
The colors are settable from the plugin's menu -> Settings -> Color Settings.
If you mean something else please explain.

**Comment by AndersBillLinden** [comment]
Ah! I was looking in the Settings->Style configurator menu!
