### ISSUE TITLE
Show Only Diffs

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#185]
Hello Pavel,

Thank you for this new feature. It's indeed useful and beautifully implemented. :+1: 

1. If the first line matches, it *is* displayed in "Only Diffs" mode.
I suppose it has to do with our old "First Line" discussion.

2. If "Move caret on navigation" is on, the navigation commands do not seem to work as expected.

3. Minor: should this command be placed with "Navigation Bar" in the menu?

I appreciate your work.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> Would disabling Next/Prev (not First/Last) require a lot of work or be a needless bloat?

I don't think it is necessary.

> An interesting behavior: ...

I'll take a look, thanks for reporting.

> Can you think of a way to illustrate "Show Diffs Only"?

I'll think about it.
But it is not really a 'must-have' thing so don't bother if it requires a lot of work or you don't have the time.
I appreciate your help anyway.

> I think the CustomizeToolbar plugin should be mentioned in every possible place for users who might want to remove some icons.

Does it mean that you think the new toolbar icon is useless / not needed ?

Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

>  An interesting behavior: ...
...
I'll take a look, thanks for reporting.

:+1: 
Thank you.
***
I suppose that some users would like to have a toolbar button for "Show Diffs Only". It's certainly not "useless".
Others might want to remove it and they should be aware of the option to do it. :)

Please let me know if you decide to add it and I'll try some other sketches.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> > An interesting behavior: ...
> 
> I'll take a look, thanks for reporting.

This should be fixed here:
https://ci.appveyor.com/api/buildjobs/saj2sgw4rhllsbgp/artifacts/ComparePlugin.dll .

> Please let me know if you decide to add it ...

I believe it will be a good thing, yes.

> Can you think of a way to illustrate "Show Diffs Only"?

What do you think of a simple un-equality sign (scratched '=') ?

Thank you,
BR

**Comment by pnedev** [comment]
Hi Yaron,

Here is a binary with the new toolbar icon implemented (the real icon is just something I found and we might change it for better appearance):
https://ci.appveyor.com/api/buildjobs/qxqw3p603tc82tm2/artifacts/ComparePlugin.dll .

Thanks again for helping :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> This should be fixed here:

Great. :+1: 
Thank you.
***
I think the icon should illustrate both diffs (Show Diffs) and matches (Hide Matches).
We don't have a color representing matches and adding it would only complicate things IMO.

Your "=/" is nice but wouldn't it be confusing as it's to close to the Changed symbol?
(Also, it does not illustrate diffs).

Looking again at my suggested icons - they are not too pretty visually.
How about this?

![default](https://user-images.githubusercontent.com/10229320/50660297-f53ecf00-0fa7-11e9-8e27-1bc1bb94c783.png)

You see the diffs and some parts (matches - for which we don't have a color) are hidden/grayed.
The gray can be darker/lighter to your liking. :)
***
I haven't followed the various Plugin Admin discussion.
Thank you for your contribution. I'm sure it wouldn't have been the same without it.

https://notepad-plus-plus.org/community/topic/16848/notepad-v7-6-2-yellow-vest-gilet-jaune-edition/8

CustomizeToolbar v4.2 changed the dll name to _CustomizeToolbar.

BR

**Comment by pnedev** [comment]
Hello Yaron,

The new icon looks great as it is :+1: 

As I said, I also like the second icon from your first proposal.
Perhaps it is even my favorite because it shows both diffs (the colored lines) and the matches (the empty section of the icon) and the matches are covered with 'disable' sign.
I'll leave it to you to decide which to use.

Thank you very much for providing the icon, I appreciate it.

> CustomizeToolbar v4.2 changed the dll name to _CustomizeToolbar

Strange. Thanks for clarifying.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I've played a bit with the image you preferred.
The "disabled" part is slightly smaller (6x6); it can be placed in the middle and the entire layout is better IMO.

![default](https://user-images.githubusercontent.com/10229320/50694839-9f1f6980-1043-11e9-82af-e9664d346663.png)
![default](https://user-images.githubusercontent.com/10229320/50694862-aba3c200-1043-11e9-8668-17720cf8cb34.png)
![default](https://user-images.githubusercontent.com/10229320/50694876-b65e5700-1043-11e9-99b3-59fc9f301b16.png)

The zip file contains the larger "disabled" as well.
[ShowOnlyDiffs.zip](https://github.com/pnedev/compare-plugin/files/2727449/ShowOnlyDiffs.zip)

Thanks again for this useful feature. :+1: 
BR

**Comment by pnedev** [comment]
Hello Yaron,

Great! Thank you once again :+1: 

Here is the link to the binary for reference (I know you can find it alone but anyway):
https://ci.appveyor.com/api/buildjobs/ml35mdm9v8y08srx/artifacts/ComparePlugin.dll .

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great work.
For my personal use I'll certainly keep it in the toolbar.
Thank you very much.

> Here is the link to the binary for reference (I know you can find it alone but anyway):

Special thanks. :)

Have a nice weekend.
