### ISSUE TITLE
Update manual plugin documentation

### ISSUE THREAD

**Issue by kszydlo** [pnedev/compare-plugin#189]
Hi,
The documentation for adding the Compare plugin manually to a system could use an update. On the 7.6.X builds of Notepad++, you have to add the plugin to C:\programdata\Notepad++\Plugins\ (Plugin Name). The Compare.DLL also NEEDS to be in the aforementioned directory as well. I was having issues updating mine when I found notes on Notepad++ site (linked below).

https://notepad-plus-plus.org/news/notepad-7.6.1-released.html

Other than that, the Plugin works great with Notepad++ release 7.6.2. Thank you for all your hard work.

**Comment by pnedev** [comment]
Good point, thanks :+1:

**Comment by pnedev** [comment]
README info updated.
