### ISSUE TITLE
[Proposed Fix] Opened files appear in the Recently Closed list

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#19]
Hello Pavel,

[This](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1514) NPP bug is quite a problem for Compare users.
See https://github.com/jsleroy/compare-plugin/issues/6.

Some simple changes in three NPP source files seem to solve this annoying issue.

In Notepad_plus.h replace
`void doClose(BufferID, int whichOne, bool doDeleteBackup = false);`
with
`void doClose(BufferID, int whichOne, bool doDeleteBackup = false, bool addToClosedList = true);`

In Notepad_plus.cpp replace
```
//just close the activate document, since thats the one we moved (no search)
doClose(_pEditView->getCurrentBufferID(), currentView());
```
with
```
//just close the activate document, since thats the one we moved (no search)
doClose(_pEditView->getCurrentBufferID(), currentView(), false, false);
```
In NppIO.cpp replace
`void Notepad_plus::doClose(BufferID id, int whichOne, bool doDeleteBackup)`
with
`void Notepad_plus::doClose(BufferID id, int whichOne, bool doDeleteBackup, bool addToClosedList)`

and also replace
`if (PathFileExists(buf->getFullPathName()))`
with
`if (PathFileExists(buf->getFullPathName()) && addToClosedList)`
***
If you don't find a problem in those modifications, could you please open a PR?
There's a chance Don might accept it. :).

Thank you. I appreciate your time.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

I might look into it at a later time but honestly it is not quite interesting to me at the moment.
It is good you have created N++ issue report about that let's hope it will be reviewed soon.

BR
