### ISSUE TITLE
"Access Violation" on comparing an empty file

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#191]
Hello Pavel,

Could you please compare empty vs. non-empty files?
This is a recent regression.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for the good catch :+1: 
It is fixed here:
https://ci.appveyor.com/api/buildjobs/jeatr3cm4nyknpn6/artifacts/ComparePlugin.dll .

BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Thank you for the quick fix.

BR
