### ISSUE TITLE
Exeption

### ISSUE THREAD

**Issue by amspeople** [pnedev/compare-plugin#192]
When scrolling the file after comparison, I get an error as in the screenshot. The last version.
![2019-3-5 23-33-48](https://user-images.githubusercontent.com/5773978/53835859-7feb7c80-3f9f-11e9-893c-472f8dc8bdba.png)

**Comment by pnedev** [comment]
Hello @amspeople ,

Do you have DSpellCheck plugin installed?
It causes such errors occasionally. If you have it, try disabling its automatic checking from the menu or temporarily remove it.

**Comment by amspeople** [comment]
OK. I will write to you about the results.

**Comment by pnedev** [comment]
Closing this issue as invalid (it is caused by DSpellCheck plugin).
Please write again if you believe it is Compare issue, thanks.
