### ISSUE TITLE
Release the plugin under new name

### ISSUE THREAD

**Issue by pnedev** [pnedev/compare-plugin#195]
Change name of the plugin for the new release.
This way both the original Compare plugin will exist together with this new one. Those started to differ a lot (at least a lot code changes exist between the too).
It will reduce confusion, let the users keep old Compare if they prefer so and make maintaining easier.
This will also leave the possibility for the official Compare maintainers to further develop it and make new releases separate from this repo.

I'm planning to name this new plugin ComparePlus.

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Please let me know if and when you'd like me to change or fine-tune the About Dlg.

Hurray ComparePlus!

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for the help, it is highly appreciated.

BR

**Comment by MetaChuh** [comment]
hi @pnedev 

awesome and very coool 👍

i'm here by pure coincidence.
(i had a user question today, where i recommended the compare plugin)

now i saw the vast amount of hours you spend almost every day for the last few months, with so many commits, and i tried out the latest appveyor build ... awesome ❤️

does your raised activity mean, that you are going to release Compare 3.0.0 rc0 aka ComparePlus 1.0 soon, or do you still want to enhance it even more before the first release ?

ps: whatever you plan to do, you have full "meta-helpdesk" support for all your users.
(i always have a smile on my face, everytime i tell a user with a plugin issue the following sentence:
**please go to the notepad++ menu `plugins > open plugins folder` and ...**
you have made our lives so much easier 😃❤️😃)

big thanks and greetings,
metachuh

**Comment by pnedev** [comment]
Hi @MetaChuh ,

Thank you for the kind words.
I'm glad to hear you like the new Compare. :)

@Yaron10 also deserves BIG Thanks - he dedicated a lot of his time to testing my development builds, providing useful feedback and suggestions and discussing how to make the plugin even better :+1: 

Before the release I still have some issues to address and several enhancements to finish but yes, I really want to do it soon as it already took considerably more time than I had imagined.

> ps: whatever you plan to do, you have full "meta-helpdesk" support for all your users.

I appreciate it, thanks :+1: 

> i always have a smile on my face ...

Now I have a smile on my face ;)

BR

**Comment by Yaron10** [comment]
Hello Pavel and @MetaChuh,

Pavel,
Thank you. I have a smile on my face too. :)

BR

**Comment by MetaChuh** [comment]
lol ... now i've got this picture in my head, with all of us permanently grinning.
thank god that github does not have live cams, or we'd probably look like stoners to the rest of the world 😂

ps: awesome, thanks to you too @Yaron10 as you are a very thorough tester, and you somehow have a "correct as usual" status in my brain 👍

**Comment by Yaron10** [comment]
Hello @MetaChuh,

Thank you for your kind words to Pavel and myself.
Pavel indeed deserves every superlative for his amazing work.

You seem to genuinely complimenting and expressing gratefulness.
I value and appreciate that.

And thanks again for your important contribution in the forum.

BR

**Comment by MetaChuh** [comment]
btw community @Yaron10:
i've noticed that you haven't been active there for quite a while.
was there any event that you did not like, or just too much other things to do ?

many thanks and greetings

**Comment by pnedev** [comment]
Hello guys,

Except the About dialog the ComparePlus transition is ready.
Here is the x86 binary:
https://ci.appveyor.com/api/buildjobs/w39gx5v3498s863i/artifacts/ComparePlus.dll

You'll need to adjust your Notepad++ plugin shortcuts, plugin config settings, etc. accordingly, sorry for the inconvenience.

BR

**Comment by MetaChuh** [comment]
ahhhhh, life is so good lately ...

i just hit **<kbd>Open Plugins Folder...</kbd>** 😉❤️ create the `ComparePlus` folder, drop `ComparePlus.dll` into it, and i'm done. 😃
(i don't use git2.dll)

big, big thanks @pnedev 👍

**Comment by Yaron10** [comment]
Hello Pavel and @MetaChuh,

Pavel,
Congratulations! :+1: 

I wasn't sure whether i should ask you this. 
But we've known each other for a long time now. So please don't mind.
`ComparePlus` is very nice. Have you considered `Compare++`?

@MetaChuh,
There was nothing in the forum I didn't like. On the contrary - I like reading your posts. :)
But life is dynamic and I indeed have had less free time recently.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you.

> But we've known each other for a long time now. So please don't mind.

It's my pleasure :) and I don't mind at all :)

> Have you considered Compare++?

Actually I have but I don't want to use other chars than alphabetical. There is no particular reason for that perhaps it is a habit of the old days when there were considerably more restrictions on the files names than today.

Nice suggestion though :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. It's certainly been my pleasure as well.

`ComparePlus` is great. :+1: 
Thanks for the explanation.

BR

**Comment by chcg** [comment]
@pnedev Just let me know if it is time to finally update sqlite to 3.28.0 https://sqlite.org/changes. and libgit2 to https://github.com/libgit2/libgit2/releases/tag/v0.28.1

**Comment by pnedev** [comment]
@chcg ,
I still have unfinished work on ComparePlus.
I'll certainly let you know when I'm ready so you can update the libraries before the actual release. Many thanks for that :+1:

**Comment by pnedev** [comment]
@chcg ,

After several years of pause in the development I'm getting really close to releasing ComparePlus.
Regarding that I made also configuration for ARM64 plugin build but I haven't built libgit2 and sqlite for ARM platform.
Do you by any chance have built those for ARM64?
If yes, could you please do a merge request here adding the ARM64 lib binaries to https://github.com/pnedev/compare-plugin/tree/master/libs folder in `arm64` sub-folder?
You could also upgrade the x86 and x64 libraries if you are still willing to do so of course.
I will understand if you don't, no problem at all.

Many thanks in advance, no matter what you decide!
BR

**Comment by chcg** [comment]
@pnedev Sqlite I just took from the release https://sqlite.org/download.html. There no arm64 binary is released.
For libgit2 I build the version via appveyor that should be possible also for arm64.

**Comment by pnedev** [comment]
@chcg ,

Thank you once again for the libraries update, I appreciate your help.

Yes, I'm working on the dev branch. I haven't transferred the changes to master yet.

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
