### ISSUE TITLE
Difference not correctly identified

### ISSUE THREAD

**Issue by palbr** [pnedev/compare-plugin#197]
I don't know if this is a duplicate to #141 or not. But I have discovered the following issue:

**Steps to reproduce:**
Open the two text files from [197-SampleFiles.zip](https://github.com/pnedev/compare-plugin/files/3062528/197-SampleFiles.zip) and compare them.

**Actual behaviour:**
![WrongDiff](https://user-images.githubusercontent.com/2083705/55859876-4647fb80-5b73-11e9-935f-14268150cc2d.png)

The screenshot shows the result, I can see after clicking "Compare". There is a difference in line 272: "2015..." on the left, "2009..." on the right. But line 272 has no "difference marker". Instead line 273 is marked as difference.

**Expected behaviour:**
I would expect to see a "difference marker" in line 272 and lines 273 to 281 (end of file) to be marked as "identical".

**Aditional Information:**
Issue #141 is talking about specific window sizes of Notepad++. The issue I discovered seems to be independant of the window size. It happens in a maximized window size, the window size in the screenshot and window sized in between.

https://github.com/pnedev/compare-plugin/issues/141#issuecomment-345284149 mentions a fixed DLL, but the download seems to be no longer available, so I can't test whether this issue is a duplicate of #141.

**Programm versions:**
* Notepad++ - v7.5.9 (64Bit)
* Compare Plugin - v.2.0.0

**Comment by palbr** [comment]
Changing positions of the two file ("file2.txt" on the left and "file1.txt" on the right) does give the correct result:
![NoProblemIfFilesSwitched](https://user-images.githubusercontent.com/2083705/55860650-097d0400-5b75-11e9-9ba4-70e0cb365238.PNG)

**Comment by pnedev** [comment]
Hello @palbr ,

Thank you for reporting this issue.

The first problem is fixed in the current development version (different line marked as added).
I'll need to investigate the second one - when you expect both lines to be considered changed (yellow mark).

BR

**Comment by pnedev** [comment]
Hello again @palbr ,

It appears the lines are correctly marked as changed in the latest development version too.

There are a lot of changes between the development version and Compare v2.0.
My plans are to release it soon but I still have some issues to fix. It will be released as a new plugin (under new name). For more info on that please check https://github.com/pnedev/compare-plugin/issues/195.

Thanks once again.

BR

**Comment by palbr** [comment]
Thank you for your quick reply and your great work at the compare plugin! :smiley:
I use it almost daily.

**Comment by palbr** [comment]
Thank you for your quick reply and your great work at the compare plugin! :smiley:
I use it almost daily. I am looking forward to the new plugin!

**Comment by Yaron10** [comment]
@palbr,

You can download Pavel's latest development version in:
https://ci.appveyor.com/project/pnedev/compare-plugin.

**Comment by palbr** [comment]
@Yaron10,

thank you for the link to the build system!

**Comment by Yaron10** [comment]
You're welcome.
