### ISSUE TITLE
[Info] How compile compare-plugin in Visual Studio 2019??

### ISSUE THREAD

**Issue by marb99** [pnedev/compare-plugin#199]
How compile compare-plugin in Visual Studio 2019??

Visual Studio 2019 not Windows XP support for C++

**Comment by pnedev** [comment]
@marb99 ,

I don't have Visual Studio 2019 so I can't know for sure but you can try without XP support (use `PlatformToolset` without `xp`)
`<PlatformToolset>v140_xp</PlatformToolset>` -> `<PlatformToolset>v140</PlatformToolset>`

Please close the issue if you try and verify your query is solved.

BR
