### ISSUE TITLE
Unicode characters compare fails

### ISSUE THREAD

**Issue by pnedev** [pnedev/compare-plugin#20]
Those are marked as if they differ even if they don't.

**Comment by Yaron10** [comment]
Hello Pavel,

A similar/related issue:
Comparing Hebrew files in LTR view, the result is a mess.
Changing to RTL view it works properly.

BR.

**Comment by pnedev** [comment]
The problem I noticed was because the encoding of the compared files differed.
I added a message notifying the user about files encoding mismatch (I only need to return to single view but that will come soon).
If encoding matches Unicode characters are compared just fine.

**Comment by Yaron10** [comment]
Hello Pavel,

Very nice!
Thank you very much.

BR
