### ISSUE TITLE
Compare Selected Lines not on menu

### ISSUE THREAD

**Issue by CaptainParalytic** [pnedev/compare-plugin#202]
According to the help.md file there should be a menu item for "Compare Selected Lines", but this is not appearing.

**Comment by pnedev** [comment]
The help file is made for the development version which is not released yet and is also quite outdated.
Put it shortly, currently you cannot rely on the help file.

For the `Compare Selected Lines` you'll need to wait for the new plugin official release or use a development build (which is OK but has some unfinished / unfixed issues).
