### ISSUE TITLE
[Feature] Live preview of newly added changes during "Compare" mode

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/compare-plugin#204]
Let's suppose I'm comparing two files, activating the two views compare window. Let's also suppose that after the compare I modify one of the two files in one of the two vies, for example by adding text. In the actual implementation of Compare Plugin, new changes won't be displayed in the diff mode until I manually run the "Compare" command.

It would be great to automatically display the new changes when modifying either one of the files (i.e. as you digit/delete/add some text), without having to manually run the "Compare" command every time.

Maybe automatic compare could be added as an option.

**Comment by pnedev** [comment]
@pidgeon777 ,

The automatic re-compare on change is already implemented and will be in the new plugin release (coming soon).
Thanks.

**Comment by pidgeon777** [comment]
Another question, would it be possible to activate the live preview mode as an option?

**Comment by pnedev** [comment]
@pidgeon777 ,

> would it be possible to activate the live preview mode as an option?

Yes, this is how it is implemented.

**Comment by pidgeon777** [comment]
Great!
