### ISSUE TITLE
[Feature] Run Compare plugin outside of Notepad++

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/compare-plugin#205]
It would be nice to add an option/external tool to the Compare Plugin so that it could be possible to call it even outside Notepad++ for comparing two files.

This is what I mean:

https://notepad-plus-plus.org/community/topic/16056/how-to-get-an-external-diff-viewer-with-n-and-the-last-compare-plugin-v2-0-0-0

**Comment by pnedev** [comment]
Hi @pidgeon777 ,

Thanks for the suggestion but external Compare launcher is a separate binary which I'm not planning to support. Compare is a plugin for Notepad and is meant to be used with it. 
BTW, the external Compare launcher was available in v1.5.6.7 (AFAIR) and it used to work with v2.0 but it has a bug in the Notepad++ plugin menu tracing (you can read more [**here**](https://notepad-plus-plus.org/community/topic/17508/compare-plugin-started-from-cmd-comparison-won-t-start-automatically-since-n-7-6-6/17).

BR

**Comment by pidgeon777** [comment]
Thanks for the great explanation. I made a few attempts and I successfully compiled the source available here, which included a hotfix committed in 2018:

https://bitbucket.org/uph0/compare/src/master/

By doing so I obtained a compare.exe executable which perfectly works even with your current Compare plugin. I haven't tested it with Notepad++ v7.7, yet.

Just out of curiosity, do someone knows where to find the sources for the SherloXplorer plugin? It was made by the same author of the Compare plugin loader.

**Comment by pnedev** [comment]
> which perfectly works even with your current Compare plugin ...

It should work as long as the plugin's name is the same and the compare command's name is the same (`Compare` / `Compare`) 

> where to find the sources for the SherloXplorer plugin?

I have no idea.

**Comment by pidgeon777** [comment]
> It should work as long as the plugin's name is the same and the compare command's name is the same (`Compare` / `Compare`)

Is there any chance this could change in your next plugin release?

**Comment by pnedev** [comment]
It will certainly change because I will release new plugin, not a new version of the current one.
The new plugin will be called `ComparePlus` so the launcher needs to be updated to search the Notepad++ menu for `ComparePlus` / `Compare`.

BR

**Comment by pidgeon777** [comment]
Perfect, then I'll modify the source of the launcher to reflect your new plugin changes. Other than that, do you think there could be someone else missing, which I should take into consideration when modifying the source?

Thanks again.

**Comment by pnedev** [comment]
I didn't quite understand your question.
Did you mean
> ... do you think there could be **something** else missing ...

If yes then no, there shouldn't be anything else.

BR

**Comment by pidgeon777** [comment]
I meant exactly that, for some reason I posted *someone* instead than *something*.

**Comment by pnedev** [comment]
@pidgeon777 ,

The new plugin ComparePlus will have command line run possibility like this:

`notepad++ -pluginMessage="compare" old_file.txt new_file.txt`

Min. Notepad++ version required is 8.4.2. The plugin will be released soon (fingers crossed :))

BR
