### ISSUE TITLE
[Enhancement] A revised behaviour of the "Navigate to the next text difference" command

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/compare-plugin#206]
Let's suppose I'm comparing two files in "Compare" mode. When I press the "Tab" key, then the Compare plugin activates the selection on the next text change starting from the cursor position.

This is an annoying behaviour. "Tab" key is usually used for indentation in Notepad++, thus I'm not able to indent text anymore in Compare mode.

My suggestion would be to simply add an option so that a user could decide which keyboard shortcut to associate to the "Select next text difference" and "Select previous text difference" commands in "Compare" mode.

Anyway, selecting all of the text occurrences of the selected diff is a cool and appreciated feature. Please, however, let us decide which key to assign to the diff text navigation commands.

**Comment by pnedev** [comment]
@pidgeon777 ,

Which version of Compare plugin are you talking about?

In the coming version of the plugin `Alt-PageUp` and `Alt-PageDown` will be used as default key combinations for going to the next/previous diff respectively.
You can change the default shortcut from Notepad++ menu:
`Setting->Shortcut Mapper..->Plugin Commands`

**Comment by pidgeon777** [comment]
Hello, my Compare plugin version is v2.0.0.

Here is what I mean:

![l9jvlC6cCx](https://user-images.githubusercontent.com/13739892/58804742-e457bf80-8612-11e9-8acc-893373465f41.gif)

As you can notice, the Tab key leads to a shift of the text selection to the next diff. When the last diff is reached, the Tab key start acting as normal. Please, let a user choose which key to assign to this diff navigation feature.

Actually, I'm already using the following keyboard combinations with success:

![image](https://user-images.githubusercontent.com/13739892/58804833-0f421380-8613-11e9-8d5d-5166cba88b2b.png)

Thus, it would be great to add a custom keyboard shortcut for the text diffs navigation, too. Even better, one for the previous diff and the other for the next diff. In the current Compare plugin version, those are automatically assigned to the Tab and Shift+Tab hotkeys leading to bad behaviour.

**Comment by pnedev** [comment]
Strange, I've never experienced such problem.
I'm pretty sure it has nothing to do with Compare plugin. Actually, Compare plugin doesn't have that functionality.
Could you check your Compare plugin menu and see if there is any command associated with `Tab` key?
Could you also try disabling all your other plugins?
Are you using Notepad++ on Linux under Wine or your operating system is native Windows?

**Comment by pidgeon777** [comment]
I'm using Notepad++ v7.6.3 on Windows 10 Pro x64 and here are all of my Compare plugin settings:

![image](https://user-images.githubusercontent.com/13739892/58808107-a1e5b100-8619-11e9-865f-a3891c9a83f2.png)

![image](https://user-images.githubusercontent.com/13739892/58808115-a5793800-8619-11e9-862b-3e3a5099a00e.png)

![image](https://user-images.githubusercontent.com/13739892/58808121-a8742880-8619-11e9-8886-d84ab82514d7.png)

You were absolutely close, though. The culprit appears to be the DoxyIt plugin:

https://github.com/dail8859/DoxyIt

Look here for more details:

https://github.com/dail8859/DoxyIt/blob/v0.4.3/README.md

_**Jump Locations**
The function and file formats can specify jump locations. These are areas of text that can be jumped to by pressing the Tab key. Using $(...) will use the text within the parenthesis as a default value for the location. Jump locations with the same default text will be edited simultaneously. Pressing the Esc key will remove all marked jump locations._

So, it seems that for whatever reason the diff matches reported by your plugin are caught by the DoxyIt plugin and considered as "jump locations". Thus, when pressing the Tab key, a selection is added to every occurrence of the next text diff, giving the user a chance to navigate through the diffs. To interrupt the process, pressing the Esc key would be enough.

All of this is very cool and funny though, don't you think? Maybe this could be added as a feature to your plugin.

Anyway, this could be the right time to say it:

![image](https://juststickers.in/wp-content/uploads/2017/08/its-not-a-bug-its-a-feature.png)

**Comment by pnedev** [comment]
Hi @pidgeon777 ,

Very good analysis :+1: 

But I wouldn't call it "feature" :)
This hidden plugins interaction shouldn't happen. It is not harmful though so I'm not going to focus on this now (if at all).

I suppose the problem is that both plugins use the same Scintilla (the Notepad++ editing component) indicator number and the bad part is that it is unavoidable. This is because there is no way for a plugin to reserve indicator number for itself and respectively to know that other plugin already uses the same indicator.

BR

**Comment by xylographe** [comment]
Hello Pavel,

Ideally, I suppose, this would be an NPP service: plug-in asks NPP for unused Scintilla indicator number, and NPP reserves it until the plug-in releases it (or until the end of the session). Unfortunately, all plug-ins would have to update to using this service, a bit like advisory flock(2) file locks. :)

Alternatively, one could, perhaps, pick the indicator number randomly? Depending on available range, collisions between plug-ins might be rare.

**Comment by pidgeon777** [comment]
@pnedev 

Understood. If possible please leave this "feature" as is without fixing it, if it is not harmful or if it doesn't represent a bug: navigating/editing the code this way is rather comfortable and helps you to quickly focus on the small text differences among the shown changes: this is why I suggested it to be a feature of your plugin.

**Comment by pnedev** [comment]
Hello @xylographe ,

Long time no "see" :)

You are right of course.
Notepad++, being the "owner" ("holder") of all Scintilla and the plugins should act like a dispatcher for resources (indicator numbers in this case) but unfortunately, currently it does not have such API and functionality.

Picking a random number is interesting idea but will lead to unpredictability and I would rather have a predictable behavior (even if wrong) than uncertainty.

Thanks for writing,
It was nice to "hear" from you :)

Hello @pidgeon777 ,

I won't be doing changes in this regard for now (although I'm not sure if I haven't changed the indicator number for the ComparePlus plugin, which is in development).
Please have in mind that the `TAB` key will take you only to the highlighted parts of the 'changed' lines.

BR

**Comment by pidgeon777** [comment]
@pnedev 

> Please have in mind that the TAB key will take you only to the highlighted parts of the 'changed' lines.

You're referring to the DoxyIt + Compare plugin combo, or only to the Compare plugin case?

**Comment by pnedev** [comment]
@pidgeon777 ,

DoxyIt + Compare plugin

**Comment by pidgeon777** [comment]
This is ok for me. If I wish to stop this behaviour, I would simply need to press the Esc key. But by doing so I would lose the highlighted text selections. But these could again be recovered by simply making another manual compare.
