### ISSUE TITLE
[Feature] Add an option to decide which SVN/Git revision to check against the chosen file

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/compare-plugin#207]
Actually, it is possible to compare a file against the last Git/SVN revision detected. But what if there is more than one revision available?

It would be great something like this: a user activates the "SVN Compare" command, the plugin detects multiple revisions of that file and ask the user which revision to choose for the comparison.

**Comment by pnedev** [comment]
That would be tedious IMO. Those commands are meant to help the user quickly see the changes made against the current HEAD of the repository, nothing more.
There might be many revisions of the file and it is out of the scope of Compare plugin to track them all and provide capability to select among them.

**Comment by pidgeon777** [comment]
I understand, maybe the SVN/Git client could be a better choice in this case.
