### ISSUE TITLE
Change default color settings dependent on selected theme

### ISSUE THREAD

**Issue by RenniePet** [pnedev/compare-plugin#211]
This is related to https://github.com/pnedev/compare-plugin/issues/193

I, too, like to use a theme with light text on a dark background, so I'm always running Notepad++ with the Zenburn theme.

![image](https://user-images.githubusercontent.com/4259011/60856671-39858300-a208-11e9-9544-6b63c576f695.png)

Now I realize that I can fix the problem by changing the color settings, and I have tried to do this with some success. But I have the problem that I'm colorblind, so I struggle to find suitable color settings - I can usually end up with something that allows me to see the changes, but it's aesthetically pretty awful and ugly.

I'm wondering if you could provide two default color settings, one for dark text on a light background, and one for light text on a dark background, and automatically choose the suitable set of colors?

Thank you.

**Comment by pnedev** [comment]
Hello @RenniePet ,

I'll think about that, thanks.

BR

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
