### ISSUE TITLE
Moved lines are not detected correctly

### ISSUE THREAD

**Issue by olma2077** [pnedev/compare-plugin#212]
Similar issue to #162 , but looks like problem is only in Unicode characters this time.
![image](https://user-images.githubusercontent.com/2031502/62263422-1f317480-b457-11e9-8c14-ce09ac5f903b.png)
 [old.txt](https://github.com/pnedev/compare-plugin/files/3454773/old.txt)
[new.txt](https://github.com/pnedev/compare-plugin/files/3454772/new.txt)

**Comment by pnedev** [comment]
Thanks for letting me know.
That is fixed in my current development and will be OK in the next release.

BR

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
