### ISSUE TITLE
[Feature request] Handling INI files

### ISSUE THREAD

**Issue by pl71** [pnedev/compare-plugin#214]
Hi,
Is it possible to handle INI files with this plugin?
It means to check between two INI files diffs in values after first "=" sign.

Presently the whole lines are compared and when differences exceed some threshold (How much?) lines are regarded as new.

From help file:
> Changed: Most of the line is identical in both files. Some changes have been made.

What means "most of"?

**Comment by pnedev** [comment]
Hi,
In the current development version you can set the threshold that defines what portion of the lines needs to match to consider it a "changed" line.
I'm going to release a completely new plugin but I'm not sure when yet as I'm advancing very slowly.
BR

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
