### ISSUE TITLE
compare from command line

### ISSUE THREAD

**Issue by urthmover** [pnedev/compare-plugin#215]
What is the syntax to execute the compare plugin from the command line?

I uncovered that previously this was accomplished using the compare.exe executable that resided within the plugins directory.  Unfortunately, that executable no longer exists for the 64bit compare plugin.  The current plugins directory only has the following:

/Program Files/Notepad++/plugins/ComparePlugin
ComparePlugin
ComparePlugin.dll
/Program Files/Notepad++/plugins/ComparePlugin/ComparePlugin
git2.dll
sqlite3.dll

Please share the syntax for spawning notepad++ and automatically comparing two files from the command line.

Thanks

**Comment by pnedev** [comment]
Hi,

When I started maintaining the plugin myself I had removed the loader as it is not part of the plugin but a simple launcher.

If you need that you can get the loader binary source from here
https://bitbucket.org/uph0/compare/src/master/
and build it yourself.

There are also binaries there but those have an issue and might not work. The source itself is fixed but not pre-built.

The loader relies on compare plugin name and command name so it will work ONLY with Compare plugin and NOT with the new one that I'm about to release - ComparePlus.

BR

**Comment by urthmover** [comment]
Thank you for the quick response.  I’ll grab the source and build the binary myself.  Thanks for your effort and work on this project.
