### ISSUE TITLE
Not workinng in npp.7.7.1

### ISSUE THREAD

**Issue by NeilTohno** [pnedev/compare-plugin#216]
![20190906074156](https://user-images.githubusercontent.com/28284594/64391125-23663880-d07a-11e9-9f3c-bcd9f2616499.jpg)

Oh,  This is wired.
must use Plugin manager.
![20190906080356](https://user-images.githubusercontent.com/28284594/64391951-3b8b8700-d07d-11e9-9671-e8b1b3d3f689.jpg)

**Comment by pnedev** [comment]
What exactly is not working?
Are you talking about Compare v2 plugin?
Can you provide some more details?

**Comment by lmullern** [comment]
Same issue here.
Notepad++ 7.7.1 ; I've installed the Compare plugin manually following the instructions described on https://github.com/pnedev/compare-plugin#installation , restarted Notepad++ but the Compare doesn't display on the Notepad++ Plugin menu.
Please advise.
Thank you,

**Comment by JanHBade** [comment]
fixed today? (tested in 32Bit and 64Bit)
Install over Plugin Manager works!

**Comment by pnedev** [comment]
The instructions in the README are misleading for Compare plugin, sorry guys, my fault.
I'm working on completely new compare plugin named ComparePlus. It is not ready and released yet but the README is modified to address its installation.
I have put a note in the README to describe the difference if you are trying to install the current Compare v2 plugin.

BR
