### ISSUE TITLE
Feature request: Compare selected text with Clipboard contents

### ISSUE THREAD

**Issue by Petewg** [pnedev/compare-plugin#217]
Hi,
few days ago I made a same [request](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6177#issue-498765480) in the  Npp++ repo. 
During the discussion, participants told me to address my request here. So, if you've time, please take a look and see if it would be possible to add the mentioned functionality into Compare-plugin. Thanks!

**Comment by pnedev** [comment]
Hi @Petewg ,
I'm currently working on a new compare plugin named ComparePlus plugin. It has `Compare Selections` feature which can be used for your needs. You'll need to paste the clipboard content to a new document and compare that against your selection.
Unfortunately I cannot tell for sure when I'll release the new plugin.
BR

**Comment by Petewg** [comment]
Hi @pnedev ,
The requested feature is not of high urgency, we can certainly wait for it.
[Don't know whether is better to keep this issue open or close it now, perhaps the only reason to keep it open, is the fact that closing it the moment when it will be finally ready,  the GitHub notifier will inform/remind us about.] 
Thanks in advance.

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
Direct command to compare file/selection against clipboard also implemented.
