### ISSUE TITLE
Change Target Name to ComparePlugin

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#22]
Hello Pavel,

In order to remove the following warning

> 1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1193,5): warning MSB8012: TargetPath(C:\Users\---\Documents\Visual Studio 2013\Projects\ComparePlugin.v1.5.6.8\projects\2013\..\..\Notepad++\plugins\Compare.dll) does not match the Linker's OutputFile property value (C:\Users\---\Documents\Visual Studio 2013\Projects\ComparePlugin.v1.5.6.8\Notepad++\plugins\ComparePlugin.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).

I've changed the Target Name to ComparePlugin.

Project -> Properties...
Configuration Properties
Change Target Name to ComparePlugin.

Good idea?

Thank you.

**Comment by pnedev** [comment]
Hello Yaron,

Yes, that's OK.
Could you create a Pull Request?
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I'm attaching the old and new Compare.vcxproj files. :)
Thank you. I appreciate it.

BR

[Compare.zip](https://github.com/pnedev/compare-plugin/files/181394/Compare.zip)

**Comment by pnedev** [comment]
Hello Yaron,

Your change is merged go master branch.
Thanks.

BR

**Comment by Yaron10** [comment]
Thank you Pavel.
BR.
