### ISSUE TITLE
ComparePlugin.dll not under ComparePlugin directory

### ISSUE THREAD

**Issue by J-Cott** [pnedev/compare-plugin#221]
When you download ComparePlugin_v2.0.0_npp7.7_X64.zip the ComparePlugin.dll is not in the \ComparePlugin directory with git2.dll and sqlite3.dll (it is one level above the directory and if installed into \plugins like this it doesn't load) . No readme file to say that ComparePlugin.dll needs to be moved into C:\Program Files\Notepad++\plugins\ComparePlugin\ for it to load in Notepad++

**Comment by pnedev** [comment]
Please read the project main page (which actually displays this readme:
https://github.com/pnedev/compare-plugin/blob/master/README.md).
