### ISSUE TITLE
Feature:  Option to disable color highlighting

### ISSUE THREAD

**Issue by vinsworldcom** [pnedev/compare-plugin#222]
Please consider adding a feature to not use colors at all for highlighting.  In other words, just disable the highlighting for compares and just use the margin symbols green '+' and red '-" like you already do.

Alternatively, an option to use SC_MARK_FULLRECT instead of SC_MARK_BACKGROUND in the settings may work as well.

I find the highlighting even with transparency set to 100% completely masks the foreground characters since I use Obsidian theme (dark background, light foreground (text)).

Other than that, great plugin, thank you very much.

Cheers.

**Comment by pnedev** [comment]
Hi @vinsworldcom ,

Doesn't changing the differences colors fix your problem?
Having only the margin marks will make the differences difficult to notice IMO.

BR

**Comment by vinsworldcom** [comment]
I changed all colors to match the background of Obsidian theme and made
them 100% transparent.  This workaround seems to work - showing no
highlighting and only the margin marks.  It makes it look much more like a
normal `diff` from the command line.

Cheers.

**Comment by pnedev** [comment]
OK @vinsworldcom ,
I'm closing this request then.

BR

**Comment by vinsworldcom** [comment]
Yes, please do.  Thanks for the tips.  I set all colors to the background of my Theme except the "Change Highlight" which is a very light yellow and set 100% transparency.  This shows the green "+", red "-" and orange "/=" (not equal) in the margin as well as putting a very subtle yellow highlight on the specific changes within each changed line.

Exactly what I was looking for.  Thanks!

**Comment by pnedev** [comment]
You are welcome.
BR
