### ISSUE TITLE
Plugin works only if everything is in one folder!

### ISSUE THREAD

**Issue by oholimoli** [pnedev/compare-plugin#224]
Hello,

I coudn't use the compare plugin because it was lost from the menu every time I restarted Notepad++.

I could fix this behaviour by copying 
- ComparePlugin.dll
- git2.dll
- sqlite3.dll

to the folder:

Notepad++\plugins\ComparePlugin\

In the zip file of the release the ComparePlugin.dll is outside of this folder and importing the dll copys it to Notepad++\plugins\ but when I restarted Notpad was looking for the dll in Notepad++\plugins\ComparePlugin

best reagard

olli

**Comment by pnedev** [comment]
@oholimoli ,

The plugin folder structure should be like that:

`Notepad++\plugins\ComparePlugin\ComparePlugin.dll`
`Notepad++\plugins\ComparePlugin\ComparePlugin\git2.dll`
`Notepad++\plugins\ComparePlugin\ComparePlugin\sqlite3.dll`

BR
