### ISSUE TITLE
"Compare" name may be needed (x86, Windows 10)

### ISSUE THREAD

**Issue by RickPack** [pnedev/compare-plugin#226]
For an x86 (32-bit) installation (Windows 10), all efforts to get the Compare plugin failed (including the use of the menu and naming all folders ComparePlugin) except naming the folders:
...\plugins\Compare\Compare

and renaming the dll to Compare.dll.

**Comment by pnedev** [comment]
That's interesting.
My folders structure have always been like I have written here:
https://github.com/pnedev/compare-plugin/issues/225 .
What is your Notepad++ version?

**Comment by jp-cabrera** [comment]
> For an x86 (32-bit) installation (Windows 10), all efforts to get the Compare plugin failed (including the use of the menu and naming all folders ComparePlugin) except naming the folders:
> ...\plugins\Compare\Compare
> 
> and renaming the dll to Compare.dll.

This is the way that worked for me. Thanks!
