### ISSUE TITLE
Any documentation about visual elements?

### ISSUE THREAD

**Issue by ttodua** [pnedev/compare-plugin#228]
Where we can see some descriptions how it works or what does such element means?
https://i.imgur.com/3NWvYFu.png

**Comment by pnedev** [comment]
@ttodua ,
There is no thorough help yet but you can take a look here: 
https://github.com/pnedev/compare-plugin/blob/master/Help.md

It should give you an overall idea and when you start using the plugin you'll see it's not complex at all.

I won't be able to comment till next week but if you have any specific question after reading the available help I'll answer as soon as I can.

BR
