### ISSUE TITLE
Feature Request: Compare character

### ISSUE THREAD

**Issue by Kai0ken** [pnedev/compare-plugin#232]
Hello, 
thanks for this nice plugin. What I am missing is a characterwise comparison. For now it shows successfully the changed lines and "words", but I wish there would be also an option for "show changed characters", because at the moment it is not easy visible (at least for me) when only one character has changed. 

Example (very short to simplify it: a one-liner): 
First Text: "Hello world!"
Second Text: "Hello worlds!" 

Currently the plugin marks the whole words "world" and "worlds", but what I want is to get only the letter/character "s" highlighted (if first text got compared to text 2, then the "s" should be marked "green (for added)" and if text 2 got compared to text 1, then the "s" should be marked "red (for deleted)". 
This feature would be very nice. Keep up the good work.
Thanks ahead.

**Comment by pnedev** [comment]
Hello @Kai0ken ,

I am very close to releasing the first version of my new ComparePlus plugin that already has this feature + many more.
I hope it will be out in 2 - 4 weeks.

BR

**Comment by Kai0ken** [comment]
Okay, thank you.
