### ISSUE TITLE
Multiple `Diff since last Save` at the same time not work

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [pnedev/compare-plugin#233]
Hi, I see that command `Diff since last Save` doesn't work correct when we use it multiple times. I use `ComparePlus Build time: Mar  2 2020,  15:16:47` version. Step to reproduce:
```
1. Open File1 and change something (without save this file).
2. Open File2 and change something (without save this file).
3. Active File1 and run `Diff since last Save`. << this work correct
4. Active File2 and run `Diff since last Save`. << this not work
``` 
Above step completely destroy `Diff since last Save` command, so If we clean all compares (by invoke `Clear All Compares`) and try invoke `Diff since last Save` once again, we don't get any compare results. To fix this we must run NPP once again.

So, is `Diff since last Save` command should work for single or multiple invoking at the same time, similar to `Ccmpare` command? If only single then should be some lock to invoking another command if first still exist.

**Comment by pnedev** [comment]
Hi @ArkadiuszMichalski,

Thanks for reporting that, I'll have a look and write back.

BR

**Comment by ArkadiuszMichalski** [comment]
Same problem is for `SVN Diff` and `Git Diff`. I can't determinate behaviour for `Compare Selections` because for second compare I always get crash.

Btw, @pnedev I have some fast questions: what additional library we need for ComparePlus? I see that for old plugin we have `git2.dll` and `sqlite3.dll` but for new don't see any infos. I only determined that we need `git2.dll` for Git compare, but what for SVN compare? And `sqlite3.dll` is still needed in new plugin?
Problem is that in https://ci.appveyor.com/project/pnedev/compare-plugin we have only `ComparePlus.dll`, without additional files, and basically we don't known what is still needed.

**Comment by pnedev** [comment]
Hi again @ArkadiuszMichalski ,

I'll check that also, thanks for reporting.

ComparePlus needs the same libraries as Compare for its Git and SVN diff commands.
They are external and are not changed. I haven't packed them with the plugin DLL because I heven't released ComparePlus officially yet.

BR

**Comment by pnedev** [comment]
Hi @ArkadiuszMichalski ,

The issue is fixed, here are the corresponding development binaries:
- x86: https://ci.appveyor.com/api/buildjobs/4mhy1g2p9yb95iu0/artifacts/ComparePlus.dll
- x64: https://ci.appveyor.com/api/buildjobs/dbg846lkl3qo588s/artifacts/ComparePlus.dll

Please tell me if you still experience the problem.
Thanks.

BR

**Comment by ArkadiuszMichalski** [comment]
@pnedev, now looks good, all works fine, thx.
