### ISSUE TITLE
Compare two pairs of files: Views are not synced after Clear Results 

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#24]
Hello Pavel,

When multiple Compares are not disabled.

STR:
Open four files.
Place two in the top view and two in the bottom view.
Compare the two files on the left.
Switch to the other two files.
Compare.
Switch back to the files on the left.
Press Clear Results.
Switch to the other two files.

Result:
The views are not synced.

Related: https://github.com/pnedev/compare-plugin/issues/13

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Let me first re-enable the multiple compares, things will be different after that.
We'll double check then this test case, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I think the broader question is what "Clear Results" should do if there are multiple Compares in the active window.

Clear all Compares? 
If so, the problem is not that the views are not synced but rather that the diff marks are not cleared.
Also, the user might want to clear only *one* Compare.

Clear only the visible Compare?
This means that If the user switches to a non-compared file, "Clear Results" should be disabled.

A setting for the preferred behavior?

Another option is not dealing with it and have some Known-Issues.
After all, it's not a professional Compare application. :)

Thanks again for your great work.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

That's the main question indeed.
For now I thought to implement the 

> Clear only the visible Compare

variant.
We may as well add _Clear all compares_ command.
What's your opinion on this?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> We may as well add Clear all compares command.

That would be the best solution. :+1: 
It seems that implementing this would require *a lot* of work.
I take my hat off even for suggesting it. :)

Thank you.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

That shouldn't be that difficult after the refactoring.
Let's get there and we'll see.
Thanks for the feedback.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> That shouldn't be that difficult after the refactoring.

OK. :)

> Thanks for the feedback.

My pleasure.
I'm impressed and even overwhelmed by the amount of work you've already accomplished.
Thank you!

Best regards.

**Comment by pnedev** [comment]
Fixed in master branch, thanks.

BR

**Comment by Yaron10** [comment]
Great.
Thank you very much.

BR
