### ISSUE TITLE
Focus after closing the NavBar

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#242]
Hello Pavel,

I hope you're doing well. 
I understand you're still not available. Please reply whenever you have time.
(I just don't want to forget the various cases).

There are some focus issues when closing the NavBar. I'd like to compare it to the Function List (with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6f09695c2d12c773e6b50e5bc2bbf2d6b24a227f).

**Toggling the Function List when it's the only tab in the docked window**:
If another element had the focus (e.g. editor, incremental bar), that element keeps the focus.
If the Function List itself had the focus, the editor gets it.

**Toggling the Function List when there are two tabs in the docked window**:
The other tab in the docked window gets the focus.

**Closing the Function List by pressing the docked window's Close button**:
The editor always gets the focus.

The behavior on closing the NavBar is different and in some cases no element gets the focus.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll see what I can do, thanks for reporting that.
I know that there are cases when the focus remains on the NavBar (as far as I recall it is when the scroll bar of the NavBar is used). I couldn't fix that back then but I considered it a small issue.

Stay safe and Best Regards,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

In some cases no element gets the focus after closing the NavBar.
It is a minor issue. We can further discuss it when you're back and after the release of ComparePlus.

Thank you. I appreciate it.

Have a nice weekend.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Could you please try the latest commit in dev branch (https://github.com/pnedev/compare-plugin/commit/bf0ff7f41d727ad7c31110f5fce0d459d1e93966) and check if the issue is fixed?
Thanks a ton!

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Could you please try the following cases?

**1.**
Set focus to the NavBar by clicking on its title bar.
Toggle the NavBar.

**Result:**
No element has focus.

**2.**
Set focus to the NavBar by clicking on its title bar.
Close the NavBar by clicking on its Close button.

**Result:**
The old file gets focus even if the previously focused element was the new file.

Thank you for looking into it. 👍 
I'm not really sure it's worth your time at this stage. :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

I see, OK, could you please try again this dev commit: https://github.com/pnedev/compare-plugin/commit/a5c591608e57e9ad8c8f8b35a48f458c241e1151 ?

Thanks for testing and for the feedback :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

👍 
Perfect!
Thank you very much.

BR
