### ISSUE TITLE
Editor wrongly gets focus when trying to close unsaved compared file(s)

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#245]
Hello Pavel,

Could you please try the following case when you have time?

**STR:**
Compare unsaved files (one unsaved or both).
Press `Close All` or the unsaved file's close button.

**Result:** 
Either the single or multiple `Save` message/dialog is displayed, but the editor has the focus. 

If it doesn't happen the first time, press `Cancel` and try again.

It might be related to https://github.com/pnedev/compare-plugin/issues/241.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll check that, thank you :+1: 

BR

**Comment by Yaron10** [comment]
:+1:

**Comment by pnedev** [comment]
Hi Yaron,

This should be fixed in my latest dev branch.
Thanks for the thorough testing of ComparePlus and for your patience, I appreciate it.
We are slooowly moving towards the first release :)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

👍 
Great!

Another bug where in some cases you can not go to the first diff, is also fixed now.
(I don't remember if we've discussed that case).

I'm glad you're back and going full force. :)
I'll be looking forward to the first release. Best of luck.

Thank you very much. I do appreciate your time and work.

BR.
