### ISSUE TITLE
Align compare tab when using multiline tab mode (continuation)

### ISSUE THREAD

**Issue by blueicehaller** [pnedev/compare-plugin#249]
Hi,
I'm facing the same behavior described here: 
[Align compare tab when using multiline tab mode · Issue #60 · jsleroy/compare-plugin · GitHub](https://github.com/jsleroy/compare-plugin/issues/60)
with Notepad++ v7.8.9 x64 and [Compare v2.0.1 x64](https://github.com/pnedev/compare-plugin/releases/tag/v2.0.1)
when activating "Multi-Line" and uncheck "Vertical".

I thought it was closed/corrected?

I didn't try another Version yet.

Thank you in advance.

Best regards
blueice_haller

**Comment by pnedev** [comment]
Hi @blueicehaller ,

This is a known issue in Compare plugin v2.0.1 and all prior versions.
It is fixed and will be OK in the new plugin I'm currently developing - ComparePlus. It is not released yet. I hope it will be soon but cannot promise anything.

BR

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
