### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by gepruts** [pnedev/compare-plugin#250]
Just want to say thanks and couldn't find any other way.

This is so much better than the original compare plugin. 
Must have been a tremendous lot of work to iron out all the wrinkles and more serious issues. 
I am glad that you did as you gave the world a very useful plug-in. 

So ... Thank you!! :-)

**Comment by Yaron10** [comment]
@gepruts,

Pavel Nedev deserves many praises and thanks for his work.

You might be interested in the ComparePlus development version which is even better.
https://ci.appveyor.com/project/pnedev/compare-plugin.
(Select the platform and then click "Artifacts").

https://github.com/pnedev/compare-plugin#installation.

Best regards.

**Comment by pnedev** [comment]
Thank you @gepruts 
for the kind feedback, I appreciate it. Enjoy! :)

Thank you @Yaron10 ,
hope you are doing well my friend. :)

BR

**Comment by Yaron10** [comment]
Hello my friend Pavel,

I'm fine. Thank you.
I've seen your recent important PRs in NPP. :+1: 

BR
