### ISSUE TITLE
"Show Diffs Only" ignored after editing a file

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#251]
Hello Pavel,

**STR:**
Check "Auto Re-Compare on Change".
Compare.
Check "Show Diffs Only".
Delete a line.

**Result:**
The entire documents are displayed.

Whenever you're back. :)

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll check that, thanks for filing the issue 👍 

BR

**Comment by Yaron10** [comment]
:+1:

**Comment by pnedev** [comment]
Hello Yaron,

I hope you are well.

Are you trying this with the latest dev commit?
I was not able to reproduce the issue, could you verify it again?

Thanks a lot! :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I'm fine. Thank you.
I hope you are well too.

I also hope that your reply is a good sign. :)
(No pressure meant whatsoever).

I've tested it again and, indeed, it does not happen with every (deleted) line.

Could you please compare [these files](https://github.com/pnedev/compare-plugin/files/5527573/TEST.zip)?
Check "Show Diffs Only".
Select and delete line `102` in `prefsNew.js`.

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'm fine as well, thank you.

> I also hope that your reply is a good sign ...

I do, don't worry :)

Thanks a lot for the sample files - I tested with them and could reproduce the issue.
Now I have a way to reliably verify my fix ;)

I'll write again,
Stay safe and
BR

**Comment by pnedev** [comment]
Hello again Yaron,

The latest commit on dev branch should fix the issue - I couldn't reproduce it anymore.
Here is the x86 binary: https://ci.appveyor.com/api/buildjobs/ps8at5cq468230kg/artifacts/ComparePlus.dll

Tell me if it works for you as well.
Thanks again, that was a good catch :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I'm glad you're doing well.
And I'm glad you've found the time to look into it.

It works like a charm. 
Thank you for the quick fix. I appreciate it. :+1: 

BR
