### ISSUE TITLE
ComparePlus 64 bits not detect moves

### ISSUE THREAD

**Issue by moob158** [pnedev/compare-plugin#252]
ComparePlus 64 bits not detect moves and many compiler warnings and  loss of data in VS 2019

it is possible to obtain a ComparePlus **64 bit** that works like the 32 bit version?

32 bit work fine, but not work on Notepad++ 64 bit

there is version Compare 2.0.1 that works, but it lacks many functions of the ComparePlus version like auto-recompare

**Comment by pnedev** [comment]
@moob158 ,

ComparePlus is not officially released yet. Only the development binaries are available but not all of them are stable.
Currently only the x86 builds will work OK with the latest Notepad++ versions.

x64 variant will be available when I make the first official release of the plugin.

P.S. The x64 build compiler warnings are normal (they are not problematic) but there are Notepad++ plugin API changes that are not backward compatible with the x64 plugin builds.

BR
