### ISSUE TITLE
ComparePlus download availability

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/compare-plugin#253]
I see many users talking about the new ComparePlus (beta version I suppose).

Is there a way to test the latest released version?

**Comment by Yaron10** [comment]
@pidgeon777,

https://ci.appveyor.com/project/pnedev/compare-plugin/build/job/ps8at5cq468230kg/artifacts (**x86**).

https://github.com/pnedev/compare-plugin#installation.

**Comment by pidgeon777** [comment]
Great, thank you!

**Comment by pnedev** [comment]
Hello @pidgeon777 ,

ComparePlus is not released but you can try the latest development binary from the link provided by @Yaron10 (thanks for that :+1: )
Currently only x86 version is working with the latest Notepad++ versions.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Best regards. :)
***
Hello @pidgeon777,

You're welcome. We should thank Pavel for his work.

**Comment by pidgeon777** [comment]
> Currently only x86 version is working with the latest Notepad++ versions.

It will be enough, I'll conduct some tests and eventually report any found issue. Thanks again.
