### ISSUE TITLE
Unable to read text when using Dark Theme

### ISSUE THREAD

**Issue by jkiller295** [pnedev/compare-plugin#258]
I'm using this Dark VS theme https://github.com/hellon8/VS2019-Dark-Npp. When I compare 2 files, the text colour turns grey which is barely visible on the black background. 

Is there a setting to change text colour when comparing files?

**Comment by pnedev** [comment]
Hi @jkiller295 ,

Currently there is no way to change the font colour when comparing files.
Only the foreground colouring can be set (the compare diffs marking and highlights).

Sorry for the late reply.
