### ISSUE TITLE
Activate originally active file when returning to One-View mode

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#26]
Hello Pavel,

Implementing https://github.com/pnedev/compare-plugin/commit/bcfcea5246d68ad4ff8491461a6ad573e895f490 (the current-file-at-top part), the active file when returning to One-View mode is not the originally active one but rather the other file. 

It can be annoying and I think it should be addressed.

Unfortunately, and unlike you, I've never tried to learn how the various parts of the code interact (not even in Compare.cpp).
I believe that while re-writing the code you may find a better way to achieve that.
(Use an existing variable or some other way). 
***
Add a global `LRESULT originallyActiveBufferID;`

Replace
`LRESULT bufferID = SendMessage(nppData._nppHandle, NPPM_GETCURRENTBUFFERID, 0, 0);`
with
`LRESULT bufferID = originallyActiveBufferID = SendMessage(nppData._nppHandle, NPPM_GETCURRENTBUFFERID, 0, 0);`

and replace
```
		if (panelsOpened && (closingWin == -1))
		{
			::SendMessage(nppData._scintillaSecondHandle, SCI_GRABFOCUS, 0, (LPARAM)0);
			skipAutoReset = true;
			SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_GOTO_ANOTHER_VIEW, 0);
			skipAutoReset = false;
		}
```
with
```
		if (panelsOpened && (closingWin == -1))
		{
			::SendMessage(nppData._scintillaSecondHandle, SCI_GRABFOCUS, 0, (LPARAM)0);
			skipAutoReset = true;
			SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_GOTO_ANOTHER_VIEW, 0);
			
			// Yaron - We could use "::SendMessage(nppData._scintillaMainHandle, SCI_GRABFOCUS, 0, (LPARAM)0);"
			// and thus have the original file activated (and avoid the following activateBufferID); but I think it's better to have 
			// currentView == 0 when switching to Onw-View mode (currentView == 0 is the start/normal state; 
			// if multiple files are open, most would remain in the top view when comparing).
			activateBufferID(originallyActiveBufferID, 0);
			skipAutoReset = false;
		} 
```
Thank you very much. I really appreciate your work.

Best regards.

**Comment by Yaron10** [comment]
Hello again,

Actually it would make more sense to activate the currently focused file.
So it should be good to implement this regardless of https://github.com/pnedev/compare-plugin/commit/bcfcea5246d68ad4ff8491461a6ad573e895f490.
What do you think?

The only change then is replacing 
```
        if (panelsOpened && (closingWin == -1))
        {
            ::SendMessage(nppData._scintillaSecondHandle, SCI_GRABFOCUS, 0, (LPARAM)0);
            skipAutoReset = true;
            SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_GOTO_ANOTHER_VIEW, 0);
            skipAutoReset = false;
        }
```
with
```
		if (panelsOpened && (closingWin == -1))
		{
			// Yaron - Get and activate the currently focused file.
			// It's still good to make sure the bottom view gets the focus so that "currentView == 0" when returning to Onw-View mode
			// ("currentView == 0" is the start/normal state; if multiple files are open, most would remain in the top view when comparing).
		
			LRESULT focusedBufferID = SendMessage(nppData._nppHandle, NPPM_GETCURRENTBUFFERID, 0, 0);
			
			::SendMessage(nppData._scintillaSecondHandle, SCI_GRABFOCUS, 0, (LPARAM)0);
			skipAutoReset = true;
			SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_GOTO_ANOTHER_VIEW, 0);
			
			activateBufferID(focusedBufferID, 0);
			
			skipAutoReset = false;
		}
```
***
I've just seen your last commits in the dev branch.
Wow! I don't understand anything in the major one. :)

Thank you.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

I don't have time to review that at the moment.
I'll address this soon.
Thanks for your suggestions.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you.
I open an issue when I think or encounter one. 
I know you're currently working on other parts of the code. :)

BR

**Comment by pnedev** [comment]
This is fixed in the master branch, thanks.

BR

**Comment by Yaron10** [comment]
Great. :+1:
Many thanks.

BR
