### ISSUE TITLE
text color affected by line's background color

### ISSUE THREAD

**Issue by michal037** [pnedev/compare-plugin#266]
Plugin version: 2.0.1
Notepad++ version: 8.1.2

I noticed that the color of the text depends on the background color of the line. I recorded a short GIF to show what it looks like. In my opinion, this reduces the clarity of the text when several colors from different backgrounds overlap. I attach my theme and plugin settings in the attachments.

![text_color](https://user-images.githubusercontent.com/7441419/128262195-bc98b1bf-7635-409b-8fe7-9912125526ea.gif)

[Dracula.xml](https://github.com/pnedev/compare-plugin/files/6934712/Dracula.txt)
[ComparePlugin.ini](https://github.com/pnedev/compare-plugin/files/6934714/ComparePlugin.txt)

**Comment by pnedev** [comment]
I'll take a look at it when I find the time, thanks for the feedback.

BR

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
