### ISSUE TITLE
Feature Request: Can you show only differences in compare?

### ISSUE THREAD

**Issue by hansstangl1** [pnedev/compare-plugin#272]
Can you show only differences in compare?
In SAP you can choose: 
Whole text (complete text, as it is currently)
Short form (2 lines before and 2 lines after difference)
Only differences

Some options:
Ignore Case (less differences)
Ignore empty lines (less differences)

You have got functionality already, because on the navigation panel you show the differences.
By that you can check the differences very fast. 
br Hans hans.stangl@gmx.at

**Comment by pnedev** [comment]
I'll have that in mind, thank for your suggestion.
Most of these features are already implemented in a new compare plugin I'm about to release (soon I hope).

**Comment by hansstangl1** [comment]
Hi Pavel.

I have read about your new project.

But you are stuck since 2019 as I have seen.

Hopefully you can release a prototyp soon or improve the old version, which is very good, too.

 

It´s no problem to have two branches :-)

 

br

Hans
 

"Es gibt Dinge, die den meisten Menschen unglaublich erscheinen, die nicht Mathematik studiert haben."

Archimedes

 
 

Gesendet: Mittwoch, 08. Dezember 2021 um 15:52 Uhr
Von: "Pavel Nedev" ***@***.***>
An: "pnedev/compare-plugin" ***@***.***>
Cc: "hansstangl1" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pnedev/compare-plugin] Feature Request: Can you show only differences in compare? (Issue #272)


 

I'll have that in mind, thank for your suggestion.
Most of these features are already implemented in a new compare plugin I'm about to release (soon I hope).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pnedev** [comment]
Hi again,
I will no longer be working on the old version as I consider it obsolete now.
Yes, I haven't been working on the new plugin since maybe a year but it is almost finished anyway and I guess I'll dedicate some time to do that in the coming month.
BR

**Comment by hansstangl1** [comment]
Good news. In Github I had read 29%.

In case u finish you can send info to me, I will install and inform you in case of any errors.

 

br

Hans

Austria

 
 

Gesendet: Mittwoch, 08. Dezember 2021 um 17:46 Uhr
Von: "Pavel Nedev" ***@***.***>
An: "pnedev/compare-plugin" ***@***.***>
Cc: "hansstangl1" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pnedev/compare-plugin] Feature Request: Can you show only differences in compare? (Issue #272)


 

Hi again,
I will no longer be working on the old version as I consider it obsolete now.
Yes, I haven't been working on the new plugin since maybe a year but it is almost finished anyway and I guess I'll dedicate some time to do that in the coming month.
BR

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pidgeon777** [comment]
> Hi again,
I will no longer be working on the old version as I consider it obsolete now.
Yes, I haven't been working on the new plugin since maybe a year but it is almost finished anyway and I guess I'll dedicate some time to do that in the coming month.
BR

Great news, we're anxiously waiting for the new version 👍.

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
