### ISSUE TITLE
comparing two files in NP++ dark mode makes differences unreadable

### ISSUE THREAD

**Issue by shocked-gamer** [pnedev/compare-plugin#273]
### Description of the Issue

when dark mode is enabled in the app, the compare plugin still uses the default colors for the white mode. this makes reading the differences very hard to read.

### Steps to Reproduce the Issue

1. go to settings, preferences and enable dark mode
2. open to text files and press ctrl+alt+c to start the compare 
3. see the highlighted results that are hard to read

### Expected Behavior
when enabling dark mode the plugin should auto change it's highlight colors to darker tones or permanently change the colors to darker tones no matter if the user selected white or dark mode.

### Debug Information
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
![Capture](https://user-images.githubusercontent.com/33640073/145711678-73cc847f-40a3-4aeb-b684-c82d9f722d95.PNG)
![Capture2](https://user-images.githubusercontent.com/33640073/145711679-17488db1-acd5-48cf-ad64-35a241f7201c.PNG)

**Comment by pnedev** [comment]
I'll see what I can do, thanks.

**Comment by nielsvdc** [comment]
Maybe add an ability to manually change the font color?

And of course it would be super to automatically detect dark mode and change the color settings accordingly.

**Comment by ageekhere** [comment]
I also have this issue, looking forward to a fix.

**Comment by pnedev** [comment]
@nielsvdc ,

> Maybe add an ability to manually change the font color?

You can change the colors manually by going to the plugin menu and opening its Settings.

The fix will be to make automatic default colors for N++ dark mode.

**Comment by RFBomb** [comment]
> > Maybe add an ability to manually change the font color?
> 
> You can change the colors manually by going to the plugin menu and opening its Settings.

There is no setting for 'Font Color' in the plugin settings page.

**Comment by pnedev** [comment]
Oh, yes, you are right about the font color. It cannot be changed currently.
I miss-interpreted the question as it was about the background color, sorry.

**Comment by mappao** [comment]
Also an option to disable highlight colors and leave just icons at left of involved rows would be really appreciated here ;) Thank you

**Comment by pnedev** [comment]
@mappao ,

Unfortunately that will not be currently possible.
You could open another ticket for that request if you like just to have that filed but I cannot promise it will be implemented, sorry.

**Comment by jocker-il** [comment]
Plugin-admin doesn't show there is a newer version for Compare - so is it better to remove compare and install comparePlus ? I'm using 8.1.8 x64, but no problem updating to newest ofc

**Comment by elisimpson** [comment]
Hoping ComparePlus resolves this issue. Back to Light Mode until it's released

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
