### ISSUE TITLE
Compare windows scroll to right or end of line

### ISSUE THREAD

**Issue by giustizieri25** [pnedev/compare-plugin#274]
When comparing two files side-by-side, the right side pane scrolls to the right, or to the end of line.
This makes the compare operation annoying, as you always have to scroll back everything to the left again, to see the compared contents.

![image](https://user-images.githubusercontent.com/16947497/146955928-5ff4454a-44cc-4b6b-8efc-87590261c354.png)

**Comment by pnedev** [comment]
This is the intended behavior when the lines are too long and your cursor position is beyond the visible line width.
Then the line is horizontally scrolled and the other compared document is synchronously scrolled to see the selected lines positions side by side and visually inspect them.

If you want to avoid that simply move your cursor position in the beginning of the line or turn on the Wrap Line function in Notepad++
