### ISSUE TITLE
v2.0.2 Crashes

### ISSUE THREAD

**Issue by MountainMan73** [pnedev/compare-plugin#276]
I cannot get v2.0.2 to work properly. I am using 64-bit. I have used Compare for many years and I just upgraded to 64-bit v2.0.2 and every time I attempt a Compare with 2 files open, I get about a 1 second pause and then Notepad++ exits. I have tried with different files, the same text in 2 different files and it happens each time. I just switched back to v2.0.1 and I get it to work as before.

**Comment by Yaron10** [comment]
@MountainMan73,

What version of Notepad++ are you using?

**Comment by pnedev** [comment]
@MountainMan73 ,

Compare Plugin v2.0.2 is specifically done for Notepad++ versions 8.2.2 and above.
It WILL crash for versions before 8.2.2.
There are no functional differences between Compare v2.0.1 and v2.0.2 - they are just for different Notepad++ versions.

Thank you @Yaron10 , good point ;)

**Comment by MountainMan73** [comment]
I was using v8.2.1. I just installed v8.3 and your Compare 22.0.2 works as it should.

BTW, this is a really nifty add-in. I write VB code for VBA and VB6 and I get versions of modules out of sync all the time and this tool is indispensable for me. I have been using it for quite a while now. Good job. Thanks for writing/supporting it.

**Comment by jcstevensri** [comment]
@MountainMan73 
Reported to Notepad++ Plugin Forum - https://community.notepad-plus-plus.org/topic/22651/notepad-8-2-1-incompatible-with-compareplugin-2-0-2
