### ISSUE TITLE
ARM64 Compilation?

### ISSUE THREAD

**Issue by specul8** [pnedev/compare-plugin#277]
Hi! Is it possible to get a compilation of this as ARM64 to support the ARM64 version of N++?

Thanks!

**Comment by pnedev** [comment]
@specul8 ,
OK, I will look into it.

**Comment by pnedev** [comment]
Could you please try this [ARM64](https://ci.appveyor.com/api/buildjobs/72ewq2upcnfwdvuy/artifacts/ComparePlus.dll) build and tell me if it is working?
Put the DLL in Notepad++ plugins folder under _ComparePlus_ subfolder and restart Notepad++.
Please have in mind that it is the new ComparePlus plugin which is not yet officially released and there are also no ARM64 Git and SVN libraries included so those commands will not work.
The ARM64 support will be available only in the new plugin (ComparePlus) as I have stopped actively supporting the old Compare plugin.

Thanks for the feedback in advance.

**Comment by specul8** [comment]
Worked perfectly - Thanks Pavel!

 

Brad

**Comment by pnedev** [comment]
Excellent, thanks for the quick check Brad.

Later I'll see if I could easily build the Git and SQLlite libraries for ARM64.

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
Only SVN diff is not possible on ARM64 architectures due to missing SQLlite library for those platforms.
