### ISSUE TITLE
Restore to Default Zoom

### ISSUE THREAD

**Issue by NebrBorn** [pnedev/compare-plugin#278]
When compare is run, application restores to default zoom setting.

**Comment by pnedev** [comment]
I can reproduce it in Compare plugin 2+, OK.

Unfortunately I have stopped supporting Compare plugin and will no longer do functional changes to it, only Notepad++ compatibility fixes.

The good news is that I will be releasing in a month a new compare plugin named ComparePlus that is very enhanced continuation of Compare 2 and it doesn't have that flaw.

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
