### ISSUE TITLE
Notepad++ Crashes when comparing text files

### ISSUE THREAD

**Issue by mvaneijken** [pnedev/compare-plugin#279]
Notepad++ crashes when comparing text files. It makes no difference which file or what the length is.

Notepad++ 8.2.1.0 x64
Compare Plugin v2.0.2 (installed using plugins admin)
OS: Windows 11 Enterprise

Crash report:
Version=1
EventType=APPCRASH
EventTime=132890607841788005
ReportType=2
Consent=1
UploadTime=132890607845068012
ReportStatus=268435456
ReportIdentifier=1931b395-a279-4b50-978b-66e852044b4f
IntegratorReportIdentifier=2ec13be7-b799-4581-a879-6a5ba3c80894
Wow64Host=34404
NsAppName=notepad++.exe
OriginalFilename=notepad++.exe
AppSessionGuid=000113ec-0001-006b-3657-e0bd4d1fd801
TargetAppId=W:000684110326953e0258d51f78b14349dbf000000904!0000dcec68639a726c2ec209293a262d5b0ebf994dc9!notepad++.exe
TargetAppVer=2022//01//19:17:45:14!5d5c5d!notepad++.exe
BootId=4294967295
ServiceSplit=122867528
TargetAsId=25056
UserImpactVector=808452912
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=49175d96cb3d091d2db92ed1b72fb251
Response.BucketTable=4
Response.LegacyBucketId=2141794576047780433
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=notepad++.exe
Sig[1].Name=Application Version
Sig[1].Value=8.2.1.0
Sig[2].Name=Application Timestamp
Sig[2].Value=61e84e2a
Sig[3].Name=Fault Module Name
Sig[3].Value=notepad++.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=8.2.1.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=61e84e2a
Sig[6].Name=Exception Code
Sig[6].Value=c000041d
Sig[7].Name=Exception Offset
Sig[7].Value=000000000003effa
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.22000.2.0.0.256.4
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1043
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=800b
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=800bfd0e114bf765ed94cb697784989d
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=c5fd
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=c5fd9756d47016c27a44e0e827ba7a4f
UI[2]=C:\Program Files\Notepad++\notepad++.exe
LoadedModule[0]=C:\Program Files\Notepad++\notepad++.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[5]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[6]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22000.120_none_9d947278b86cc467\COMCTL32.dll
LoadedModule[7]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[8]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[9]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[10]=C:\WINDOWS\System32\win32u.dll
LoadedModule[11]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[12]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[13]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[14]=C:\WINDOWS\System32\USER32.dll
LoadedModule[15]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[16]=C:\WINDOWS\SYSTEM32\dbghelp.dll
LoadedModule[17]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[18]=C:\WINDOWS\System32\WINTRUST.dll
LoadedModule[19]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[20]=C:\WINDOWS\System32\IMM32.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\WININET.dll
LoadedModule[22]=C:\WINDOWS\SYSTEM32\SensApi.dll
LoadedModule[23]=C:\WINDOWS\System32\COMDLG32.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\MSIMG32.dll
LoadedModule[25]=C:\WINDOWS\System32\combase.dll
LoadedModule[26]=C:\WINDOWS\System32\shcore.dll
LoadedModule[27]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[28]=C:\WINDOWS\System32\sechost.dll
LoadedModule[29]=C:\WINDOWS\System32\ole32.dll
LoadedModule[30]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[31]=C:\WINDOWS\SYSTEM32\UxTheme.dll
LoadedModule[32]=C:\WINDOWS\SYSTEM32\MSASN1.dll
LoadedModule[33]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[34]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[35]=C:\WINDOWS\System32\imagehlp.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[37]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[38]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[39]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[41]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\TextShaping.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[44]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[45]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[46]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[47]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\textinputframework.dll
LoadedModule[49]=C:\Program Files\Notepad++\plugins\ComparePlugin\ComparePlugin.dll
LoadedModule[50]=C:\Program Files\Notepad++\plugins\HTMLTag\HTMLTag.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\netapi32.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\SHFolder.dll
LoadedModule[53]=C:\WINDOWS\SYSTEM32\wkscli.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\cscapi.dll
LoadedModule[55]=C:\Program Files\Notepad++\plugins\mimeTools\mimeTools.dll
LoadedModule[56]=C:\Program Files\Notepad++\plugins\nppConverter\nppConverter.dll
LoadedModule[57]=C:\Program Files\Notepad++\plugins\NppExport\NppExport.dll
LoadedModule[58]=C:\Program Files\Notepad++\plugins\NPPJSONViewer\NPPJSONViewer.dll
LoadedModule[59]=C:\Program Files\Notepad++\plugins\XMLTools\XMLTools.dll
LoadedModule[60]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22000.434_none_ce836c1412fb9b57\gdiplus.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
LoadedModule[62]=C:\WINDOWS\SYSTEM32\OLEACC.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\CoreMessaging.dll
LoadedModule[65]=C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
LoadedModule[66]=C:\WINDOWS\system32\propsys.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[68]=C:\Windows\System32\Windows.System.Launcher.dll
LoadedModule[69]=C:\Windows\System32\msvcp110_win.dll
LoadedModule[70]=C:\WINDOWS\SYSTEM32\windows.staterepositorycore.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=22000
OsInfo[3].Key=ubr
OsInfo[3].Value=493
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=176
OsInfo[8].Key=sku
OsInfo[8].Value=4
OsInfo[9].Key=domain
OsInfo[9].Value=1
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=221481605
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.22000.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=49093
OsInfo[19].Key=svolsz
OsInfo[19].Value=464
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=210604
OsInfo[22].Key=bldtm
OsInfo[22].Value=1628
OsInfo[23].Key=bldbrch
OsInfo[23].Value=co_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.22000.493.amd64fre.co_release.210604-1628
OsInfo[30].Key=buildflightid
OsInfo[30].Value=1c80e5fd-1c24-4bf1-97e9-a191d0c240bf
OsInfo[31].Key=edition
OsInfo[31].Value=Enterprise
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=fconid
OsInfo[34].Value=25704915,1,2,1;35825666,0,1,1
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
OsInfo[38].Key=servicinginprogress
OsInfo[38].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Notepad++ : a free (GPL) source code editor
AppPath=C:\Program Files\Notepad++\notepad++.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=85BEBAB64AC4A2750DD3BE0B301A2753
MetadataHash=-750897262

**Comment by Yaron10** [comment]
@mvaneijken,

See https://github.com/pnedev/compare-plugin/issues/276.

**Comment by mvaneijken** [comment]
Check, searched for it but didn't found it on that moment. This one is closed then,

**Comment by jcstevensri** [comment]
@mvaneijken 
Reported to Notepad++ Plugin Forum - https://community.notepad-plus-plus.org/topic/22651/notepad-8-2-1-incompatible-with-compareplugin-2-0-2
