### ISSUE TITLE
Compare to last Save: wrong files are compared

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#28]
STR:

Open two files.
*Activate the left file* and change anything in it (do not save).
Compare to last Save.

Result:
The existing files are compared and the changes are "undone".

**Comment by pnedev** [comment]
I'll look into this, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Thank you Pavel.

BR

**Comment by pnedev** [comment]
Fixed in master, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great job!
Thank you very much.

BR
