### ISSUE TITLE
v2.02 causes Notepad++ to Crash

### ISSUE THREAD

**Issue by Krammig** [pnedev/compare-plugin#282]
I have an issue with Compare, might well be something I am doing wrong or a setting somewhere, so I thought I would try v2.02 just in case it resolves it before I post my issue. 

However after selecting two files, and selecting Compare, I get a crash as follows. 

Just sharing in case it is helpful, I will just drop back to v2.01

Windows 7  SP1
HP i7
16GB Mem

Cheers

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	notepad++.exe
  Application Version:	8.2.1.0
  Application Timestamp:	61e84e2a
  Fault Module Name:	notepad++.exe
  Fault Module Version:	8.2.1.0
  Fault Module Timestamp:	61e84e2a
  Exception Code:	c0000005
  Exception Offset:	000000000003effa
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	4d4f
  Additional Information 2:	4d4f7286db83f9c877db33d396e597fc
  Additional Information 3:	1018
  Additional Information 4:	1018caa13b02353ab0a44d1ac1adf592

**Comment by pnedev** [comment]
@Krammig ,
Please read the release notes of Compare plugin v.2.0.2: https://github.com/pnedev/compare-plugin/releases/tag/v2.0.2
Compare 2.0.2 is NOT compatible with Notepad++ 8.2.1
