### ISSUE TITLE
Comapring two files, clicking at a location jumps the cursor to a previous location on that line. 

### ISSUE THREAD

**Issue by Krammig** [pnedev/compare-plugin#283]
I have come across an annoyance, but perhaps it is just me overlooking a setting …

I have two files open for compare.

When I click at a position on a line, the screen jumps back to an earlier location on that line and thus I then have to go and find the location I want and once again click in that location. Sometimes that is Ok, most times not.

What I usually have to do is after the screen jumps backwards to an earlier position, I then have to move the cursor to the location I want to alter that text.

Hope that makes sense.

Cheers

**Comment by pnedev** [comment]
@Krammig ,

I didn't understand you description, sorry.
Could you give step-by-step instructions how I can reproduce that?
Thanks.
