### ISSUE TITLE
Notepad++ crashed using compare plugin

### ISSUE THREAD

**Issue by garvarma** [pnedev/compare-plugin#284]
I installed in new PC with Windows 10 64bits, the Notepad ++ v8.2.1 (64bits).

Alter using Plugin Admin I installed compare plugin (v2.0.2). When i try to compare 2 files, appears a little windows with progress bar, and after 1second, all notepad ++ aplication closed.

What it happends? What else i can see?

Thanks

**Comment by rdipardo** [comment]
<https://github.com/pnedev/compare-plugin/releases/tag/v2.0.2>:

> This release is ONLY for Notepad++ versions above 8.2.2!!!
>
> If your Notepad++ version is below 8.2.2 please use Compare plugin v2.0.1 - there are no functional differences between v2.0.1 and v.2.0.2

**Comment by pnedev** [comment]
@garvarma ,

Did you use Plugins **Admin** to install Compare or you used Plugin **Manager**?

**Comment by greg-michael** [comment]
@pnedev I had this same issue, and I used the Plugins Admin to install, because the Compare plugin had disappeared from my N++ installation. I updated N++ to v8.3.1 and the issue was resolved.

**Comment by pnedev** [comment]
Thanks for the feedback @greg-michael

**Comment by pnedev** [comment]
All,

It seems there might be some problem with Notepad++ v8.2.1 PluginsAdmin Compare plugin versioning. Perhaps it is only true for the 64bit version, I don't know for sure.
I cannot do anything about it so if you happen to have the same issue please use Compare v2.0.1 with Notepad++ v8.2.1. You can download it from the Releases section here and install it manually.

I am sorry for the inconvenience.
