### ISSUE TITLE
Compare 2.0.2 is no more compatible with Notepad++ (after upgrade to V8.3.3)

### ISSUE THREAD

**Issue by revirevy** [pnedev/compare-plugin#286]
Hello

Compare 2.0.2 is no more compatible with Notepad++ (after upgrade to V8.3.3)

Error message : "GUP : the plugin package is built wrongly. this plugin will be uninstalled"

Best regards,

**Comment by pnedev** [comment]
Hi,

It should be working.
Try uninstalling Compare and then installing it again (through Notepad++'s Plugin Admin from the plugins menu).
Write back if it works.

BR

**Comment by stortec** [comment]
Hi,

I had the same problem, after starting Notepad++ as administrator I was able to install it.

Best regards

**Comment by pnedev** [comment]
Thanks for the info @stortec 👍 
I will mark that issue "invalid" then.

BR
