### ISSUE TITLE
Comparison doesn't work Oo

### ISSUE THREAD

**Issue by sweddd** [pnedev/compare-plugin#288]
Hello.
First of all, I would like to thank you for such a handy plugin that has helped me many times.
I also have to apologize for my terrible English.
So.
Until recently, everything was great.
Then I had to reinstall Windows and all programs. After that, the Compare plugin began to work "not like before".
I am comparing two tables. In the first table - only IDs, in the second table - some of these IDs + related information.
This is how the comparison looks now:
![image](https://user-images.githubusercontent.com/95692357/170961949-d9be2864-0fe1-48ca-96f5-11a8951f959c.png)

This is how the comparison should look like (this is how it looked before)
![image](https://user-images.githubusercontent.com/95692357/170962431-d046c77b-bb4c-48e7-9c77-10bd0b8e527c.png)

The main question is what am I doing wrong?

**Comment by sweddd** [comment]
I will add. It can still do what I need if I compare ID ONLY.
![image](https://user-images.githubusercontent.com/95692357/170989766-4e5b7a3d-df96-4ff7-8b52-f431dad9ae17.png)

**Comment by pnedev** [comment]
@sweddd ,

I stopped supporting Compare plugin because I'm close to releasing a new plugin named ComparePlus that is based on Compare but much more enhanced.

Meanwhile, can you tell me your Notepad++ version, the Compare plugin version and if you have other plugins installed?
Just go to Notepad++ menu, the question mark ('?') at the end and then click on `Debug Info...`.
Copy the info and paste it in this thread.

**Comment by sweddd** [comment]
@pnedev 
Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home Single Language (64-bit) 
OS Version : 2009
OS Build : 19044.1706
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by pnedev** [comment]
@sweddd ,

I have no idea what might be wrong at the moment. It doesn't seem you are doing anything wrong.
I would suggest to try reinstalling Compare plugin again manually:
- exit Notepad++ if it is running
- delete your current Compare plugin from `C:\Program Files\Notepad++\plugins\ComparePlugin\` (all files and folders in that folder)
- delete your current Compare plugin config from `C:\Users\YOUR_USER\AppData\Roaming\Notepad++\plugins\config\ComparePlugin.ini`
- download the plugin again from https://github.com/pnedev/compare-plugin/releases/download/v2.0.2/ComparePlugin_v2.0.2_X64.zip
- extract it and then copy the extracted files to the same folder as before so you'll have `C:\Program Files\Notepad++\plugins\ComparePlugin\ComparePlugin\` and `C:\Program Files\Notepad++\plugins\ComparePlugin\ComparePlugin.dll`
- start Notepad++ and run your compare again

Let me know if that works.

**Comment by sweddd** [comment]
Nothing changed :0(
![image](https://user-images.githubusercontent.com/95692357/171663037-a574c7b5-d067-424f-85c4-521f7891d40a.png)

**Comment by pnedev** [comment]
Thanks for trying.
Let's wait for me to release the new ComparePlus plugin and see if it has that problem as well.

**Comment by pnedev** [comment]
Hello @sweddd ,

I will release the new ComparePlus plugin in less than a month (it will be available through PluginsAdmin feature in next Notepad++ version probably or maybe the one that will follow) so can you try your test again when it is out and open another issue here if you still experience problems? Thanks a lot.

I will close this thread now as it concerns the old Compare plugin.

BR
