### ISSUE TITLE
control plugin from command line

### ISSUE THREAD

**Issue by jkiss56** [pnedev/compare-plugin#293]
Hi,
Notepad++  v8.4.2 supports a "message" to a plugin from command line
Would it be possible to start N++ from command prompt opening 2 files in comapare mode?
something like -pluginMessage="second filename to open"

**Comment by pnedev** [comment]
Hi @jkiss56 ,

It is already implemented in ComparePlus - a new plugin, successor of Compare that is about to be released soon (in a month or so).

The command to run compare from command line will be:

`notepad++ -pluginMessage="compare" old_file.txt new_file.txt`

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
