### ISSUE TITLE
Compare - Hebrew

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#299]
Hello Pavel,

I don't compare Hebrew files very frequently.
I've tested [the latest commit](https://github.com/pnedev/compare-plugin/commit/1dbfb927c81cd61d9977da47b6a6849859843b3d) vs. [the previous one](https://github.com/pnedev/compare-plugin/commit/b12f1b4ae7f43bf310dc7b96a604228e56237880).

[Here are the files](https://github.com/pnedev/compare-plugin/files/9073123/TestHebrew.zip).
Please remember to change "View -> Text Direction" to RTL.

Thank you for looking into it.

BR

***

**Latest https://github.com/pnedev/compare-plugin/commit/1dbfb927c81cd61d9977da47b6a6849859843b3d**:
**ANSI**:
The results are "Character Diffs" even if that setting is unchecked.
The results are also _wrong_ (first and second lines).

![תמונה](https://user-images.githubusercontent.com/10229320/178015514-b403d80f-8776-4294-a009-5c3b56c73056.png)

**UTF-8**:
"Character Diffs" - _correct_.
![תמונה](https://user-images.githubusercontent.com/10229320/178016147-a7319425-70a2-45a5-9c06-66518370527c.png)

"Character Diffs" unchecked - _wrong_.
![תמונה](https://user-images.githubusercontent.com/10229320/178017942-4f9cd9a7-3914-41d0-9ba4-224baa5bd920.png)

***

**Previous https://github.com/pnedev/compare-plugin/commit/b12f1b4ae7f43bf310dc7b96a604228e56237880**:
**ANSI**:
"Character Diffs" unchecked - _correct_.
![תמונה](https://user-images.githubusercontent.com/10229320/178018880-44eb8db7-97d5-4ae5-8af7-b5509c6f2331.png)

"Character Diffs" - _correct_.
![תמונה](https://user-images.githubusercontent.com/10229320/178019524-1f8b8b3b-c232-4291-8040-5b0ec8964ed9.png)

**UTF-8:**
The results are "Character Diffs" even if that setting is unchecked.
The results are also _wrong_ (first and second lines).

**Comment by pnedev** [comment]
Hello Yaron,

Could you please test again this build when you have the time:
https://ci.appveyor.com/project/pnedev/compare-plugin/builds/44301097 ?

Thank you!

**Comment by Yaron10** [comment]
Hello Pavel,

With https://github.com/pnedev/compare-plugin/commit/84e001ba36dacb2ebcfa213c97087af7752c3d18.
Comparing **UTF-8** files, the results are perfect.
Comparing **ANSI** files, the results are "Character Diffs" even if that setting is unchecked and they are also wrong.

Is that expected? Should it only work with UTF files? 

Thank you very much for your work. I do appreciate it. 👍 

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for testing that.

> Is that expected? Should it only work with UTF files?

Yes, that is expected. Files should be UTF.
I will consider that issue fixed unless you have additional comments / concerns.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

👍 
No additional comments / concerns. :)

Thanks again for your great work.

BR

**Comment by pnedev** [comment]
Hello Yaron,

The strange thing is that on my side your example ANSI files compare the same as your UTF8 files in both cases (char diffs and no char diffs).
When I open the ANSI files my character set is actually set to Windows-1255.
Is it the same on your side?

Thanks

**Comment by Yaron10** [comment]
Hello Pavel,

That's a good and interesting point. 👍 

I have `Autodetect character encoding` (NPP Preferences -> MISC.) unchecked.
Checking it, I get your results: Windows-1255 and correct Compare.

But for my personal use, NPP seems to work better with that setting unchecked.

Thank you.

**Comment by Yaron10** [comment]
Hello again Pavel,

I've just tested https://github.com/pnedev/compare-plugin/commit/73b47941e760cdc2098b3f698705e36cc441045d.
Both UTF8 and ANSI seem to work perfectly and regardless of `Autodetect character encoding`.

This is absolutely great! 👍 
Thank you very much.

Could you confirm please?

**Comment by pnedev** [comment]
Hello Yaron,

The result on my side is the same, it confirms your observations, excellent :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Thanks again for your great work.

BR
