### ISSUE TITLE
Incompatible with Notepad++ v8.4.2

### ISSUE THREAD

**Issue by acreconsulting** [pnedev/compare-plugin#302]
Installed the latest update of Notepad++ and it's forcing this plugin to be disabled, citing incompatibility.

**Comment by pnedev** [comment]
Hello @acreconsulting ,

I stopped supporting Compare plugin.
I'm working on another plugin that is its successor called ComparePlus. Its first release will be in less than a month and will be available through Plugins Admin dialog in the next versions of Notepad++.

You could try deleting Compare plugin and reinstalling it again to see if it fixes your problem. AFAIK Compare plugin should be working on Notepad++ v8.4.2.
