### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#33]
Hello Pavel,

After testing the new version (and briefly looking at the re-written Compare.cpp) I'm just beginning to appreciate your remarkable accomplishment.
When we first discussed the concept of Multiple Compares I thought it would take you at least a few months. :) Amazing.
The design and structure are simply beautiful.

On behalf of myself and thousands of future happy users: Thank you!

As you have mentioned this is the first draft and naturally it has some issues.
With some minor adjustments and fine-tuning Compare Plugin v2.0 (yes, this should be the new version) would be a masterpiece.

I know you you don't like opened issues. You can close this one. :)

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for all the feedback.
There is still much to improve end enhance but my idea was to make a decently working version that can be released to the community and used without worrying about the stability (as you initially discussed with Ede).

I'm thinking of opening a generic discussion "issue" thread :)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> but my idea was to make a decently working version that can be released to the community and used without worrying about the stability (as you initially discussed with Ede).

If you had only refactored the memory allocation and fixed two/three other issues, I would have been very happy and suggested you should announce a new version.

But you have done wonders to Compare. Literally.
It's only natural that in such a scale of work some issues would pop up.
As you have written: We are not in a hurry. 
Let's take it easy. :)

BR
