### ISSUE TITLE
Compared files wrongly activated

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#34]
Hello Pavel,

STR:

Have two files in the top view and tow others in the bottom view.
Compare.
Activate a not-compared file.
Activate the not-compared file *in the other view*.

Result:

The compared files are activated.

Thank you.

BR

**Comment by pnedev** [comment]
Yes, this is something I've noticed already but haven't found a workaround to it yet.

It appears that when switching between the views N++ first activates the currently active file in the new view (or something like that). I'll investigate this for sure but it is with low priority for now.

Thanks for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for the explanation. Interesting.
I do appreciate your perseverance. Best of luck.

BR

**Comment by pnedev** [comment]
Fixed in latest master commit.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Brilliant work. Synchronizing the compared pairs is a fantastic feature. :+1: 

Still a minor issue:
Have two files in the top view and tow others in the bottom view.
Compare the two on the left.
Compare the two on the right.
Clear All Compares.

Result:
The wrong file gets active-not-focused.

Thank you very much.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Thanks.
I don't understand "_gets active-not-focused_".
I've tried the steps and couldn't find any inconsistency.
Could you elaborate more?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

If you have a file at top and another at bottom, NPP refers to both as active: active-focused and active-unfocused.
See Style Configurator -> Global Style -> "Active tab focused indicator" and "Active tab unfocused indicator".

Have files A+B at top and C+D at bottom.
Compare A to C.
Compare B to D (currently B is active-focused and D is active-unfocused).
Clear All Compares.

Result:
C is active-unfocused instead of D.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Now I see what you mean, thanks for clarifying.
This is fixed in latest master.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much.

BR
