### ISSUE TITLE
Issues when comparing and view's ID is SUB_VIEW

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#35]
STR:

Single-View and view's ID is SUB_VIEW.
Open three files.
Compare.

Result:
Diff marks are not cleared in one file.
If you compare again, current and *next* are compared.

Thank you.

**Comment by pnedev** [comment]
Confirmed, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Thank you. I appreciate that.

BR

**Comment by pnedev** [comment]
Fixed in master, thanks.

BR
