### ISSUE TITLE
Diff Marks are cleared after switching files

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#36]
STR:

Open two files.
Compare.
Reopen a file from the Recently Closed Files list.
Switch back to the compared files.

Result:

Some (or all) Diff Marks are cleared.

**Comment by pnedev** [comment]
Thanks for reporting, I'll investigate this soon.

BR

**Comment by Yaron10** [comment]
Thank you Pavel. I appreciate it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

This seems to be solved in the latest https://github.com/pnedev/compare-plugin/commit/f2281774fb55ae64aa90438c04c7f753bbf98120.

Thank you very much.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

This seems to be solved in the latest https://github.com/pnedev/compare-plugin/commit/f2281774fb55ae64aa90438c04c7f753bbf98120.

Thank you very much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

OK, that's good. I'm closing this then.
Thanks.

BR
