### ISSUE TITLE
Empty lines are not removed

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#37]
STR:

Open two files.
Compare.
Reopen a file from the Recently Closed Files list.
Clear All Compares

Result:

Temporarily empty lines are not removed.

**Comment by pnedev** [comment]
Hello Yaron,

In my N++ workflow I never use Recently Closed Files list. I have totally disabled it.
Thanks for catching all the "Recently Closed Files list" related plugin issues :+1: 

I'll look into those soon.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> In my N++ workflow I never use Recently Closed Files list. I have totally disabled it.

Now I understand why you regarded https://github.com/pnedev/compare-plugin/issues/19 as unrelated to Compare. :)
It's not caused by Compare but if you regularly use "Restore recent closed file" (I have a toolbar button for that), this is a **huge** problem for Compare users.

Thank you very much.
BR

**Comment by pnedev** [comment]
Well, perhaps you are right. When I get to this your words for sure will make more sense.
Anyway, regarding #19 I really think it is N++ thing and I'm not sure we can do much about that.
We'll see, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Thank you Pavel.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

This seems to be solved in the latest https://github.com/pnedev/compare-plugin/commit/f2281774fb55ae64aa90438c04c7f753bbf98120.

Thank you very much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Great. I'm closing this issue then, thanks.

BR
