### ISSUE TITLE
Diff Marks are not cleared after "Move to Other View"

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#38]
Hello Pavel,

STR:

Compare.
Move to Other View.

Result:

The Diff Marks are not cleared in the other file.

I wonder why. Isn't a Close message sent when "Move to Other View" is executed?

Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, I know about that issue and I think its root cause is the same as in [this](https://github.com/pnedev/compare-plugin/issues/34) issue.
I'll definitely investigate that further, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Thank you. I appreciate that.

BR

**Comment by pnedev** [comment]
Fixed in latest master branch commit. Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Very nice. :+1: 
Thank you.

BR
