### ISSUE TITLE
Add Sound notification when wrapping around 

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#4]
After the line
`FlashWindowEx(&flashInfo);`
add
`MessageBeep(MB_OK);	// Yaron - Sound notification.`
Thank you.

**Comment by pnedev** [comment]
I'm not overly fond of sound notifications.
Do you really need that?

**Comment by Yaron10** [comment]
No problem at all.
Personally I find it helpful and I'll add it for my personal use. :)

BR.

**Comment by jsleroy** [comment]
This issue was moved to jsleroy/compare-plugin#40
