### ISSUE TITLE
Activate Sub-View before closing files

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#40]
Hello Pavel,

If you Compare when multiple files are open in Single-View mode, the original view's ID affects the following behavior:
If it's MAIN_VIEW most of the files are in the top view.
If it's SUB_VIEW most of the files are in the bottom view.

Most users don't know how NPP's "Move to Other View" is handled and might wonder about this inconsistency.
I think we should do whatever possible not to change the *default* view's ID in Single-View mode.

Currently after closing matched files, the view's ID is SUB_VIEW.

And therefore I think we should replace

```
                ::SendMessage(nppData._nppHandle, NPPM_MENUCOMMAND, 0, IDM_FILE_CLOSE);
                ::SendMessage(nppData._nppHandle, NPPM_MENUCOMMAND, 0, IDM_VIEW_SWITCHTO_OTHER_VIEW);
                ::SendMessage(nppData._nppHandle, NPPM_MENUCOMMAND, 0, IDM_FILE_CLOSE);
                ::SendMessage(nppData._nppHandle, NPPM_MENUCOMMAND, 0, IDM_VIEW_SWITCHTO_OTHER_VIEW);
```

with
```
                HWND focusedView = ::GetFocus();
                ::SetFocus(nppData._scintillaSecondHandle);

                ::SendMessage(nppData._nppHandle, NPPM_MENUCOMMAND, 0, IDM_FILE_CLOSE);
                ::SendMessage(nppData._nppHandle, NPPM_MENUCOMMAND, 0, IDM_VIEW_SWITCHTO_OTHER_VIEW);
                ::SendMessage(nppData._nppHandle, NPPM_MENUCOMMAND, 0, IDM_FILE_CLOSE);

                if (IsWindowVisible(focusedView))
                    ::SetFocus(focusedView);
```

Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I'm really curious what is it that bothers you so much with those views :))

My opinion is that the Compare plugin is not Notepad++'s view manager. It's job is to compare and leave the things as close as possible to the state they were before the compare. The user should be aware of the views and how to handle them if he gets to a point where his single view is actually the sub-view. This would mean that he deliberately had moved files to that view and should expect them to remain there after the compare. If he never moves files and uses compare (which is now totally possible with the "Select first" command) he wouldn't bother about views at all.

This is why I don't consider this an issue, just on the contrary - the other behavior might seem as an issue to an experienced user that knows what he's doing.
Do you agree? :)

Thanks.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

> This would mean that he deliberately had moved files to that view and should expect them to remain there after the compare.

That's the point.
The user has not moved any files, but we have changed the default view from 0 to 1.

STR:

Start NPP.
Open two files and compare.
Files match. Close? - Yes.

Result:
The view is 1.
Why should we do that?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

This definitely needs fixing then. Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I appreciate it.

BR

**Comment by pnedev** [comment]
Fixed in master branch.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much.

Two related questions:

***
Start NPP.
Open two matched files.
Move to Other View.
Compare.
Files match. Close? - Yes.

Result:

The view is 1.

*

Start NPP.
Open two matched files.
Move to Other View.
*Activate the file at top.*
Compare.
Files match. Close? - Yes.

Result:

The view is 0.

Should the result depend on the currently focused view?
Wouldn't it make more sense to return to MAIN_VIEW in both cases?
You can argue that we don't have a "Restore Point" (i.e. we can't be sure of the view's ID before the Two-Views mode), so why return to MAIN_VIEW?
Well, the user wants to return to Single-View and MAIN_VIEW is default.
***
Two matched files; Single-View; SUB_VIEW.
Compare.
Files match. Close? - Yes.

Result:

The view is 0.

Shouldn't we restore the original SUB_VIEW?
Is the experienced user so sophisticated and knows we return to MAIN_VIEW because it's the active view when he presses "Yes"? :)

This question is relevant to the code I suggested as well.
***
Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

You are right. It seems there is some inconsistency there. I'll check that, thanks for reporting this.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Now if equal files are closed (and there are no other files open) the view will always be the main one (0).
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Now if equal files are closed (and there are no other files open) the view will always be the main one (0).

Even if the original view was 1 (which is fine).

Thank you.
BR

**Comment by pnedev** [comment]
> Even if the original view was 1 (which is fine).

Exactly. :)

BR
