### ISSUE TITLE
"Close compared files" on Cancel

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#42]
Hello Pavel,

Continued from https://github.com/pnedev/compare-plugin/issues/27#issuecomment-206392415.

This makes sense.
However, and with your permission, there's a difference between Match and Cancel:
In the first case we have to display a message box *anyway*; so why not offer an option to close the files?
In the second case the message box is not necessary.
Good modern applications avoid using message boxes (interrupting the workflow and forcing the user to press OK) if possible.

I hope you agree. :)

Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Hm, I don't think it is a good idea to close the files without a prompt in the Cancel case.
Sometimes I have an open file from a project and I want to compare it to a file from another project. I open the second file and compare and if for whatever reason the plugin closes my first file without at least asking that will really piss me off.

I think I'll leave this as it is now.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

This issue's title was not a request but a reference to https://github.com/pnedev/compare-plugin/issues/27#issuecomment-206392415.
It never occurred to me to suggest closing the files without a prompt. Give me some credit. :) :) 
My point was that the message box was not necessary in this case.

Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I didn't mean to sound harsh if that's what you felt.
I really value your opinion and feedback. Thanks.
I guess it's just another misunderstanding :)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I appreciate your kindness.
I actually found this misunderstanding quite funny. "Give me some credit." was written with a wink. :)

BR
