### ISSUE TITLE
[Enhancement] Provide icons for Compare and Clear Current Compare

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#46]
Hello Pavel,

How about providing icons for Compare and Clear Current Compare?

If you want to be really sophisticated you might get the `"ScintillaViewsSplitter"` setting from config.xml and accordingly use either Compare Horizontal.bmp or Compare Vertical.bmp.

But on a more serious note, it wouldn't be difficult to offer a version with Horizontal icons and another with Vertical ones.
***
When disabled, 16bpp and 32bpp images look differently on the toolbar.
I have converted the navigation icons to 32bpp for consistency.

Thank you.

Best regards.

[Compare Icons.zip](https://github.com/pnedev/compare-plugin/files/211416/Compare.Icons.zip)

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for the updated icons - I'll get them some time soon.
The idea about the "Compare", ... icons is not bad but I'll think about it more later.
I won't bother checking _config.xml_ - it is not that interesting and important to me, sorry :)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> If you want to be really sophisticated you might get the "ScintillaViewsSplitter" setting from config.xml and accordingly use either Compare Horizontal.bmp or Compare Vertical.bmp.

That was a philosophical comment. And I continued "But on a more serious note".
One day we'll be better synced. :)

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I have updated the existing icons to your new 32bpp versions, thanks for supplying those.
About the other icons - the ones for "Compare" and "Clear Current Compare" - they don't seem to me appropriate enough, sorry. They look to me more like a "Show two views mode" and "Close two views mode" commands and thus I find them misleading.
If we can find other more appropriate ones we can add them later.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

You are right. Thank you.

BR
