### ISSUE TITLE
Compare sets focus to Find dialogue

### ISSUE THREAD

**Issue by xylographe** [pnedev/compare-plugin#49]
CP 1d3e95abb30526a96dd58d3f07b9c0296201bfcc
NPP 6.9.1
Win7SP1[64]

I see this often, as I always keep the Find dialogue open (maximum transparency on losing focus).

This is just one of many ways to reproduce:
- Open two files in main view (A, B)
- Open Find dialogue
- Set focus to B (but keep Find dialogue open)
- Trigger Compare

Result: B-A Compare is performed, subsequently focus is set to Find dialogue.
Expected: B-A Compare is performed, subsequently focus is set to B.
\[Preferred: A-B Compare is performed, afterwards focus is set to A. But that's a different issue ;) \]

No big deal, as pressing `Win+Tab` will return focus to B, but it's a bit unusual, and most likely not intentional behaviour. :)

**Comment by pnedev** [comment]
I'll look into this, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Thank you my friends.

xylographe,

> [Preferred: A-B Compare is performed, afterwards focus is set to A. But that's a different issue ;) ]

Can you explain that please? 
Do you mean B should be in the right/bottom view? If positive, https://github.com/pnedev/compare-plugin/issues/29 is relevant.

Best regards.

**Comment by xylographe** [comment]
Yes, A in the main (left) view, B in the sub (right) view, because A will be the base file.
I always order different versions from oldest (on the left) to most recent (on the right).
As I mentioned in another issue, I'm visually left-to-right oriented.

**Comment by Yaron10** [comment]
Thanks for clarifying that.

A ("base file") is the old file.
B (current file) is the new file.
You want B to be in the right view.

If that was the behavior and you *happened* to Compare when A was active, you wouldn't get the desired layout. Correct?
IOW, you have to "calculate" (or at least make sure) which file is active before comparing. Right?

Do you agree that many users might open the new file, then the old one and Compare?
Don't you think that some users might wonder why the current file is placed in the secondary panel?

**Comment by xylographe** [comment]
Assume (X, ^A, B, Y) \[A is active (^)\], then triggering "Compare" would result in (^X, B, Y | A) with an X-A compare, which would be useless if X and A are unrelated. So, indeed, I would activate B, then trigger "Compare", to get the desired A-B compare: (X, ^A, Y | B). One could look at it as an implicit "Set first" on the left neighbour of the active file. After "Clear Compare" I would like the original situation restored: (X, A, ^B, Y).

It seems natural to me that the origin (old/base) is on the left side and the current (new) on the right side when comparing two files. Therefore it's normal that the current (new) file is placed in the secondary view, while the origin (old) remains in the primary view. I think, many more users might be surprised if you were to place origin (old) in the secondary view, keeping current (new) in the primary view. *I* certainly wouldn't want new on the left and old on the right.

**Comment by pnedev** [comment]
Hello @xylographe  and @Yaron10 ,

It appears that is totally a user perspective and thus it seems inevitable some users to get dissatisfied with the implementation (whatever that may be).

@xylographe ,
My preference as a user is exactly the opposite of yours, no offence here.

So it seems that in the far future the compare plugin would need some user setting about the preferred behavior.

For the time being I find it natural to move the first file ("Set first" or the currently active file from which we start the compare in single view) to the first N++ view (top/left) as it is the case now.
The notation of "new/old" version of the file here is totally missing and is known only by the user.
Well, the things will be different when we do compare to last save, Git or SVN - then we are entering the realm of the user preference (as discussed above).

Thanks for sharing your thoughts.
If you'd like to further discuss this or request a change in this regard would you please move to the General Discussion or a new issue thread, please?
I'd really like to keep the concrete issues as clean as possible so nothing get's lost in-between and I can orient faster in what's proposed/discussed/requested/pending.
IOW -> Let's try to keep a single topic in a single issue.

Thanks for understanding.

BR

**Comment by pnedev** [comment]
Fixed in master, thanks,

BR

**Comment by xylographe** [comment]
Thank you Pavel.

Fix confirmed (CP 754fa33d56bb29367ecc9a03b85e786538218380)

**Comment by Yaron10** [comment]
Hello Pavel,

The issue reported here has been resurrected in v3. :)

STR:
Open any docked window.
Move the focus to the editor.
Compare.

Result:
The docked window gets the focus.

I hope you're doing well.
BR

**Comment by pnedev** [comment]
Hello @Yaron10 ,

Thank you very much for all your recent feedback.
I'll have a look and write whenever I can.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Please try **[this](https://ci.appveyor.com/api/buildjobs/ic6yf5hwkq32xpda/artifacts/ComparePlugin.dll)** binary.

Thank you.

BR
