### ISSUE TITLE
Compare margin not removed when closing files without Clear Compare

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#50]
Hello Pavel,

STR:

Compare.
Close one of the compared files.

Or:
Compare.
Files match. Close? - Yes.

Result:

Compare margin is not removed.

Thank you.

BR

**Comment by pnedev** [comment]
Will check that, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much.

BR

**Comment by pnedev** [comment]
Fixed in master, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Files match. Close? - Yes.

Fixed.

> Close one of the compared files.

Still a problem in some cases if you don't return to Single-View mode.

I assume you know this issue didn't exist up until a few commits ago.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> Still a problem in some cases if you don't return to Single-View mode.


Can you give me steps how I can reproduce this? Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I reproduced the issue, I'll look into it, thanks,

BR

**Comment by pnedev** [comment]
Hello again,

I fixed that in master, however, there is still an issue with the margin when you close a file and another is activated in its view, that is compared. In this case the margin is as if the new file is not compared.
I'll fix that soon too.

BR

**Comment by pnedev** [comment]
Fixed, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Very nice.
Thank you very much.

BR
