### ISSUE TITLE
Move to first diff after re-compare

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#54]
Thank you Pavel.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I intentionally made CP remember the last position if re-comparing and return to that.
Do you find it more convenient to go to first after re-compare?

Here is a scenario:
You compare A and B.
You see that the first 5 differences are no problem and reach the sixth one.
You review the sixth and alter the new file and would like to continue on to the seventh diff (and further down) but trigger re-compare to keep the comparison in sync.
Now after the re-compare you go again to the first diff.

Wouldn't it be better to remain at the position you have been last before the re-compare?
Thanks.

BR

**Comment by xylographe** [comment]
I would like to keep this user friendly feature.

When you return to the last position after re-compare, going back to the first diff is only one 
`Ctl-Alt-PgUp` away.

When you jump to the first diff after re-compare, going back to the previous editing position takes more effort.

**Comment by xylographe** [comment]
To be more precise, I can think of two re-compare scenario's:

1. After editing. In this case I would like to stay at the last position.
2. After external file modification. In this case jumping to the first diff *might* be more desirable.

**Comment by pnedev** [comment]
Hello @xylographe ,

2. is not relevant at the moment because there is no N++ notification about file reload (as we've discussed before). Otherwise I agree on that. I'll think about reload later.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I thought this behavior might be intentional and I can see the advantage in some cases.
Again, consistency vs. possible efficiency. :)

Anyway, In my personal workflow I prefer to move to the first diff.
If you decide to keep the current behavior, could you please refer me to the relevant code?
I suppose I should add `First()` somewhere. I haven't looked at the code for quite a while. :)

Thank you very much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> Again, consistency vs. possible efficiency. :)

User preference actually :)

I can add config setting for this. The current implementation will be the default.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I can add config setting for this.

I assume other users may also prefer to move to the first diff. A setting would be good.

Thank you very much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Config setting for re-compare position added - try latest master commit.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. Thank you very much.

BR
