### ISSUE TITLE
Focus moved to other view after closing a compared file

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#55]
Hello Pavel,

STR:
Have two files at top and two at bottom.
Compare two files.
Close one compared file.

Result:
The compared file in the other view is activated.

Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

What would you expect the behavior to be? Remain in the view of the closed file?

What about if you started from single view?
Would you then like to restore the focus to the other compared file?
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> What would you expect the behavior to be? Remain in the view of the closed file?

I think this would be the expected behavior; just like in a case the user manually had the same layout and closed a file. If I understand it (the code structure) correctly, CP shouldn't interfere and let NPP activate the other file in the same view.

> What about if you started from single view?
> Would you then like to restore the focus to the other compared file?

Yes.
If I understand it correctly, CP shouldn't interfere and let NPP activate the other compared file.

Thank you very much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I agree about the two view mode.

I need some more clarification for single view mode.

> Yes.
If I understand it correctly, CP shouldn't interfere and let NPP activate the other compared file.

You are referring here the case where the compared files are adjacent. Then N++ will activate the other compared file on its own.
However, if we have files A, B, C in single view, we compare A and C (C is the file moved to the other view) then when we close C, the file activated by N++ will be B.
Do you think this should be the behavior in this particular case?

Thanks.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

> However, if we have files A, B, C in single view, we compare A and C (C is the file moved to the other view) then when we close C, the file activated by N++ will be B.

Why B? A was the active/not-focused file in the other view, and NPP should activate it.
Am I missing anything?

Thank you.
BR

**Comment by pnedev** [comment]
Maybe I am missing something :)

I'll test it and fix it, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

We all miss something at some point. :)
Thank you very much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Should be OK in latest master commit.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much.

BR
