### ISSUE TITLE
Ignore "Set first" if current is in the other view

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#56]
Hello Pavel,

Have several files in the top view and some others in the bottom.
Activate a file at top and Set first (currently set as NEW/PlusGreen).
Activate a file at bottom and Compare.

Result:
1) The file at top (set as NEW/PlusGreen) is MinusRed.
2) The file at top gets the focus.

There are some other confusing cases.

Suggestion:
"Set first" should override the old compare behavior only if both files (first and current) are in the same view.

Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Good point, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Thank you Pavel.
BR

**Comment by pnedev** [comment]
Hello Yaron,

It is a bit tricky to make "Set first" work only if both files are in the same view.
The current implementation also adds more flexibility.
Thus, I have fixed the _PlusGreen_ / _MinusRed_ issue you reported, could you please try the latest master to see if there are more "confusing cases"?
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

That's nice. Thank you.
Still, IMO it's highly confusing when the files change positions (i.e. the file at bottom is moved to top and vice-versa).
Is it *that* tricky? :)

Another confusing case:
Have two files at top and one at bottom.
Set one of the files at top as First.
Activate the other file at top.
Activate the file at bottom.
Compare.

The natural expected behavior in Two-Views mode is to compare the two active files.
I can see the benefit in "Set first" even in Two-Views mode but, again, I'd restrict it to a case where it's really useful.

Best regards.

**Comment by xylographe** [comment]
If you regard "Set First" as an action that overrules default behaviour, it all makes sense.
If you want default behaviour, don't use "Set First", or use "Clear Compare" before "Compare".

"Set First" allows you to select focal/base file first, then examine other tabs (in the same and/or the other view) until you find the file you want to compare to, and trigger "Compare". I think, it's a great feature.

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for the feedback.
I agree with xylographe here - if you don't want to override the default behavior simply don't use "Set first".

For whatever reason you might have several files in one view and several in the other. Then you might want to compare two files each in different view. "Set first" now allows you to choose which is the old and which is the new file without the need to manually move the files and after the compare - restoring them.

BR

**Comment by Yaron10** [comment]
Hello,

OK. :)
Thank you.

BR
