### ISSUE TITLE
Undo list is emptied after Compare

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#57]
Hello Pavel,

STR:
Modify a file.
Compare.

Result:
The Undo list is not available.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, that is expected.
Unfortunately I cannot change that. It is due to the "blank lines" insertion and is also suggested by the Scintilla documentation.
This should be the case in the older versions as well, is it?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Sorry.
In older versions the Undo command is not grayed-out but it doesn't actually undo (I didn't test that part :) ).
The current behavior is better. The command IS grayed-out. 

Thank you very much.
BR
