### ISSUE TITLE
Wrong highlighted section

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#58]
Hello Pavel,

**This issue exists in older versions as well.**

STR:
Compare the [prefs files](https://github.com/pnedev/compare-plugin/files/243904/prefs.zip) (prefsFF.js is focal).

Result:
The beginning of line 80 is marked as different.
If you delete the lines 78-79 in prefsFF.js and Compare, you get the expected results.

![Wrong](http://s32.postimg.org/6y26wrd91/Wrong.png)

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll look into this, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Thank you Pavel.
BR

**Comment by pnedev** [comment]
Hello Yaron,

This is fixed with the latest commit.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great work! 👍 I'm really impresses.
Thank you very much. I do appreciate your time and investment.

BR
