### ISSUE TITLE
Ctrl+Alt+F is taken :)

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#65]
Hello Pavel,

`Ctrl+Alt+F` does not set as First; it's used for Fold.

You can change it to `Ctrl+Alt+1`.

How about the following?
- Compare: `Alt+=`.
- Set First: `Alt+[` (used in many apps for First).
- Clear: `Alt+-` (Minus).
- Clear All: `Ctrl+Alt+-`.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> Ctrl+Alt+F does not set as First; it's used for Fold.

You are right, I have missed that.
What about Alt-Shift-= for "Set First" (as a preparation phase before "Compare")?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I suppose you agree to
- Compare: `Alt+=`.
- Clear: `Alt+-`.
- Clear All: `Ctrl+Alt+-`.

,correct?

I'm not sure I understand why you prefer `Alt+Shift+=` (for "Set First") over the shorter `Alt+[`.
Also, "Set First" is the first command and IMO it would be somewhat strange if it had a longer combination than the next one.
If you decide not to use `Alt+[`, I think `Ctrl+Alt+=` would be more consistent with the other shortcuts.

Thank you.
BR

**Comment by xylographe** [comment]
["But we don't have to use Alt which opens a menu."](https://github.com/pnedev/compare-plugin/issues/43#issuecomment-208593945) :grinning:

**Comment by Yaron10** [comment]
In that thread you corrected me that pressing Alt does not open the menu but rather underlines its keyboard accelerators. I agreed.

There was still a problem with Alt+Letter. We're now discussing Alt+Non-Letter which does not conflict with Windows convention whatsoever.

Sorry for wiping out that grin.

**Comment by pnedev** [comment]
Hello Yaron,

I changed "Set First" shortcut to _Ctrl-Alt-1_.
This makes the shortcuts more 'alike'.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. 
Thank you.

BR
