### ISSUE TITLE
Caret position after Clear Compare

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#66]
Hello Pavel,

A bug in NPP:
Have two files open in Single-View mode.
Move to Other View.
Move the caret in both files.
Move to Other View (the one moved earlier).

Result:
The moved file's caret position is preserved (correct).
The caret in the other file is back to its pre-Move position (wrong).

**Now to CP.**

Case 1:
Single-View.
Compare.
Move the caret in both files.
Clear.

Result:
The old file's caret position is preserved.
The caret in the new file is back to its pre-Compare position.

*

Case 2:
Double-View.
Compare.
Move the caret in both files.
Clear.

Result:
Both files' caret position is preserved.

*

I think that preserving the recent position makes more sense.
(Just like the recent active file preserves its state and you do not activate the original active one).

What do you think? Would it require a lot of work?

NOTE:
A case where the caret position was in an alignment line seems to be handled well (when the recent position is preserved).

Thank you very much.
Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Tomorrow :)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Sure. :) 
Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

It appears to be a N++ issue when moving a file between views.
There isn't much I can do about it (at least there is no workaround that is efficient enough), sorry.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for trying. :) I do appreciate it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

The first from https://github.com/pnedev/compare-plugin/issues/89#issuecomment-257405459.
Thanks again. :)

After comparing two files I, quite often, want to concentrate on a specific segment in one of the files.
I prefer to Clear Compare first for two reasons:
1) The segment may contain some blank alignments lines.
2) It's more convenient to work with a single view.

Currently I need to add a bookmark to the segment before Clear Compare.

I was wondering if the following simple steps should work.
1) After clearing the Compare diffs and *before* moving one file back to its original view, save its caret position.
2) After moving the file back to its original view, it is the active document - go to the *saved* caret position.
3) Activate the active file before Clear Compare (current behavior).

NOTE:
The caret position may not be in the visible section.
So, ideally both the caret position and the first visible line should be saved and restored.
But, IMO, saving and going to the caret position would suffice and be a significant improvement.

What do you think?
***
> 1) The segment may contain some blank alignments lines. 

A possible enhancement *for a future version*:
A new command: Toggle (Hide/Display) Alignments Lines.

I often want to copy a segment to a third file (without Clear Compare).
If it contains some 20 alignments Lines, I then need to manually remove them from the third file.

I don't know how complex the implementation might be and if it's worth it at all (compared to Clear and re-Compare).

Thank you very much. I appreciate your time and great work.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I was wondering if the following simple steps should work.
> 1) After clearing the Compare diffs and before moving one file back to its original view, save its caret position.
> 2) After moving the file back to its original view, it is the active document - go to the saved caret position.
> 

Some confusion in those lines: the problem is not with the moved file but rather with the other one (as mentioned in the first post here).
***
Anyway, the following change in Notepad_plus.cpp seems to fix this issue and also https://github.com/pnedev/compare-plugin/issues/94#issuecomment-255371385.

Replace

```
	else	//open the document, also copying the position
	{
		loadBufferIntoView(current, viewToGo);
		Buffer *buf = MainFileManager->getBufferByID(current);
		_pEditView->saveCurrentPos();	//allow copying of position
		buf->setPosition(buf->getPosition(_pEditView), _pNonEditView);
		_pNonEditView->restoreCurrentPos();	//set position
		activateBuffer(current, viewToGo);
	}
```

with

```
	else	//open the document, also copying the position
	{
		BufferID currentUnfocused = _pNonEditView->getCurrentBufferID();

		if (currentUnfocused != BUFFER_INVALID)
		{
			Buffer *bufUnfocused = MainFileManager->getBufferByID(currentUnfocused);
			_pNonEditView->saveCurrentPos();
			bufUnfocused->setPosition(bufUnfocused->getPosition(_pNonEditView), _pEditView);
		}

		loadBufferIntoView(current, viewToGo);
		Buffer *buf = MainFileManager->getBufferByID(current);
		_pEditView->saveCurrentPos();	//allow copying of position
		buf->setPosition(buf->getPosition(_pEditView), _pNonEditView);
		_pNonEditView->restoreCurrentPos();	//set position

		if (currentUnfocused != BUFFER_INVALID)
			_pEditView->restoreCurrentPos();

		activateBuffer(current, viewToGo);
	}
```

It doesn't deal with the root of the problem but it works (not tested long enough though).

As this is a NPP issue I suppose you wouldn't like to delve into it and submit a PR. Or would you? :)

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

As I have written before

> It appears to be a N++ issue when moving a file between views.
There isn't much I can do about it (at least there is no workaround that is efficient enough), sorry.

I will re-assess if there is something I can do to work-around that N++ problem but I cannot promise anything.

The best thing would be to submit a new issue on N++ project page describing the problem (not the CP case but rather the simple "Move to other view" behavior). You can submit a PR with your fix then that references the issue you created. I'm pretty sure the people tracking the N++ issues will pay attention to this problem.

I'll get back to this as soon as I have finished with the current CP bugs I'm fixing.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I'll get back to this as soon as I have finished with the current CP bugs I'm fixing.

Thank you very much. I appreciate it.
And thanks again for your ongoing work.

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2541

BR

**Comment by pnedev** [comment]
Hello Yaron,

This will be tedious to fix in CP and (being a N++ issue actually) I consider it inappropriate to make inefficient patches addressing this here.
It is better if those efforts are aimed at fixing the root cause in N++.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again for looking into it. I do appreciate it.

@SinghRajenM has submitted some excellent PRs to NPP.
I've asked him to review my proposed solutions to this issue and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2277.

BR

**Comment by pnedev** [comment]
Hello Yaron,

OK, that's the right route to go on this.
Thanks.

BR

**Comment by Yaron10** [comment]
Fingers crossed. :)

BR

**Comment by SinghRajenM** [comment]
@Yaron10 
Due to my current busy schedule, I couldn't find time to work on this. I will check it on this weekend and will do whatever I can. Thank you!

**Comment by Yaron10** [comment]
Hello @SinghRajenM,

Thank you very much. Pavel, myself and many other users would appreciate it. :)

Best regards.

**Comment by Yaron10** [comment]
Hello @SinghRajenM,

Allow me to thank you here again. 
I appreciate your kindness.

Best regards.

**Comment by SinghRajenM** [comment]
You're welcome! :)

**Comment by pnedev** [comment]
Hello @SinghRajenM ,

Excellent work, thanks.

BR
