### ISSUE TITLE
Set First: Two minor issues

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#67]
Hello Pavel,

STR:
Set First.
Switch to another file.
Set First.

Result:
The "Clear Active Compare" command is disabled.
***
STR:
Set First.
Open the Settings dialog.
Press OK (without changing anything).

Result:
First is cleared.

*
And if the user "Set First", opens the Settings dialog and changes the `First is:` setting?
Current behavior (First is cleared) seems fine.

Thank you.
BR

**Comment by xylographe** [comment]
Hello Yaron & Pavel,

Confirming (1)  \[aa489eec303516003d36df8d1a705099236de15c]

(2) seems reasonable behaviour to me.

**Comment by pnedev** [comment]
Hello guys,

1) is fixed.
2) is made on purpose. Clearing First when Pressing OK without changing anything is not important and doesn't hurt.

Thanks for the catch Yaron.

BR

**Comment by xylographe** [comment]
Fix confirmed (CP b6918e2faa481a2af4535ba514bf46eb7e103eed).

Thank you, Pavel.

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much.

BR
