### ISSUE TITLE
Known Issues / Reminders

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#68]
https://github.com/pnedev/compare-plugin/issues/66.
https://github.com/pnedev/compare-plugin/issues/48.
***
***********EDIT: FIXED***********

Reminder:
In a RTL interface NPP flips horizontally the toolbar buttons.
The Replace button (A-B) is particularly weird.

And so is the Set First button ("1" flipped).
When you announce the new version, you can offer a RTL version (with slightly different icons, not just flipped).
Alternatively you can refer RTL users to the CT plugin.

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for summarizing here the known issues. :+1: 

I don't want to make several releases - it's tedious and is something that's not interesting to me. It is just a routine work and I find it rather boring. Besides, then we would need to have several CP versions in the Plugin Manager which is a mess.

Is it possible to make the button bitmaps universal to both LTR and RTL?

Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Only one version in the Plugin Manager.
I'll provide the RTL version if you don't mind (so it's a reminder to myself).
If you do mind, just mention the issue in the Help section and refer the users to CT.

> Is it possible to make the button bitmaps universal to both LTR and RTL?

I've done my best. It would require a professional designer.

Thank you.
BR

**Comment by Yaron10** [comment]
Start NPP.
Open 2 new empty files.
Compare.

Result:
The second file is closed.

https://github.com/pnedev/compare-plugin/issues/17#issuecomment-199055849
https://github.com/pnedev/compare-plugin/issues/64#issuecomment-220547911

**Comment by Yaron10** [comment]
https://github.com/pnedev/compare-plugin/issues/63#issuecomment-220590047

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for adding that to the known issues list.
I'll fix that later by checking if both files are empty.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> I've done my best. It would require a professional designer.

You've done a really great job. :+1: 

> Only one version in the Plugin Manager.
I'll provide the RTL version if you don't mind (so it's a reminder to myself).

OK, that's perfect.
How are you going to distribute the RTL version? Just link it in the Plugin forum of N++ community?
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you.

> I'll fix that later by checking if both files are empty.

Is my suggestion to programmatically open a new file implementable?

> How are you going to distribute the RTL version? Just link it in the Plugin forum of N++ community?

Yes, a link in the forum.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> Is my suggestion to programmatically open a new file implementable?

Unfortunately no (at least the amount of code is not worth it).
I'll think about what I can do but that's really not that critical issue.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I've added the RTL button bitmaps also. Now CP detects if it is in RTL mode and loads the corresponding icons. Could you give latest master a try? Thanks.

I will also need the RTL version of the "Set First" bitmap - it seems you have forgotten to send it to me.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Is my suggestion to programmatically open a new file implementable?
> 
> Unfortunately no (at least the amount of code is not worth it).
> I'll think about what I can do but that's really not that critical issue.

The best apps have some Known Issues.
IMO this can be one of CP. :)
***

> I've added the RTL button bitmaps also...

That's great.
I actually thought about it but didn't want to suggest it.
Thank you.

The RTL icons have to be flipped so that when NPP flips them they would be displayed properly. :)
The "Set First" image is the same for LTR and RTL (just flipped); the others are slightly different.
As I uploaded the RTL icons *not* flipped (for whoever might be interested), I didn't include FirstToCompareRTL.

Are you flipped now? :)

[Here](https://github.com/pnedev/compare-plugin/files/276662/IconsRTL.zip) are the right RTL icons.

BR

**Comment by pnedev** [comment]
Hello Yaron,

The icons in RTL should be flipped horizontally (across the Y axis) right?
I see a difference only in FirstToCompareRTL. All other bitmaps seem the same as the LTR versions.
Are you sure those are needed?
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Yes, the RTL icons should be flipped horizontally.

The images' frame (*except FirstToCompare*) should represent a "window".
If you just flip them, the frame's gradient and other minor elements would not be displayed as intended.
So there's a difference between the LTR and the RTL icons.

Having said that, it's not *that* important. The other three icons would be OK flipped by NPP.
It would be fine if you prefer to reduce the resources and only use FirstToCompareRTL. 

Thank you.
BR

**Comment by Yaron10** [comment]
> It would be fine if you prefer to reduce the resources and only use FirstToCompareRTL. 

If you prevent NPP from flipping FirstToCompare or re-flip it, you wouldn't have to use FirstToCompareRTL either.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I decided to use only FirstToCompare RTL bitmap.
The others' differences between LTR and RTL variants are hardly noticeable.
The changes are in latest master commit.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

That's a good decision. Most people wouldn't notice the difference.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I'll close this thread and open Known Issues / Reminders (2).
Thanks.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks.

BR
