### ISSUE TITLE
Some more modified Text Strings

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#7]
Replace
`:MessageBox(nppData._nppHandle, TEXT("No file to open"), TEXT("error"), MB_OK);`
with
`::MessageBox(nppData._nppHandle, TEXT("No file to open."), TEXT("Compare Plugin"), MB_OK);`
***
Replace
`MessageBox(nppData._nppHandle, L"Can't locate SVN information", L"ComparePlugin", MB_OK);`
with
`MessageBox(nppData._nppHandle, L"Can not locate SVN information.", L"Compare Plugin", MB_OK);`
***
Replace
`MessageBox(nppData._nppHandle, L"Can't locate GIT information", L"ComparePlugin", MB_OK);`
with
`MessageBox(nppData._nppHandle, L"Can not locate GIT information.", L"Compare Plugin", MB_OK);`
***
Replace
`::MessageBox(nppData._nppHandle, TEXT("Nothing to compare!"), TEXT("Error"), MB_OK);`
with
`::MessageBox(nppData._nppHandle, TEXT("No files to compare."), TEXT("Compare Plugin"), MB_OK);`

Thank you.

**Comment by Yaron10** [comment]
Replace
`::MessageBox(nppData._nppHandle, TEXT("Notepad v4.5 or higher is required to line up matches. This feature will be turned off"), TEXT("Incorrect Version"), MB_OK);`
with
`::MessageBox(nppData._nppHandle, TEXT("Notepad v4.5 or higher is required to line up matches. This feature will be turned off."), TEXT("Compare Plugin"), MB_OK);`

**Comment by pnedev** [comment]
Merged to master, thanks
