### ISSUE TITLE
Other tab is activated when "Different Encoding" message is displayed

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#71]
Hello Pavel,

A minor issue.

STR:
Compare two files using different encoding.

Result:
The prev/next tab is activated when the "Different Encoding" message is displayed.
Users might consider this behavior slightly strange.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, thanks for reporting.
This saves me some coding, I'm not sure it's worth it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I understand the move to the prev/next tab is performed before the encoding check.

This is indeed a minor issue but IMO it's worth some extra coding (a common operation and a strange behavior).
I know it's easier said than done. Please don't mind my expressing this view. :)

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

No problem, I'll see what I can do.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

This should be fixed in latest master commit.
Could you please check? Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Special thanks for that. :+1: 

BR
