### ISSUE TITLE
"Files Match" is displayed after canceling Compare

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#72]
Hello Pavel,

STR:
Compare two large files.
Press Cancel in the Progress Bar.

Result:
The "Files Match" message is displayed.

Thank you.
BR

**Comment by Yaron10** [comment]
Hello again Pavel,

Two more issues with the Progress Bar.

1) The wrong file is active-focused while the Progress Bar is displayed.
Probably related: https://github.com/pnedev/compare-plugin/issues/71.

2) The Cancel button has the focus but pressing Enter does not work.
This problem existed before the Old/New refactoring.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for reporting, I'll have a look soon.

BR

**Comment by pnedev** [comment]
Hello Yaron,

The first issue is fixed (reporting files are equal on compare cancel).
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. :+1: 

BR

**Comment by pnedev** [comment]
Hello Yaron,

> 1) The wrong file is active-focused while the Progress Bar is displayed.

This should be fixed in latest master commit.
Could you please check? Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great! Thank you very much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> 2) The Cancel button has the focus but pressing Enter does not work.

This is also fixed. I'm closing this issue now.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. It works like a charm.
Allow me to compliment you again: I'm really impressed by your work. :)

I've had a busy day. I'll refer to the other issues later.

BR

**Comment by pnedev** [comment]
Thank you, Yaron.

BR
