### ISSUE TITLE
Separate git dir not supported

### ISSUE THREAD

**Issue by xylographe** [pnedev/compare-plugin#75]
Git repositories created with `git init --separate-git-dir` contain a `.git` *file* instead of a `.git` *directory*. The `.git` file acts as a filesystem-agnostic Git symbolic link to the repository.
Content example, (one line terminated by a single LF [not preceded by CR])
```
gitdir: //cardea/xg/Repos/NppComparePlugin
```

**Comment by pnedev** [comment]
Hello @xylographe ,

I'll check this, thanks for reporting.

BR

**Comment by pnedev** [comment]
Hello @xylographe ,

Could you please try this commit https://github.com/pnedev/compare-plugin/commit/4048c06fc4ffe168f4f45be3c3093b4d384cfd1b ?
Tell me if it is working or not, thanks.

BR

**Comment by xylographe** [comment]
Hello Pavel,

Sorry, the result with CP build from your 'gitpath' branch is the same : "No Git data found."

Running `git grep -F 'gitdir:'` ==> "Binary file src/LibGit2/git2.dll matches"
Which would suggest the git2 lib should be able to handle the filesystem-agnostic Git symbolic link.

**Comment by pnedev** [comment]
Hello @xylographe ,

Thanks for testing.
I'll merge the changes to master anyway because I have reworked the Git and SVN diff handling code.
I'll continue with this issue later.

BR

**Comment by xylographe** [comment]
Hello Pavel,

Apparently, `git_repository_open_ext()` succeeds (return value zero).
Tested with these lines : 
```
		if (git_repository_open_ext(&repo, ansiCurrDir, 0, NULL))
		{
			::MessageBox(nppData._nppHandle, TEXT("git_repository_open_ext != 0"), TEXT("Compare Plugin"), MB_OK);
			return NULL;
		}
		else
		{
			::MessageBox(nppData._nppHandle, TEXT("git_repository_open_ext == 0"), TEXT("Compare Plugin"), MB_OK);
		}
```

**Comment by pnedev** [comment]
Hello @xylographe ,

Yes, I know, I made some tests on my own.
I created git repo with filesystem-agnostic link.
`git_repository_open_ext` manages to read the link properly and the repo path is found successfully.
The problem is in my code when I try to get the relative path as repo path and source path are not sharing common root.
I'll fix that most probably this evening, it's just a matter of time.

Thanks for investigating.

BR

**Comment by xylographe** [comment]
Hello Pavel,

`git_index_find(&at_pos, index, ansiGitFilePath)` returns `GIT_ENOTFOUND`.

Tested with 4dcb3d1ca1809bec87fe5b4c0d36c1d30f9dd9aa

Perhaps, the problem is that `ansiGitFilePath` contains an absolute path?

**Comment by pnedev** [comment]
Kind of. `ansiGitFilePath ` is empty string.
This is because RepoRelativePath is unable to find relative path - the repo folder and the source folder are not sharing a common root. I just need to get the folder where .git link file is and create relative source path to this.

**Comment by xylographe** [comment]
Thank you for the explanation, Pavel. I can now see where it's going wrong.

**Comment by xylographe** [comment]
Hello Pavel,

Using `git_repository_workdir()` i/o `git_repository_path()` (as in 41d1c561f0154ec3fb109adcecfd9f358f6b14bd) gets the right path.

**Comment by pnedev** [comment]
Hello @xylographe ,

Thank you for the reference.
I have fixed the issue in master.

BR
