### ISSUE TITLE
Wrong "Files Match" if both compared files consist of only one line

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#77]
Hello Pavel,

STR:
File 1: a.
File 2: b.
Compare.

Result:
Files Match.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll look into this, thanks for catching it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

This problem must have started in one of the recent commits.
It doesn't exist in https://www.dropbox.com/sh/f42cxkqppuapa1j/AAAOMcOIyqO2UTqN3o5N4cUKa/cp-pnedev-0030-65c3d573afbc53c5e9902b6857ce3e5895c38765.7z?dl=0 from ten days ago.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I know what's causing this and I have fixed that in the tmp branch but there are some other related issues that I'd like to investigate first.
Thanks for investigating.

BR

**Comment by pnedev** [comment]
Hello Yaron,

This is fixed in latest master.
There are some issues regarding the last line if comparing empty doc but those are another matter.
I'll look them later.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I appreciate it.

Would you like to open a new issue? :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

I don't know how to formulate the potential new issue.
When I get to that I'll open it, thanks.

BR

**Comment by pnedev** [comment]
Well, just to have it in the record I'll open an issue "Check compare ending lines"

Thank you, Yaron.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Would you like to open a new issue? :)

I suggested it half jokingly.
Thanks for doing that.

BR
