### ISSUE TITLE
Temp file is not discarded if moved to other view

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#78]
Hello Pavel,

This is your issue in https://github.com/pnedev/compare-plugin/issues/70.

> Just FYI - When you are in a diff compare mode and you move the temp file it will remain open in N++ but the temp file itself will be deleted. I'll think how I can fix that.

As you've written https://github.com/pnedev/compare-plugin/issues/70 is too clattered and hence this new issue. :)

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for filing this issue.

BR

**Comment by pnedev** [comment]
Hello Yaron,

The issue is fixed.
Please note that some regressions are possible. This is because some refactoring was necessary.
If you come across something weird please report as always. Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great.
Thank you very much for this too. 

BR
