### ISSUE TITLE
Check ending lines when comparing files of different sizes

### ISSUE THREAD

**Issue by pnedev** [pnedev/compare-plugin#79]
When a single line file (without EOL symbol) is compared against file with several lines there is something weird in the last lines of the compare results.

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again.

Do you mean the empty line 5?

![InsertText](http://s33.postimg.org/qp838855r/image.png)

BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, indeed.

BR

**Comment by Yaron10** [comment]
Thank you Pavel.

BR

**Comment by pnedev** [comment]
The issue is fixed with the latest commit.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for that too. Great.

BR
