### ISSUE TITLE
Implement separate setting for prev/next file auto-selection in single view compare

### ISSUE THREAD

**Issue by pnedev** [pnedev/compare-plugin#81]

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much for adding this setting.

Continued from https://github.com/pnedev/compare-plugin/issues/64#issuecomment-223498057:
That's good. Or `Default compared file in Single-View: Previous/Next`.

BR

**Comment by pnedev** [comment]
Hello all,

This is implemented in master branch.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again. I appreciate it.

I've seen your title of https://github.com/pnedev/compare-plugin/commit/18e982345f1cc72a4a95b3ebee2c787711868ede and I think it's good and much clearer.

How about adding "old file" to the setting as well?
`Default old file in Single-View Compare`.
Anyway, "Single-View" would be better than "Single view " IMO. :)

I think that using "Old File" (capital letters) in Settings reduces the literalness of  the words and slightly transforms them into a term.
Your opinion?

BR

**Comment by xylographe** [comment]
Hello Yaron and Pavel,

I think, the wordings are fine as they are. Title case belongs in the dialogue caption ("*Compare Plug-in Settings*"), not in the text of labels and other controls.

Not sure if the hyphen ("*Single-view default compare to*") is necessary, as it would be, for example, in "*a single-view environment*".

**Comment by pnedev** [comment]
Hello Yaron,

> How about adding "old file" to the setting as well?

This adds clarity, I agree but I didn't add it initially because of the width of the settings dialog.
I need to keep the text as concise as possible. Otherwise the width becomes too big and the overall appearance of the settings dialog will suffer.

> Anyway, "Single-View" would be better than "Single view " IMO

I agree but "Single-view" is better IMO because it becomes a kind of single word term.

About the "Old File" I agree with @xylographe  - it is better as it is. Perhaps you are right and it really does reduce the literalness of the words but it is very subtle to grasp. Besides, the real term there is "New" / "Old" (like for example "Base", "Focal", "Original".. etc). "file" is just to be specific (for clarity and completeness).

Hello xylographe,

> BTW the hyphen in 'plug-in' is actually mandatory

That's true but the term "plugin" is so popular in today's SW - it has become a well-known and accepted word. At least in N++ it is so commonly used.

Thank you both.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

As you understand. :) 

Thank you.
BR
