### ISSUE TITLE
Different Encoding: Some Questions

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#82]
Hello Pavel,

When comparing a Windows-1255 file to a UTF-8 file, the warning is not displayed.

A more general question with your permission:
Is *any* encoding difference might lead to inaccurate results?
For example: UTF-8-BOM vs. UTF-8-NO-BOM.

Is there a formula for that (i.e. different formats which might actually lead to inaccurate results)?
If positive, is implementing it worth while?
If negative, wouldn't it be a good idea to give the user an option not to display the warning?  

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll write soon.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> any encoding difference might lead to inaccurate results?

Perhaps no.

> Is there a formula for that (i.e. different formats which might actually lead to inaccurate results)?

There might be but I am really not familiar with different encodings and I'm not able to derive one.

> If positive, is implementing it worth while?

Absolutely.

> If negative, wouldn't it be a good idea to give the user an option not to display the warning?

I don't know but why? Is this warning so frustrating and/or disturbing? It is just a reminder and a notification that the user cannot trust the results a 100%.
I would like to avoid crowding the Settings dialog as much as possible. I'd like to keep there only the settings that actually do add value and are really useful.

> When comparing a Windows-1255 file to a UTF-8 file, the warning is not displayed.

Could you send me an example files that I can test?
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Is this warning so frustrating and/or disturbing?

Not to me personally.
It might be if some users regularly compare different encoded files which do not present a problem.
I don't know. You can wait for feedback from users after announcing the new version.

> Could you send me an example files that I can test? 

[Test.zip](https://github.com/pnedev/compare-plugin/files/301389/Test.zip).

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> It might be if some users regularly compare different encoded files which do not present a problem.

You are right about that.
Being able to switch off encoding warning might really be useful in that case.

I've created another issue for that, thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes indeed, the warning is not displayed.
Could you please try again but after really adding a Hebrew letter/word in the 1255 file?
I suspect N++ does some kind of file auto-detection.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for adding the setting. I think it's a good decision.

Adding a Hebrew letter makes no difference.
Interestingly - comparing UTF-8 *with BOM* to 1255, the warning is displayed.
Isn't it related to https://github.com/pnedev/compare-plugin/issues/70#issue-156075996?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'm really not familiar with different encodings. I'm using N++ plugin API to get the encoding of each file and compare those. It appears that in some cases those are matching (although they seem different). Perhaps N++ itself is using some kind of formula (like the one you suggested several posts up), I don't know. Perhaps 1255 is a sub-set of UTF-8.

> Isn't it related to #70 (comment)?

Not exactly.

This "issue" is not a problem by itself but if we get wrong compare results when we do compare files with 1255 and UTF-8 encodings then we'll have a problem.
We'll need similar files so we know if the results are wrong.

Thanks Yaron.

BR

**Comment by xylographe** [comment]
Hello Pavel,

NPP uses [Uchardet](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/src/uchardet) to detect text encoding.

**Comment by pnedev** [comment]
Hello @xylographe ,

Interesting, thank you for the info.
Anyway, I'll leave the encoding detection to N++.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for looking into it and for the explanation. I do appreciate it.

> Anyway, I'll leave the encoding detection to N++.

That's absolutely fine.
Should I add it as a minor (NPP) issue to the Known-Issues list?
***
Hello xylographe,

Thanks for the input.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> Should I add it as a minor (NPP) issue to the Known-Issues list?

I trust your judgement on this, thank you.

I'm closing this issue now.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again.

BR
