### ISSUE TITLE
Set First: Clear is wrongly disabled

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#86]
Hello Pavel,

I had a "real" compare session yesterday. It's a pleasure using CP now.
Thanks again for your great work.

I encountered the following issue:

STR:
Open three files.
Compare.
Switch to the not-compared file.
Set First.
Switch to one of the compared files.
Switch back to the not-compared file.

Result:
"Clear Active Compare" is disabled.

BR

**Comment by pnedev** [comment]
Hello Yaron,

This is fixed. Thanks for catching it and reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much for the quick fix. I appreciate it.

BR
