### ISSUE TITLE
Deleted line's marker is moved to next line in some cases

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#88]
Hello Pavel,

Thanks again for https://github.com/pnedev/compare-plugin/commit/41d35747af3b0342d79ca4fb82c863e1f7c2d3fe. I find it very helpful.

Could you please compare [these](https://github.com/pnedev/compare-plugin/files/309984/prefs.zip) files and repeat the following STR?

Delete line 43 in prefsNew.js (the marker is removed - OK).
Copy line 65 from prefsOld.js and replace line 64 **(65 before the deletion)** in prefsNew.js with it (the marker is removed - OK).
Select lines 78+79 in prefsNew.js and delete them  (the marker is moved to the next line - wrong).

Thank you for looking into it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll have a look, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

This is fixed, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great! :+1: 
Special thanks for that.

BR
