### ISSUE TITLE
Wrap Mode: A diff might be missed

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#90]
Hello Pavel,

Could you please look into the following issue?

STR:
Set NPP window to 985*732 (in config.xml: `<GUIConfig name="AppPosition" x="300" y="4" width="985" height="732" isMaximized="no" />`).
Wrap Mode: On.
Compare [these](https://github.com/pnedev/compare-plugin/files/353279/prefs.zip) files.
Press "Next" 7 times (do not scroll).

Result:
Line 106 (added in prefsNew.js) is not visible and the user might miss that diff.

NOTE: 
1) An important issue IMO.
2) The behavior in CP 1.5.6.4 is different.

When you have some free time. :)
Thank you very much.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

I'll check that, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I appreciate it.

(Tested in Top/Bottom layout).

BR

**Comment by pnedev** [comment]
Confirmed in Left/Right layout also, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for testing. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

The issue is fixed, thanks for catching it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. Thank you.

And special thanks for synchronizing the vertical scroll of long wrapped lines.
I discussed the issue with UFO at the time. :) 
This is another major improvement and I'm really impressed by your work. :+1:

Testing it now, I came across another interesting [issue](https://github.com/pnedev/compare-plugin/issues/92).

Best regards.

**Comment by Yaron10** [comment]
Hello Pavel,

Regarding the synchronized vertical scroll of long wrapped lines.
This is an important improvement. Thanks again.

It has, however, a downside in the following case:
Compare [these](https://github.com/pnedev/compare-plugin/files/387300/prefs.zip) files.
When you scroll to line 63 in prefsNew.js, both files are in 63.
When you scroll to line 64 in prefsNew.js, prefsOld.js jumps back to line 55 (depending on the window width).

Related: https://github.com/pnedev/compare-plugin/issues/51.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, I've noticed that behavior.
I'm working on a solution, thanks for the feedback.

BR

**Comment by pnedev** [comment]
The issue is fixed, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Absolutely brilliant! One of your best. :)

Ready for one more push?
Comparing [these](https://github.com/pnedev/compare-plugin/files/389352/prefs.zip) files and scrolling one line at a time (of the wrapped line 64, prefsNew.js) - seems great.
Doing the same in [these](https://github.com/pnedev/compare-plugin/files/389356/prefs2.zip) files - the behavior is somewhat less intuitively expected.

I haven't fully analyzed it. What do you think?

(`<GUIConfig name="AppPosition" x="300" y="4" width="985" height="732" isMaximized="no" />`).

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I couldn't see any problem.
Do you mean that the diffs inside line 64 are not aligned?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

In the second pair of files, the first half of line 64 is equal.
Yet - when scrolling one line within line 64 in prefsNew2.js, prefsOld2.js [doesn't come along](https://s31.postimg.org/6i96vymnv/image.png). :)

I suppose that adding the diffs-inside-wrapped-lines factor would be too complex. Is that correct?

Many thanks.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, that would be complex.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for confirming.
And thanks again for your great work.

BR
