### ISSUE TITLE
A diff is skipped if the cursor is in an adjacent line 

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#92]
Hello Pavel,

STR:
Place the cursor *one line* before a diff.
Press "Next".

Result:
The next diff is skipped and we move to the diff following it.

NOTE:
The same is true in reverse.
Place the cursor *one line* after a diff.
Press "Prev". 

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Confirmed and fixed, thank you for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. :+1: 
Thank you very much.

BR
