### ISSUE TITLE
Compare with "Ignore Spaces" is occasionally throwing exception

### ISSUE THREAD

**Issue by pnedev** [pnedev/compare-plugin#93]

**Comment by Yaron10** [comment]
Hello Pavel,

That might explain the crashes I experienced some time ago.
Have you been able to pinpoint the cause? STR?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Unfortunately not.
It is not happening consistently, I need to investigate further.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Good luck. :)
Thank you.

BR

**Comment by pnedev** [comment]
I have been doing comparisons with "Ignore Spaces" option on extensively since I posted this issue and never had any problems so I'm closing it now.
I'll reopen it again if I ever come across this again.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for the update.
I usually have "Ignore Spaces" checked and haven't experienced any crashes since that session a couple of months ago.

BR

**Comment by pnedev** [comment]
Thanks for the feedback, Yaron.

BR
