### ISSUE TITLE
Position is not preserved when switching between Compares

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#94]
Hello Pavel,

STR:
Compare two files.
Move to a specific line (20 for an easier illustration).
Compare another pair of files.
Move to a specific line  (80 for an easier illustration).
Switch between the two Compares.

Result:
The line position is not preserved.

*

NOTE:
1) If you can't reproduce it after switching once, please try again.
2) There seems to be a regression caused by a recent commit: testing the issue with https://www.dropbox.com/sh/f42cxkqppuapa1j/AAABBiMpPMSKMM2nkasGF6fea/cp-pnedev-0070-3cec468af3ca457fd8132c88b6e0fdc3a481eb0b.7z?dl=0 - the problem only happens when switching between two Compares _and from one view to the other_.
With the [current latest commit](https://github.com/pnedev/compare-plugin/commit/1cd106e97ea6170a2b9556a5e4b8c770b7942b48) it occurs even when switching in the same view.

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for reporting.
Unfortunately I am unable to reproduce the issue on my Linux machine under Wine. I changed the files many times and the cursor position didn't change.
I'll try later on Windows but meanwhile, although you have described everything very clearly (as always), can you give me an even more detailed step-by-step instruction how you reproduce the issue. For example "Compare A and B. Switch to C. Set as first....." etc.
Thank you.

BR

**Comment by pnedev** [comment]
Hello again,

I think I reproduced the issue.
The cursor position is not changed (as I initially interpreted your report) but the "visible" position is changed - the first visible line of the compared docs.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I indeed meant the visible position. Sorry for the confusion.
Thank you for looking into this. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

No problem. Can you try recreating the issue with the last master branch commit?
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Problem solved when switching in the same view. :+1: 

Could you please try the following steps?
Activate file A at top.
Activate file B at top.
Activate file C (compared to A) at bottom.

Result:
The visible section is changed.

Thanks again for your great work.
BR

**Comment by pnedev** [comment]
Hello Yaron,

The problem should be fully-solved.
That was a good catch, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Excellent! As always - I'm truly impressed.
Thank you very much.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

When the 64-bit issues are settled (thanks again), could you please try the following steps?

Open two files and Compare.
Open a third file.
Move (the third file) to Other View.
Activate the compared file in the view containing now the third file.

Result:
Position is not preserved.

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I followed the steps and I cannot see any problem. What am I missing?
What are your Left/Right, Old/New configurations?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

The issue occurs in all possible settings.

**Start NPP**.
Open two files and Compare.
Open a third file.
Move (the third file) to Other View.
Activate the compared file in the view containing now the third file.

Result:
Position is not preserved.
** That is: the visible section is changed**.

*

I may not be by my PC until Monday.

Thank you very much. I appreciate your work.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I see the problem now. I was again thinking about the file tabs position and not the cursor position.
I'll see what I can do, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I've just read your reply.

Sorry for the confusion.
And thank you for looking into it. Highly appreciated as always.

BR

**Comment by pnedev** [comment]
Hello Yaron,

This is a N++ issue that appears when moving files between the views.
There is one simple work-around for this:
If I make the caret line position in one compared file mirror the other then this won't appear.
For example if you change the caret line position in file A from line 30 to line 240 then the caret position in file B will automatically move to line 240.
Tell me what you think about that.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

For my personal use, the solution proposed in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2541 solves this problem too.
(BTW, thanks for the "Thumbs up"; just saw it). 

But it might be important for other CP users.
 
I think your suggestion is great.
I was actually thinking about suggesting it for a different reason.
STR:
Compare.
Press "Next" a few times.
Activate the other compared file *by clicking on its tab*.
Press "Next".

Result:
You are back in the first diff (slightly strange IMO).

I did not suggest it because I thought the advanced user might consider this the expected behavior in NPP. 

So, what do you think? A preference?

Thank you very much. Highly appreciated.
BR

**Comment by Yaron10** [comment]
Hello again,

> There is one simple work-around for this:
> If I make the caret line position in one compared file mirror the other then this won't appear.

Are you sure this would work?
If you *manually* change the caret position it is not preserved.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> Are you sure this would work?
If you manually change the caret position it is not preserved.

Yes, you are right. This doesn't help with the issue. I must have overlooked it when I've been testing it.

Anyway, I think it is a good feature and I have added it here https://github.com/pnedev/compare-plugin/commit/3034ff6c12538b303bf0035b22da6ffcb2e8bc88.

Thank you for the feedback.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for synchronizing the caret line position. I find it very helpful.
And I'm glad you consider the preference unnecessary.

Just as a fine-tuning: how about synchronizing the caret column position as well?
***
Should I close this issue?

BR

**Comment by pnedev** [comment]
Hello Yaron,

I made a work-around for this issue. Some regressions are possible though due to the refactoring.
Could you please try commit https://github.com/pnedev/compare-plugin/commit/fc06cf39e67fd0868939e1dd02d4fee65e67cbeb?
Thanks.

> Just as a fine-tuning: how about synchronizing the caret column position as well?

Why would we need that?
Compare process guarantees that the compared files will have equal number of lines (because of the added synchronization blanks) but that's not the case with the chars per line.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I made a work-around for this issue.

I'm impressed and curious. May I ask you to briefly explain the idea?

> Some regressions are possible though due to the refactoring.

I haven't come across any regressions. 👍 
***

> Why would we need that?

1) It's simply nicer.
2) When switching from one compared file to the other, the caret is usually visible (i.e. now that the line position is synchronized).
If, however, the first visible line in file A is the middle of a long wrapped line and you then switch to file B - the caret is not visible.
3) If you switch back to a file where you already (and intentionally) set the column position - the caret is positioned at the beginning of the line.
Wouldn't this be considered a minor bug?

> Compare process guarantees that the compared files will have equal number of lines (because of the added synchronization blanks) but that's not the case with the chars per line. 

If you click on column 15 and that line only contains 10 chars - the caret is positioned at the end of the line.
Wouldn't this be the case if you do that programmatically?
***
Synchronizing the caret position deselects selection(s).

STR:
Compare.
Select some text.
Switch to the other file.
 
Result:
The selection is deselected.

I wonder if using `setPosition()` instead of `::SendMessage(otherView, SCI_GOTOLINE, activeLine, 0);` would make a difference.
(I've come across `setPosition()` in Notepad_plus.cpp).
***
Thank you very much. Highly appreciated as always.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> May I ask you to briefly explain the idea?

Well, because both views are synchronized, on buffer re-activation I'm trying to guess which view to use as 'focal' for the new synchronization - if the moved file view is activated then use the other to sync again because there is a chance that the moved file has lost its position.

About the horizontal caret position synchronization only point 3 and the STR make sense to me and I have fixed those in the latest commits. I have also fixed a regression where if you create 2 new empty files and compare and chose not to close the compared identical files CP hangs. Further, I have also improved the position restoring described above because it still had some issues. Please try commit https://github.com/pnedev/compare-plugin/commit/be2ad5f7d7cbcbb845cb29f01f60773d7cc718b2 and write back if you have further concerns / comments. Thanks.

Thank you for testing and for the feedback.

BR

**Comment by pnedev** [comment]
Hello Yaron,

One more thing:
Please note that the position issue work-around fix works only if we are starting from the main view. That is, if you have file A in the sub view then compare files from the main view and then move the A file to main view the issue will appear again (position in the compared file in the main view will be lost).
The work-around is thus not universal but it covers the most common workflow / use-case.
I'll consider this bug closed now but any comments are welcome.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Well, because both views are synchronized, on buffer re-activation I'm trying to guess which view to use

Thanks for the explanation. I'd have to delve deeper into it. :)

> About the horizontal caret position synchronization only point 3 and the STR make sense to me and I have fixed those in the latest commits.

Clever and beautiful! 👍  

> I have also fixed a regression where if you create 2 new empty files and compare and chose not to close the compared identical files CP hangs.

Great. Hey, that's my job. :)

> Further, I have also improved the position restoring described above because it still had some issues.

👍 

> Please note that the position issue work-around fix works only if we are starting from the main view.

That's fine. It's certainly not a common use-case.

Thank you very much. Brilliant work.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks.

> I'd have to delve deeper into it.

Both compared files have the same view position. Now if you move another file you'll compromise one of them (the view position of the file in the moved view will be lost) but the other still holds the valid position. If you activate a compared file CP synchronizes the other file's view to the activated one. So if you activate the compromised file both files will get the wrong position. That's why in the work-around I'm trying to guess if the file's view has been compromised an if so on its activation to use the other file as a bias for the views synchronization. I hope that's a little bit clearer :)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again. It is clearer now. :)
👍 
BR

**Comment by Yaron10** [comment]
Hello Pavel,

With https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1ee8cbd21caceb387a2c772efe0883f26c719d0a, the workaround (https://github.com/pnedev/compare-plugin/issues/94#issuecomment-264865705) seems unnecessary.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, I suppose so. But it doesn't hurt so let's leave it for now.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Sure, as you understand.

Thank you.
BR
