### ISSUE TITLE
[Request] CP for NPP 64-bit

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#96]
Hello Pavel,

This is a [request](https://notepad-plus-plus.org/community/topic/12303/notepad-7-release-candidate/6) by Claudia Frank.

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, I saw the N++ v7 64-bit release and even before that - [this announcement](https://notepad-plus-plus.org/community/topic/12053/notepad-plugin-template-plugin-demo-x64-build-available).
64-bit CP version will need to be done at some point.
Thanks for filing an issue.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I assumed you were aware of the 64-bit release.
I thought that opening an issue would be a more respectful reply to Claudia.
I hope you don't mind. :)

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> I hope you don't mind.

Not at all :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

I haven't tested it myself and perhaps more modifications are needed but thanks to @chcg and @xylographe we now should be able to build CP for x64 targets.

I'll leave this request open until I check the x64 build myself.

BR

**Comment by xylographe** [comment]
I assume that we will need 64-bit `git2.dll` and `sqlite3.dll` ?

**Comment by pnedev** [comment]
Yes, correct. Haven't thought about that so far.

**Comment by Yaron10** [comment]
Hello Pavel, xylographe and chcg,

Thank you all.
BR

**Comment by marb99** [comment]
@xylographe 

can you please compile ComparePlugin.dll 64bit???

**Comment by xylographe** [comment]
@marb99 
Added `x64` folder to latest 7z-archive ([cp-pnedev-0094-*.7z](https://www.dropbox.com/sh/f42cxkqppuapa1j/AADvlcmqoK_myRmoOpeL1yGMa?dl=0)).
- The 64-bit `x64\ComparePlugin.dll` is untested. Looking at the huge number of "conversion" warnings at compile time, it will probably throw an exception (or crash). Save important files before testing!
- The `x64\ComparePlugin` folder is empty (no 64-bit `git2.dll` and `sqlite3.dll` yet). Hence, "Git Diff" and "SVN Diff" will definitely not work.

**Comment by marb99** [comment]
@xylographe 

thanks, for now it crash. I will wait a bit longer :)

thanks

**Comment by pnedev** [comment]
Hello all,

FYI:
Thanks to @chcg , apart from Git and SVN diff (which require external 64-bit DLLs) the 64-bit CP build should be functional now.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for the update and thank you all for your work.
I can't test it as my system is 32-bit.

Best regards.

**Comment by pnedev** [comment]
Hello all,

CP x64 is ready and completely usable.
You need to either compile it yourself for x64 or you can take it from
https://ci.appveyor.com/api/buildjobs/l6levanxkyh3f9la/artifacts/ComparePlugin.X64.Release%20Unicode.v120_xp.dll
You will also need to replace the git2.dll and sqlite3.dll files in your Npp_Install_Path\plugins\ComparePlugin\ folder with their 64bit versions from
https://github.com/jsleroy/compare-plugin/tree/master/libs/x64.

If you find any issue please report it here, thanks.

BR
